namespace Delta.ECS.Generators;

internal static class ComponentComparerTemplates
{
    internal static string Render(ComponentComparerModel model, IReadOnlyList<PredicateModel>? whereSources = null)
    {
        string hash = GeneratorSupport.StableName(model.Key);
        string comparerType = model.FunctorType;
        ComponentComparerSignature signature = model.Signature!;
        string idFields = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"private readonly global::Delta.ECS.ComponentId _componentId{index};", "\n");
        string idAssignments = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"_componentId{index} = componentIds[{index}];", "\n");
        string validation = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"world.ValidateGeneratedOrderedQueryKey<{model.ComponentTypes[index]}>(in query, _componentId{index});", "\n");
        string leftLocals = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"ref readonly {model.ComponentTypes[index]} left{index} = ref world.GetGeneratedOrderedQueryKey<{model.ComponentTypes[index]}>(left, _componentId{index});", "\n");
        string rightLocals = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"ref readonly {model.ComponentTypes[index]} right{index} = ref world.GetGeneratedOrderedQueryKey<{model.ComponentTypes[index]}>(right, _componentId{index});", "\n");
        string leftEntity = signature.HasEntity ? "global::Delta.ECS.Entity leftEntity = left;" : string.Empty;
        string rightEntity = signature.HasEntity ? "global::Delta.ECS.Entity rightEntity = right;" : string.Empty;
        string invokeArguments = ComponentComparerTemplateSupport.Arguments(
            signature.HasContext,
            signature.ContextMode,
            signature.HasEntity,
            model.ComponentTypes.Length,
            "_context",
            static index => $"in left{index}",
            static index => $"in right{index}");
        string primaryIds = string.Join(", ", model.ComponentTypes.Select(static componentType =>
            $"world.Layouts.GetPrimary(typeof({componentType}))"));
        string primaryOrderByIds = $"global::Delta.ECS.GeneratedForEachRuntime.GetGeneratedPrimaryComponentIds<{comparerType}>(in query, static world => new global::Delta.ECS.ComponentId[] {{ {primaryIds} }})";
        string primaryThenByIds = $"global::Delta.ECS.GeneratedForEachRuntime.GetGeneratedPrimaryComponentIds<{comparerType}>(in sourceQuery, static world => new global::Delta.ECS.ComponentId[] {{ {primaryIds} }})";
        string contextField = signature.HasContext ? $"private {signature.ContextType} _context;" : string.Empty;
        string contextConstructorParameter = signature.HasContext
            ? ", " + SignatureProjection.ContextParameter(signature.ContextMode, signature.ContextType!, "context")
            : string.Empty;
        string contextAssignment = signature.HasContext ? "_context = context;" : string.Empty;
        string contextCallParameter = signature.HasContext
            ? ", " + SignatureProjection.ContextParameter(signature.ContextMode, signature.ContextType!, "context")
            : string.Empty;
        string contextCtorArgument = signature.HasContext ? ", " + SignatureProjection.ContextArgument(signature.ContextMode, "context") : string.Empty;
        string comparerNullCheck = model.IsReferenceType
            ? "global::Delta.ECS.GeneratedForEachRuntime.ThrowIfNull(comparer, nameof(comparer));"
            : string.Empty;
        string entityLeftAndRight = GeneratorTemplates.JoinNonEmpty(new[] { leftEntity, rightEntity });
        string orderedMethods = ComponentComparerTemplateSupport.RenderOrderedMethods(
            model.ComponentTypes.Length,
            string.Empty,
            contextCallParameter,
            "ref " + comparerType + " comparer",
            primaryOrderByIds,
            primaryThenByIds,
            ids => $"new Adapter(comparer, {ids}{contextCtorArgument})");
        if (whereSources is { Count: > 0 })
        {
            orderedMethods = GeneratorTemplates.JoinNonEmpty(new[]
            {
                orderedMethods,
                string.Join("\n\n", whereSources
                    .OrderBy(static source => source.Key, StringComparer.Ordinal)
                    .Select(source => ComponentComparerTemplateSupport.RenderWhereOrderedMethods(
                        source,
                        model.ComponentTypes.Length,
                        string.Empty,
                        contextCallParameter,
                        "ref " + comparerType + " comparer",
                        primaryOrderByIds,
                        primaryThenByIds,
                        ids => $"new Adapter(comparer, {ids}{contextCtorArgument})")))
            });
        }

        string source = $$"""
            // <auto-generated />
            #nullable enable

            namespace Delta.ECS
            {
            internal static class GeneratedComponentComparerExtensions_{{hash}}
            {
                private sealed class Adapter : global::Delta.ECS.IGeneratedComponentComparer
                {
                    private {{comparerType}} _comparer;
                    {{contextField}}
                    {{idFields}}

                    internal Adapter({{comparerType}} comparer, global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds{{contextConstructorParameter}})
                    {
            {{GeneratorTemplates.Indent(comparerNullCheck, "            ")}}
                        _comparer = comparer;
            {{GeneratorTemplates.Indent(contextAssignment, "            ")}}
                        global::Delta.ECS.GeneratedForEachRuntime.ValidateComponentIdCount(componentIds, {{model.ComponentTypes.Length}});
            {{GeneratorTemplates.Indent(idAssignments, "            ")}}
                    }

                    public void Validate(global::Delta.ECS.World world, in global::Delta.ECS.Query query)
                    {
            {{GeneratorTemplates.Indent(validation, "            ")}}
                    }

                    public int Compare(global::Delta.ECS.World world, global::Delta.ECS.Entity left, global::Delta.ECS.Entity right)
                    {
            {{GeneratorTemplates.Indent(leftLocals + "\n" + rightLocals, "            ")}}
            {{GeneratorTemplates.Indent(entityLeftAndRight, "            ")}}
                        return _comparer.Invoke({{invokeArguments}});
                    }
                }

            {{GeneratorTemplates.Indent(orderedMethods, "    ")}}
            }
            }
            """;
        return GeneratedSourceFormatter.Format(source);
    }

}

internal static class ComponentComparerTemplateSupport
{
    internal static string RenderOrderedMethods(
        int arity,
        string genericClause,
        string contextParameter,
        string callbackParameter,
        string primaryOrderIds,
        string primaryThenIds,
        Func<string, string> createAdapter)
    {
        var methods = new List<string>();
        foreach (bool thenBy in new[] { false, true })
        {
            string methodName = thenBy ? "ThenBy" : "OrderBy";
            string queryType = thenBy ? "OrderedQuery" : "Query";
            foreach (RegistrationBindingKind registration in new[]
                {
                    RegistrationBindingKind.Primary,
                    RegistrationBindingKind.Explicit,
                    RegistrationBindingKind.Dynamic
                })
            {
                bool explicitIds = registration == RegistrationBindingKind.Explicit;
                bool dynamicIds = registration == RegistrationBindingKind.Dynamic;
                string selectors = registration switch
                {
                    RegistrationBindingKind.Explicit => GeneratorTemplates.JoinIndexed(
                        arity,
                        static index => $"global::Delta.ECS.ComponentId componentId{index}"),
                    RegistrationBindingKind.Dynamic => "global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds",
                    _ => string.Empty
                };
                string parameters = string.Join(", ", new[]
                {
                    "this global::Delta.ECS." + queryType + " query",
                    selectors,
                    contextParameter.TrimStart(',', ' '),
                    callbackParameter
                }.Where(static parameter => parameter.Length != 0));
                string ids = dynamicIds
                    ? string.Empty
                    : explicitIds
                        ? "global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds = stackalloc global::Delta.ECS.ComponentId[] { "
                            + GeneratorTemplates.JoinIndexed(arity, static index => $"componentId{index}") + " };\n"
                        : "global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds = "
                            + (thenBy ? primaryThenIds : primaryOrderIds) + ";\n";
                string sourceQuery = thenBy && registration == RegistrationBindingKind.Primary
                    ? "global::Delta.ECS.Query sourceQuery = query.SourceQuery;\n"
                    : string.Empty;
                string adapter = createAdapter("componentIds");
                string factory = thenBy
                    ? $"query.AppendGenerated({adapter})"
                    : $"global::Delta.ECS.OrderedQuery.CreateGenerated(query, {adapter})";
                string body = sourceQuery + ids + "return " + factory + ";";
                methods.Add(GeneratorTemplates.RenderBlock(
                    $"internal static global::Delta.ECS.OrderedQuery {methodName}{genericClause}({parameters})",
                    body));
            }
        }

        return string.Join("\n\n", methods);
    }

    internal static string RenderWhereOrderedMethods(
        PredicateModel source,
        int arity,
        string genericClause,
        string contextParameter,
        string callbackParameter,
        string primaryOrderIds,
        string primaryThenIds,
        Func<string, string> createAdapter)
    {
        string whereParameters = GeneratedWhereTemplates.ViewMethodTypeParameters(source);
        string whereArguments = SignatureProjection.TypeArguments(whereParameters);
        string methodTypeParameters = SignatureProjection.JoinGeneric(
            genericClause.Trim('<', '>'),
            whereParameters);
        string methodGenericClause = SignatureProjection.TypeArguments(methodTypeParameters);
        string viewType = GeneratedWhereTemplates.ViewTypeName(source) + whereArguments;
        string orderedViewType = GeneratedWhereTemplates.OrderedViewTypeName(source) + whereArguments;
        var methods = new List<string>();

        foreach (bool thenBy in new[] { false, true })
        {
            string methodName = thenBy ? "ThenBy" : "OrderBy";
            string receiver = thenBy ? orderedViewType : viewType;
            foreach (RegistrationBindingKind registration in new[]
                {
                    RegistrationBindingKind.Primary,
                    RegistrationBindingKind.Explicit,
                    RegistrationBindingKind.Dynamic
                })
            {
                bool explicitIds = registration == RegistrationBindingKind.Explicit;
                bool dynamicIds = registration == RegistrationBindingKind.Dynamic;
                string selectors = registration switch
                {
                    RegistrationBindingKind.Explicit => GeneratorTemplates.JoinIndexed(
                        arity,
                        static index => $"global::Delta.ECS.ComponentId componentId{index}"),
                    RegistrationBindingKind.Dynamic => "global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds",
                    _ => string.Empty
                };
                string parameters = string.Join(", ", new[]
                {
                    "this " + receiver + " query",
                    selectors,
                    contextParameter.TrimStart(',', ' '),
                    callbackParameter
                }.Where(static parameter => parameter.Length != 0));
                string sourceQuery = thenBy
                    ? "global::Delta.ECS.Query sourceQuery = query.SourceQuery;\n"
                    : "global::Delta.ECS.Query sourceQuery = query.Query;\n";
                string ids = dynamicIds
                    ? string.Empty
                    : explicitIds
                        ? "global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds = stackalloc global::Delta.ECS.ComponentId[] { "
                            + GeneratorTemplates.JoinIndexed(arity, static index => $"componentId{index}") + " };\n"
                        : "global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds = "
                            + (thenBy ? primaryThenIds : primaryOrderIds).Replace("in query", "in sourceQuery") + ";\n";
                string adapter = createAdapter("componentIds");
                string orderedQuery = thenBy
                    ? $"query.Ordering.AppendGenerated({adapter})"
                    : $"global::Delta.ECS.OrderedQuery.CreateGenerated(sourceQuery, {adapter})";
                string sourceView = thenBy ? "query.Source" : "query";
                string body = sourceQuery + ids
                    + $"return new {orderedViewType}({sourceView}, {orderedQuery});";
                methods.Add(GeneratorTemplates.RenderBlock(
                    $"internal static {orderedViewType} {methodName}{methodGenericClause}({parameters})",
                    body));
            }
        }

        return string.Join("\n\n", methods);
    }

    internal static string Arguments(
        bool hasContext,
        ContextModeKind contextMode,
        bool hasEntity,
        int arity,
        string contextName,
        Func<int, string> left,
        Func<int, string> right)
    {
        var arguments = new List<string>();
        if (hasContext)
        {
            arguments.Add(SignatureProjection.ContextArgument(contextMode, contextName));
        }

        if (hasEntity)
        {
            arguments.Add("leftEntity");
        }

        arguments.AddRange(Enumerable.Range(0, arity).Select(left));
        if (hasEntity)
        {
            arguments.Add("rightEntity");
        }

        arguments.AddRange(Enumerable.Range(0, arity).Select(right));
        return string.Join(", ", arguments);
    }
}
