namespace Delta.ECS.Generators;

internal static class ComponentComparerDelegateTemplates
{
    internal static string Render(ComponentComparerDelegateModel model)
    {
        string genericNames = GenericParameterNames(model);
        string genericArguments = GenericArguments(genericNames);
        string delegateName = "Compare" + genericArguments;
        string[] genericTypes = Enumerable.Range(0, model.ComponentTypes.Length)
            .Select(index => "T" + (index + 1)).ToArray();
        string delegateParameters = CallbackParameters(model, genericTypes, DefaultParameterNames(model));
        string invokeParameters = CallbackParameters(model, genericTypes, DefaultParameterNames(model));
        string invokeArguments = ComponentComparerTemplateSupport.Arguments(
            model.HasContext,
            model.ContextMode,
            model.HasEntity,
            model.ComponentTypes.Length,
            "_context",
            index => ComponentArgument(model, index, "left" + index),
            index => ComponentArgument(model, model.ComponentTypes.Length + index, "right" + index));
        string idFields = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"private readonly global::Delta.ECS.ComponentId _componentId{index};", "\n");
        string idAssignments = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"_componentId{index} = componentIds[{index}];", "\n");
        string validation = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"world.ValidateGeneratedOrderedQueryKey<{genericTypes[index]}>(in query, _componentId{index});", "\n");
        string leftRows = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"ref readonly {genericTypes[index]} left{index} = ref world.GetGeneratedOrderedQueryKey<{genericTypes[index]}>(left, _componentId{index});", "\n");
        string rightRows = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"ref readonly {genericTypes[index]} right{index} = ref world.GetGeneratedOrderedQueryKey<{genericTypes[index]}>(right, _componentId{index});", "\n");
        string compareRows = leftRows + "\n" + rightRows;
        string contextField = model.HasContext ? $"private {model.ContextType} _context;" : string.Empty;
        string contextParameter = model.HasContext
            ? ", " + SignatureProjection.ContextParameter(model.ContextMode, model.ContextType!, "context")
            : string.Empty;
        string contextArgument = model.HasContext
            ? ", " + SignatureProjection.ContextArgument(model.ContextMode, "context")
            : string.Empty;
        string callbackField = "private readonly " + delegateName + " _callback;";
        string callbackCall = "_callback(" + invokeArguments.Replace("_context", "context") + ")";
        string source = $$"""
            // <auto-generated />
            #nullable enable

            namespace Delta.ECS
            {
            internal static class GeneratedComponentComparerDelegateExtensions_{{model.Hash}}
            {
                internal delegate int {{delegateName}}({{delegateParameters}});

                internal abstract class AdapterBase<{{genericNames}}> : global::Delta.ECS.IGeneratedComponentComparer
                {
                    {{idFields}}
                    {{contextField}}

                    protected AdapterBase(global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds{{contextParameter}})
                    {
                        global::Delta.ECS.GeneratedForEachRuntime.ValidateComponentIdCount(componentIds, {{model.ComponentTypes.Length}});
            {{GeneratorTemplates.Indent(idAssignments, "            ")}}
                        {{(model.HasContext ? "_context = context;" : string.Empty)}}
                    }

                    public void Validate(global::Delta.ECS.World world, in global::Delta.ECS.Query query)
                    {
            {{GeneratorTemplates.Indent(validation, "            ")}}
                    }

                    public int Compare(global::Delta.ECS.World world, global::Delta.ECS.Entity left, global::Delta.ECS.Entity right)
                    {
            {{GeneratorTemplates.Indent(compareRows, "            ")}}
                        {{(model.HasEntity ? "global::Delta.ECS.Entity leftEntity = left;\n            global::Delta.ECS.Entity rightEntity = right;" : string.Empty)}}
                        return Invoke({{invokeArguments}});
                    }

                    protected abstract int Invoke({{invokeParameters}});
                }

                private sealed class DelegateAdapter<{{genericNames}}> : AdapterBase<{{genericNames}}>
                {
                    {{callbackField}}

                    internal DelegateAdapter(
                        global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds{{contextParameter}},
                        {{delegateName}} callback)
                        : base(componentIds{{contextArgument}})
                    {
                        global::Delta.ECS.GeneratedForEachRuntime.ThrowIfNull(callback, nameof(callback));
                        _callback = callback;
                    }

                    protected override int Invoke({{invokeParameters}})
                        => {{callbackCall}};
                }

            {{RenderExtensions(model, delegateName, genericNames)}}
            }
            }
            """;

        return GeneratedSourceFormatter.Format(source);
    }

    internal static string RenderInterceptor(ComponentComparerDelegateSite site)
    {
        ComponentComparerDelegateModel model = site.Model;
        string genericNames = string.Join(", ", site.ComponentTypes);
        string genericArguments = GenericArguments(genericNames);
        string extensionClass = "global::Delta.ECS.GeneratedComponentComparerDelegateExtensions_" + model.Hash;
        string delegateType = extensionClass + ".Compare" + genericArguments;
        string adapterType = extensionClass + ".AdapterBase<" + genericNames + ">";
        string contextParameter = model.HasContext
            ? ", " + SignatureProjection.ContextParameter(model.ContextMode, model.ContextType!, "context")
            : string.Empty;
        string contextArgument = model.HasContext
            ? ", " + SignatureProjection.ContextArgument(model.ContextMode, "context")
            : string.Empty;
        string selectorParameters = SelectorParameters(site.RegistrationBinding, model.ComponentTypes.Length);
        string selectorNames = SelectorArgumentNames(site.RegistrationBinding, model.ComponentTypes.Length);
        string queryType = site.MethodName == "OrderBy" ? "global::Delta.ECS.Query" : "global::Delta.ECS.OrderedQuery";
        string sourceQuery = site.MethodName == "OrderBy" ? "query" : "sourceQuery";
        string sourceQueryDeclaration = site.MethodName == "OrderBy"
            ? string.Empty
            : "global::Delta.ECS.Query sourceQuery = query.SourceQuery;";
        string idsExpression = site.RegistrationBinding switch
        {
            RegistrationBindingKind.Primary => $"global::Delta.ECS.GeneratedForEachRuntime.GetGeneratedPrimaryComponentIds<{delegateType}>(in {sourceQuery}, static world => new global::Delta.ECS.ComponentId[] {{ {PrimaryIds(site.ComponentTypes, "world")} }})",
            RegistrationBindingKind.Explicit => $"stackalloc global::Delta.ECS.ComponentId[] {{ {selectorNames} }}",
            _ => "componentIds"
        };
        string callbackType = $"{delegateType} _";
        string genericClause = string.Empty;
        string directParameters = CallbackParameters(model, site.ComponentTypes, site.ParameterNames);
        string callbackBody = site.CallbackBody;
        string directInvoke = "protected override int Invoke(" + directParameters + ")";
        string usings = string.Join("\n", site.Usings
            .Where(static value => value.Trim() is not ("using Delta.ECS;" or "using global::Delta.ECS;"))
            .Concat(string.IsNullOrEmpty(site.NamespaceName) ? Array.Empty<string>() : new[] { "using global::" + site.NamespaceName + ";" })
            .Distinct(StringComparer.Ordinal));
        string directAdapter = "new DirectAdapter(resolvedComponentIds" + contextArgument + ")";
        string returnExpression = site.MethodName == "OrderBy"
            ? $"global::Delta.ECS.OrderedQuery.CreateGenerated(query, {directAdapter})"
            : $"query.AppendGenerated({directAdapter})";
        string invocationParameterList = string.Join(", ", new[]
        {
            "this " + queryType + " query",
            selectorParameters,
            contextParameter.Length == 0 ? string.Empty : contextParameter.Substring(2),
            callbackType,
        }.Where(static value => value.Length != 0));

        string source = $$"""
            // <auto-generated />
            #nullable enable
            {{usings}}

            namespace Delta.ECS.Generated
            {
                file static class ComponentComparerInterceptor_{{site.Id}}
                {
                    private sealed class DirectAdapter : {{adapterType}}
                    {
                        internal DirectAdapter(global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds{{contextParameter}})
                            : base(componentIds{{contextArgument}}) { }

                        {{directInvoke}}
                        {
            {{GeneratorTemplates.Indent(callbackBody, "                ")}}
                        }
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    {{site.InterceptionAttribute}}
                    internal static global::Delta.ECS.OrderedQuery Intercept{{genericClause}}({{invocationParameterList}})
                    {
                        {{sourceQueryDeclaration}}
                        global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> resolvedComponentIds = {{idsExpression}};
                        return {{returnExpression}};
                    }
                }

            {{GeneratorTemplates.InterceptorSourceFooter}}
            """;

        return GeneratedSourceFormatter.Format(source);
    }

    private static string RenderExtensions(
        ComponentComparerDelegateModel model,
        string delegateName,
        string genericNames)
    {
        string genericClause = GenericArguments(genericNames);
        string contextParameter = model.HasContext
            ? ", " + SignatureProjection.ContextParameter(model.ContextMode, model.ContextType!, "context")
            : string.Empty;
        string contextArgument = model.HasContext
            ? ", " + SignatureProjection.ContextArgument(model.ContextMode, "context")
            : string.Empty;
        string adapter = "DelegateAdapter<" + genericNames + ">";
        string primaryOrder = PrimaryIds(delegateName, model.ComponentTypes, "query");
        string primaryThen = PrimaryIds(delegateName, model.ComponentTypes, "sourceQuery");

        return ComponentComparerTemplateSupport.RenderOrderedMethods(
            model.ComponentTypes.Length,
            genericClause,
            contextParameter,
            delegateName + " callback",
            primaryOrder,
            primaryThen,
            ids => $"new {adapter}({ids}{contextArgument}, callback)");
    }

    private static string PrimaryIds(string delegateName, string[] componentTypes, string query)
    {
        string registrations = PrimaryIds(componentTypes, "world");
        return $"global::Delta.ECS.GeneratedForEachRuntime.GetGeneratedPrimaryComponentIds<{delegateName}>(in {query}, static world => new global::Delta.ECS.ComponentId[] {{ {registrations} }})";
    }

    private static string SelectorParameters(RegistrationBindingKind kind, int arity)
        => SelectorArguments(kind, arity, parameters: true);

    private static string SelectorArgumentNames(RegistrationBindingKind kind, int arity)
        => SelectorArguments(kind, arity, parameters: false);

    private static string SelectorArguments(RegistrationBindingKind kind, int arity, bool parameters)
        => kind switch
        {
            RegistrationBindingKind.Explicit => GeneratorTemplates.JoinIndexed(
                arity,
                index => parameters
                    ? $"global::Delta.ECS.ComponentId componentId{index}"
                    : $"componentId{index}"),
            RegistrationBindingKind.Dynamic => parameters
                ? "global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds"
                : "componentIds",
            _ => string.Empty
        };

    private static string PrimaryIds(string[] componentTypes, string world)
        => string.Join(", ", componentTypes
            .Select(type => $"{world}.Layouts.GetPrimary(typeof({type}))"));

    private static string CallbackParameters(ComponentComparerDelegateModel model, string[] genericTypes, string[] parameterNames)
    {
        var parameters = new List<string>();
        int nameIndex = 0;
        if (model.HasContext)
        {
            parameters.Add(SignatureProjection.ContextParameter(model.ContextMode, model.ContextType!, parameterNames[nameIndex++]));
        }

        if (model.HasEntity)
        {
            parameters.Add("global::Delta.ECS.Entity " + parameterNames[nameIndex++]);
        }

        for (int index = 0; index < model.ComponentTypes.Length; index++)
        {
            parameters.Add(ComponentParameter(model, index, genericTypes[index], parameterNames[nameIndex++]));
        }

        if (model.HasEntity)
        {
            parameters.Add("global::Delta.ECS.Entity " + parameterNames[nameIndex++]);
        }

        for (int index = 0; index < model.ComponentTypes.Length; index++)
        {
            parameters.Add(ComponentParameter(model, model.ComponentTypes.Length + index, genericTypes[index], parameterNames[nameIndex++]));
        }

        return string.Join(", ", parameters);
    }

    private static string ComponentParameter(ComponentComparerDelegateModel model, int index, string type, string name)
        => SignatureProjection.ComponentParameter(model.ComponentModes[index], type, name);

    private static string[] DefaultParameterNames(ComponentComparerDelegateModel model)
    {
        var names = new List<string>();
        if (model.HasContext)
        {
            names.Add("context");
        }

        if (model.HasEntity)
        {
            names.Add("leftEntity");
        }

        names.AddRange(Enumerable.Range(0, model.ComponentTypes.Length).Select(index => "left" + index));
        if (model.HasEntity)
        {
            names.Add("rightEntity");
        }

        names.AddRange(Enumerable.Range(0, model.ComponentTypes.Length).Select(index => "right" + index));
        return names.ToArray();
    }

    private static string ComponentArgument(ComponentComparerDelegateModel model, int index, string name)
        => SignatureProjection.ComponentArgument(model.ComponentModes[index], name);

    private static string GenericParameterNames(ComponentComparerDelegateModel model)
        => model.ContextIsGeneric
            ? GenericNames(model.ComponentTypes.Length) + ", TContext"
            : GenericNames(model.ComponentTypes.Length);

    private static string GenericNames(int arity)
        => string.Join(", ", Enumerable.Range(0, arity).Select(static index => "T" + (index + 1)));

    private static string GenericArguments(string names)
        => "<" + names + ">";

}
