namespace Delta.ECS.Generators;

internal static class ComponentComparerTemplates
{
    internal static string Render(ComponentComparerModel model, IReadOnlyList<PredicateModel>? whereSources = null)
    {
        string hash = GeneratorSupport.StableName(model.Key);
        string comparerType = model.FunctorType;
        ComponentComparerSignature signature = model.Signature!;
        string idFields = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"private readonly global::Delta.ECS.ComponentId _componentId{index};", "\n");
        string idAssignments = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"_componentId{index} = componentIds[{index}];", "\n");
        string validation = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"world.ValidateGeneratedOrderedQueryKey<{model.ComponentTypes[index]}>(in query, _componentId{index});", "\n");
        string leftLocals = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"ref readonly {model.ComponentTypes[index]} left{index} = ref world.GetGeneratedOrderedQueryKey<{model.ComponentTypes[index]}>(left, _componentId{index});", "\n");
        string rightLocals = GeneratorTemplates.JoinIndexed(model.ComponentTypes.Length,
            index => $"ref readonly {model.ComponentTypes[index]} right{index} = ref world.GetGeneratedOrderedQueryKey<{model.ComponentTypes[index]}>(right, _componentId{index});", "\n");
        string leftEntity = signature.HasEntity ? "global::Delta.ECS.Entity leftEntity = left;" : string.Empty;
        string rightEntity = signature.HasEntity ? "global::Delta.ECS.Entity rightEntity = right;" : string.Empty;
        string invokeArguments = ComponentComparerTemplateSupport.Arguments(
            signature.HasContext,
            signature.ContextMode,
            signature.HasEntity,
            model.ComponentTypes.Length,
            "_context",
            static index => $"in left{index}",
            static index => $"in right{index}");
        string primaryIds = string.Join(", ", model.ComponentTypes.Select(static componentType =>
            $"world.Layouts.GetPrimary(typeof({componentType}))"));
        string contextField = signature.HasContext ? $"private {signature.ContextType} _context;" : string.Empty;
        string contextConstructorParameter = signature.HasContext
            ? ", " + SignatureProjection.ContextParameter(signature.ContextMode, signature.ContextType!, "context")
            : string.Empty;
        string contextAssignment = signature.HasContext ? "_context = context;" : string.Empty;
        string contextCallParameter = signature.HasContext
            ? ", " + SignatureProjection.ContextParameter(signature.ContextMode, signature.ContextType!, "context")
            : string.Empty;
        string contextCtorArgument = signature.HasContext ? ", " + SignatureProjection.ContextArgument(signature.ContextMode, "context") : string.Empty;
        string comparerNullCheck = model.IsReferenceType
            ? "global::Delta.ECS.GeneratedForEachRuntime.ThrowIfNull(comparer, nameof(comparer));"
            : string.Empty;
        string entityLeftAndRight = GeneratorTemplates.JoinNonEmpty(new[] { leftEntity, rightEntity });
        string orderedMethods = ComponentComparerTemplateSupport.RenderOrderedMethods(
            model.ComponentTypes.Length,
            string.Empty,
            contextCallParameter,
            "ref " + comparerType + " comparer",
            query => $"global::Delta.ECS.GeneratedForEachRuntime.GetGeneratedPrimaryComponentIds<{comparerType}>(in {query}, static world => new global::Delta.ECS.ComponentId[] {{ {primaryIds} }})",
            ids => $"new Adapter(comparer, {ids}{contextCtorArgument})",
            whereSources);

        string source = $$"""
            // <auto-generated />
            #nullable enable

            namespace Delta.ECS
            {
            internal static class GeneratedComponentComparerExtensions_{{hash}}
            {
                private sealed class Adapter : global::Delta.ECS.IGeneratedComponentComparer
                {
                    private {{comparerType}} _comparer;
                    {{contextField}}
                    {{idFields}}

                    internal Adapter({{comparerType}} comparer, global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds{{contextConstructorParameter}})
                    {
            {{GeneratorTemplates.Indent(comparerNullCheck, "            ")}}
                        _comparer = comparer;
            {{GeneratorTemplates.Indent(contextAssignment, "            ")}}
                        global::Delta.ECS.GeneratedForEachRuntime.ValidateComponentIdCount(componentIds, {{model.ComponentTypes.Length}});
            {{GeneratorTemplates.Indent(idAssignments, "            ")}}
                    }

                    public void Validate(global::Delta.ECS.World world, in global::Delta.ECS.Query query)
                    {
            {{GeneratorTemplates.Indent(validation, "            ")}}
                    }

                    public int Compare(global::Delta.ECS.World world, global::Delta.ECS.Entity left, global::Delta.ECS.Entity right)
                    {
            {{GeneratorTemplates.Indent(leftLocals + "\n" + rightLocals, "            ")}}
            {{GeneratorTemplates.Indent(entityLeftAndRight, "            ")}}
                        return _comparer.Invoke({{invokeArguments}});
                    }
                }

            {{GeneratorTemplates.Indent(orderedMethods, "    ")}}
            }
            }
            """;
        return GeneratedSourceFormatter.Format(source);
    }

}

internal static class ComponentComparerTemplateSupport
{
    internal static string RenderOrderedMethods(
        int arity,
        string genericClause,
        string contextParameter,
        string callbackParameter,
        Func<string, string> getPrimaryIds,
        Func<string, string> createAdapter,
        IReadOnlyList<PredicateModel>? whereSources = null)
    {
        IEnumerable<PredicateModel?> sources = new PredicateModel?[] { null }
            .Concat(whereSources ?? Array.Empty<PredicateModel>());
        return string.Join("\n\n", sources.SelectMany(source => RenderOrderedMethodSet(
            source,
            arity,
            genericClause,
            contextParameter,
            callbackParameter,
            getPrimaryIds,
            createAdapter)));
    }

    private static IEnumerable<string> RenderOrderedMethodSet(
        PredicateModel? source,
        int arity,
        string genericClause,
        string contextParameter,
        string callbackParameter,
        Func<string, string> getPrimaryIds,
        Func<string, string> createAdapter)
    {
        string whereTypeArguments = source is null
            ? string.Empty
            : GeneratedWhereTemplates.ViewMethodTypeArguments(source);
        string orderedViewType = OrderedReturnType(source, whereTypeArguments);
        string methodGenericClause = source is null
            ? genericClause
            : SignatureProjection.TypeArguments(SignatureProjection.JoinGeneric(
                genericClause.Trim('<', '>'),
                GeneratedWhereTemplates.ViewMethodTypeParameters(source)));

        foreach (bool thenBy in new[] { false, true })
        {
            string methodName = thenBy ? "ThenBy" : "OrderBy";
            string receiverType = OrderedReceiverType(source, thenBy, whereTypeArguments);
            foreach (RegistrationBindingKind registration in new[]
                {
                    RegistrationBindingKind.Primary,
                    RegistrationBindingKind.Explicit,
                    RegistrationBindingKind.Dynamic
                })
            {
                string selectors = registration switch
                {
                    RegistrationBindingKind.Explicit => GeneratorTemplates.JoinIndexed(
                        arity,
                        static index => $"global::Delta.ECS.ComponentId componentId{index}"),
                    RegistrationBindingKind.Dynamic => "global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds",
                    _ => string.Empty
                };
                string parameters = string.Join(", ", new[]
                {
                    "this " + receiverType + " query",
                    selectors,
                    contextParameter.TrimStart(',', ' '),
                    callbackParameter
                }.Where(static parameter => parameter.Length != 0));
                string sourceQuery = SourceQueryDeclaration(source, thenBy, registration);
                string primaryQuery = source is null && !thenBy ? "query" : "sourceQuery";
                string ids = ComponentIdsDeclaration(
                    arity,
                    registration,
                    getPrimaryIds(primaryQuery));
                string adapter = createAdapter("componentIds");
                string factory = GeneratedOrderingFactory(source, thenBy, adapter, whereTypeArguments);
                string body = sourceQuery + ids + "return " + factory + ";";
                yield return GeneratorTemplates.RenderBlock(
                    $"internal static {orderedViewType} {methodName}{methodGenericClause}({parameters})",
                    body);
            }
        }
    }

    internal static string OrderedReceiverType(PredicateModel? source, bool thenBy, string whereTypeArguments)
    {
        if (source is null)
        {
            return "global::Delta.ECS." + (thenBy ? "OrderedQuery" : "Query");
        }

        return (thenBy
            ? GeneratedWhereTemplates.OrderedViewTypeName(source)
            : GeneratedWhereTemplates.ViewTypeName(source)) + whereTypeArguments;
    }

    internal static string OrderedReturnType(PredicateModel? source, string whereTypeArguments) => source is null
            ? "global::Delta.ECS.OrderedQuery"
            : GeneratedWhereTemplates.OrderedViewTypeName(source)
                + whereTypeArguments;

    internal static string SourceQueryDeclaration(PredicateModel? source, bool thenBy, RegistrationBindingKind registration)
    {
        bool needsSourceQuery = source is null
            ? thenBy && registration == RegistrationBindingKind.Primary
            : !thenBy || registration == RegistrationBindingKind.Primary;
        if (!needsSourceQuery)
        {
            return string.Empty;
        }

        string sourceProperty = source is null || thenBy ? "SourceQuery" : "Query";
        return $"global::Delta.ECS.Query sourceQuery = query.{sourceProperty};\n";
    }

    private static string ComponentIdsDeclaration(int arity, RegistrationBindingKind registration, string primaryIds)
    {
        return registration switch
        {
            RegistrationBindingKind.Dynamic => string.Empty,
            RegistrationBindingKind.Explicit => $$"""
                global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds =
                    stackalloc global::Delta.ECS.ComponentId[]
                    {
                        {{GeneratorTemplates.JoinIndexed(arity, static index => $"componentId{index}")}}
                    };
                """,
            _ => $$"""
                global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> componentIds =
                    {{primaryIds}};
                """
        };
    }

    internal static string GeneratedOrderingFactory(
        PredicateModel? source,
        bool thenBy,
        string adapter,
        string whereTypeArguments)
    {
        if (source is null)
        {
            return thenBy
                ? $"query.AppendGenerated({adapter})"
                : $"global::Delta.ECS.OrderedQuery.CreateGenerated(query, {adapter})";
        }

        string orderedQuery = thenBy
            ? $"query.Ordering.AppendGenerated({adapter})"
            : $"global::Delta.ECS.OrderedQuery.CreateGenerated(sourceQuery, {adapter})";
        string sourceView = thenBy ? "query.Source" : "query";
        return $"new {GeneratedWhereTemplates.OrderedViewTypeName(source)}{whereTypeArguments}({sourceView}, {orderedQuery})";
    }

    internal static string Arguments(
        bool hasContext,
        ContextModeKind contextMode,
        bool hasEntity,
        int arity,
        string contextName,
        Func<int, string> left,
        Func<int, string> right)
    {
        var arguments = new List<string>();
        if (hasContext)
        {
            arguments.Add(SignatureProjection.ContextArgument(contextMode, contextName));
        }

        if (hasEntity)
        {
            arguments.Add("leftEntity");
        }

        arguments.AddRange(Enumerable.Range(0, arity).Select(left));
        if (hasEntity)
        {
            arguments.Add("rightEntity");
        }

        arguments.AddRange(Enumerable.Range(0, arity).Select(right));
        return string.Join(", ", arguments);
    }
}
