using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace Delta.ECS.Generators;

/// <summary>Raw-string templates for validated demand-driven iteration shapes.</summary>
internal static class DemandDrivenForEachTemplates
{
    private const string InterceptorSourceHeader = """
        // <auto-generated />
        #nullable enable
        #pragma warning disable CS0436 // Demand-generated callback contracts can also arrive through a referenced consumer assembly.

        """;
    private const string InterceptorSourceFooter = """
        }

        }

        namespace System.Runtime.CompilerServices
        {

        file sealed class InterceptsLocationAttribute : global::System.Attribute
        {
            internal InterceptsLocationAttribute(int version, string data) { }
        }
        }
        """;

    internal static string Render(IterationRenderModel model)
    {
        IterationModel shape = model.Shape;
        RenderModel? contracts = model.RenderContracts && !shape.IsFunctor && shape.ComponentModels.Length > 0
            ? GeneratorTemplates.RenderMember(shape.Api, RenderContracts(model))
            : null;
        RenderModel? stampWriter = shape.ComponentModels.Count(static component => component.IsWrite) > 1
            ? GeneratorTemplates.RenderMember(shape.Api, RenderArchetypeStampWriter(shape))
            : null;
        RenderModel? invoker = shape.Parallel || shape.HasEntityTarget
            ? GeneratorTemplates.InvokerTemplate(new InvokerModel(shape.Api, RenderParallelInvoker(shape)))
            : null;
        RenderModel extension = GeneratorTemplates.ExtensionTemplate(
            shape.Api,
            $$"""DemandForEachExtensions_{{GeneratorSupport.StableName(shape.Key)}}""",
            shape.IsFunctor,
            RenderExtensionsBody(model));
        RenderModel[] members = new[] { contracts, stampWriter, invoker, extension }
            .Where(static member => member is not null)
            .Cast<RenderModel>()
            .ToArray();
        return GeneratorTemplates.FileTemplate(new GeneratedFileModel(
            "Delta.ECS",
            ImmutableArray.Create("using System;"),
            members.ToImmutableArray()));
    }

    private static string RenderContracts(IterationRenderModel model)
    {
        IterationModel shape = model.Shape;
        string generic = GeneratorSupport.GenericTypes(shape.Components.Length);
        string parameters = RefParameters(shape.ComponentModels);
        string suffix = IsAllWrite(shape.ComponentModels) ? string.Empty : "_" + shape.Pattern;
        IEnumerable<string> contracts = new[]
        {
            AppendContract("ForEachAction" + suffix, generic, parameters),
            AppendContract("ForEachEntityAction" + suffix, generic, JoinParameters("Entity entity", parameters)),
        }.Concat(model.SupportedContextModes
            .SelectMany(mode =>
            {
                string context = ContextParameter(mode, "TContext", "context");
                string contextGeneric = JoinGeneric("TContext", generic);
                string modeSuffix = ContextDelegateSuffix(mode);
                return new[]
                {
                    AppendContract("ForEachContextAction" + modeSuffix + suffix, contextGeneric, JoinParameters(context, parameters)),
                    AppendContract(
                        "ForEachContextEntityAction" + modeSuffix + suffix,
                        contextGeneric,
                        JoinParameters(JoinParameters(context, "Entity entity"), parameters)),
                };
            }));
        return string.Join("\n", contracts) + "\n";
    }

    private static string AppendContract(string name, string generic, string parameters)
        => $$"""public delegate void {{TypeWithGenericArgs(name, generic)}}({{parameters}});""";

    private static string RenderArchetypeStampWriter(IterationModel shape)
    {
        string name = ArchetypeStampWriterName(shape);
        int[] writes = WriteIndices(shape.ComponentModels).ToArray();
        string fields = GeneratorTemplates.JoinNonEmpty(writes.Select(index => $$"""private readonly int _access{{index}};"""));
        string constructorParameters = string.Join(", ", writes.Select(index => $$"""int access{{index}}"""));
        string assignments = GeneratorTemplates.JoinNonEmpty(writes.Select(index => $$"""_access{{index}} = access{{index}};"""));
        string increments = GeneratorTemplates.JoinNonEmpty(writes.Select(index =>
            $$"""GeneratedForEachRuntime.IncrementArchetypeStamp(stamps, _access{{index}});"""));
        return $$"""
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            internal struct {{name}} : IGeneratedArchetypeStampWriter
            {
            {{fields}}

                internal {{name}}({{constructorParameters}})
                {
            {{assignments}}
                }

                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                void IGeneratedArchetypeStampWriter.Write(Stamp[] stamps)
                {
            {{increments}}
                }
            }
            """;
    }

    private static string RenderParallelInvoker(IterationModel shape)
    {
        string generic = ComponentGenericTypes(shape);
        string stateGeneric = StateGeneric(shape, generic);
        string name = ParallelInvokerName(shape);
        string actionType = ActionType(shape);
        string rows = shape.IsStamp
            ? string.Empty
            : GeneratorTemplates.JoinNonEmpty(Enumerable.Range(0, shape.ComponentModels.Length).Select(index =>
            {
                string componentType = ComponentType(shape, index);
                return $$"""ref {{componentType}} row{{index}} = ref slots.GetGeneratedReadReference<{{componentType}}>(_access{{index}});""";
            }));
        string components = GeneratorTemplates.JoinNonEmpty(Enumerable.Range(0, shape.ComponentModels.Length).Select(index => shape.IsStamp
            ? $$"""Stamp component{{index}} = slots.GetGeneratedStamp(_access{{index}}, index);"""
            : $$"""{{(shape.ComponentModels[index].IsWrite ? "ref " : "ref readonly ")}}{{ComponentType(shape, index)}} component{{index}} = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref row{{index}}, index);"""));
        return $$"""
            internal struct {{name}}{{stateGeneric}} : IGeneratedParallelInvoker
            {
            {{AppendInvokerFields(shape, actionType)}}
            {{AppendInvokerConstructor(shape, name, actionType, parallel: true)}}

                public bool RequiresSingleThread => {{(shape.ContextMode == ContextModeKind.Ref ? "true" : "false")}};

                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                public void Invoke(ref GeneratedQuerySlots slots)
                {
            {{rows}}
                    int count = slots.Count;
                    for (int index = 0; index < count; index++)
                    {
            {{components}}
                        {{AppendClosedInvocation(shape, "_action", "_functor", "_context", "component", "slots.EntityAt(index)")}};
                    }
                }
            {{AppendInvokerProperties(shape)}}
            }
            """;
    }

    private static string AppendInvokerFields(IterationModel shape, string actionType)
    {
        string context = shape.HasContext
            ? $$"""private {{ContextType(shape)}} _context;"""
            : string.Empty;
        string callback = shape.IsFunctor
            ? $$"""private {{shape.FunctorType}} _functor;"""
            : $$"""private readonly {{actionType}} _action;""";
        return GeneratorTemplates.JoinNonEmpty(new[] { context, callback }
            .Concat(Enumerable.Range(0, shape.ComponentModels.Length)
                .Select(index => $$"""private readonly int _access{{index}};""")));
    }

    private static string AppendInvokerConstructor(
        IterationModel shape,
        string name,
        string actionType,
        bool parallel)
    {
        string[] parameters = new[]
            {
                shape.HasContext ? $$"""{{ContextType(shape)}} context""" : string.Empty,
                shape.IsFunctor ? $$"""{{shape.FunctorType}} functor""" : $$"""{{actionType}} action""",
                parallel ? AccessTokenParameters(shape.ComponentModels) : AccessParameters(shape.ComponentModels)
            }
            .Where(static parameter => parameter.Length != 0)
            .ToArray();
        string[] assignments = new[]
            {
                shape.HasContext ? "_context = context;" : string.Empty,
                shape.IsFunctor ? "_functor = functor;" : "_action = action;"
            }
            .Concat(Enumerable.Range(0, shape.ComponentModels.Length).Select(index =>
        {
            string value = parallel
                ? $$"""GeneratedForEachRuntime.Get{{(shape.ComponentModels[index].IsWrite ? "Write" : "Read")}}QueryComponentIndex(access{{index}})"""
                : $$"""access{{index}}""";
            return $$"""_access{{index}} = {{value}};""";
        }))
            .Where(static assignment => assignment.Length != 0)
            .ToArray();
        return $$"""
                internal {{ConstructorName(name)}}({{string.Join(", ", parameters)}})
                {
            {{GeneratorTemplates.JoinNonEmpty(assignments)}}
                }
            """;
    }

    private static string AppendInvokerProperties(IterationModel shape)
        => GeneratorTemplates.JoinNonEmpty(new[]
        {
            shape.HasContext ? $$"""internal {{ContextType(shape)}} Context => _context;""" : string.Empty,
            shape.IsFunctor ? $$"""internal {{shape.FunctorType}} Functor => _functor;""" : string.Empty
        });

    private static string RenderClosedParallelMethod(
        IterationModel shape,
        string methodName,
        string ids,
        string componentParameters)
    {
        string generic = ComponentGenericTypes(shape);
        string genericPrefix = StateGeneric(shape, generic);
        string contextParameter = shape.HasContext
            ? $$""", {{ContextParameter(shape.ContextMode, ContextType(shape), "context")}}"""
            : string.Empty;
        string callbackParameter = shape.IsFunctor
            ? $$""", ref {{shape.FunctorType}} functor"""
            : $$""", {{ActionType(shape)}} action""";
        string invokerType = $$"""{{ParallelInvokerName(shape)}}{{StateGeneric(shape, generic)}}""";
        string target = shape.HasEntityTarget
            ? ", global::System.ReadOnlySpan<Entity> entities, in Query query"
            : ", in Query query";
        string arguments = string.Join(", ", new[]
        {
            shape.HasContext ? "context" : null,
            shape.IsFunctor ? "functor" : "action",
            AccessArguments(shape.ComponentModels),
        }.Where(static value => !string.IsNullOrEmpty(value)));
        string execute = shape.HasEntityTarget
            ? "GeneratedForEachRuntime.ExecuteEntityListParallel(world, in query, entities, ref invoker, "
            : "GeneratedForEachRuntime.ExecuteParallelDense(world, in query, ref invoker, ";
        string body = $$"""
                {{GeneratorTemplates.Indent(AccessSetup(shape, ids, closed: true, prepared: true), "    ")}}
                var invoker = new {{invokerType}}({{arguments}});
                {{execute}}{{AppendParallelWriteIndices(shape)}}, workerCount);
                {{(shape.HasContext && shape.ContextMode == ContextModeKind.Ref ? "context = invoker.Context;" : string.Empty)}}
                {{(shape.IsFunctor ? "functor = invoker.Functor;" : string.Empty)}}
            """;
        string signature = $$"""private static void {{methodName}}{{genericPrefix}}(World world{{target}}{{componentParameters}}{{contextParameter}}{{callbackParameter}}, int workerCount)""";
        return GeneratorTemplates.Indent(GeneratorTemplates.RenderBlock(
            $$"""
                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                {{signature}}
                """.Trim(),
            body), "    ");
    }

    private static string AppendParallelWriteIndices(IterationModel shape)
    {
        if (!shape.ComponentModels.Any(static component => component.IsWrite))
        {
            return "global::System.ReadOnlySpan<int>.Empty";
        }

        string indices = string.Join(", ", WriteIndices(shape.ComponentModels)
            .Select(index => $$"""global::Delta.ECS.GeneratedForEachRuntime.GetWriteQueryComponentIndex(access{{index}})"""));
        return $$"""stackalloc int[] { {{indices}} }""";
    }

    private static int StableProfileMethodId(string methodName)
    {
        unchecked
        {
            uint hash = 2_166_136_261;
            foreach (char character in methodName)
            {
                hash ^= character;
                hash *= 16_777_619;
            }

            return (int)(hash & 0x7FFF_FFFF);
        }
    }

    private static string AppendClosedInvocation(
        IterationModel shape,
        string actionName,
        string functorName,
        string contextName,
        string componentPrefix,
        string entityExpression)
    {
        var invocationArguments = new List<string>();
        if (shape.HasContext)
        {
            invocationArguments.Add(ContextInvocation(shape.ContextMode, contextName));
        }

        if (shape.HasEntity)
        {
            invocationArguments.Add(entityExpression);
        }

        invocationArguments.AddRange(Enumerable.Range(0, shape.ComponentModels.Length)
            .Select(index => shape.ComponentModels[index].InvocationModifier + componentPrefix + index));
        string invocation = shape.IsFunctor ? $$"""{{functorName}}.Invoke""" : actionName;
        return $$"""{{invocation}}({{string.Join(", ", invocationArguments)}})""";
    }

    private static string RenderExtensionsBody(IterationRenderModel model)
    {
        IterationModel shape = model.Shape;
        string className = "DemandForEachExtensions_" + GeneratorSupport.StableName(shape.Key);
        string generic = shape.GenericSelectors ? GeneratorSupport.GenericTypes(shape.Components.Length) : string.Empty;
        string ids = shape.ExplicitIds ? ComponentParameters(shape.Components.Length) : string.Empty;
        string closedIdArguments = shape.ExplicitIds ? ClosedComponentNames(shape.Components.Length) : string.Empty;
        string accessArguments = AccessArguments(shape.ComponentModels);
        string name = InvokerName(shape);
        string stateGeneric = StateGeneric(shape, generic);
        string callback = ActionType(shape);
        string componentParameters = shape.ExplicitIds ? ", " + ClosedComponentParameters(shape.Components.Length) : string.Empty;
        string prefix = shape.HasEntityTarget
            ? "this World world, global::System.ReadOnlySpan<Entity> entities"
            : "this World world";
        string query = shape.HasQuery ? ", in Query query" : string.Empty;
        string contextParameter = shape.HasContext
            ? ", " + ContextParameter(shape.ContextMode, ContextType(shape), "context")
            : string.Empty;
        string closedMethodName = "ExecuteClosed_" + GeneratorSupport.StableName(shape.Key);
        string closed = shape.Parallel
            ? RenderClosedParallelMethod(shape, closedMethodName, closedIdArguments, componentParameters)
            : RenderClosedDenseMethod(shape, closedMethodName, closedIdArguments, componentParameters);
        string extension = RenderExtensionMethod(
            shape,
            prefix,
            query,
            contextParameter,
            ids,
            callback,
            name,
            stateGeneric,
            stateGeneric,
            string.Empty,
            accessArguments,
            className,
            model.Profiling,
            closedMethodName);
        return closed + "\n" + extension;
    }

    internal static string RenderInterceptorSource(
        IterationModel shape,
        InterceptionSite site)
    {
        string usings = string.Join(
            "\n",
            (!site.Usings.Any(static value => value.Trim() is "using Delta.ECS;" or "using global::Delta.ECS;")
                ? new[] { "using global::Delta.ECS;" }
                : Array.Empty<string>())
            .Concat(site.Usings.OrderBy(static value => value, StringComparer.Ordinal)));
        string execution = shape.HasEntityTarget || shape.Parallel
            ? GeneratorTemplates.JoinNonEmpty(new[]
            {
                RenderInterceptedParallelInvoker(shape, site),
                RenderInterceptedParallelClosedMethod(shape, site)
            })
            : RenderInterceptedClosedMethod(shape, site);
        string source = GeneratorTemplates.JoinNonEmpty(new[]
        {
            usings,
            $$"""
            namespace Delta.ECS.Generated
            {

            file static class ForEachInterceptor_{{site.Id}}
            {
            """,
            CanInlineInterceptedLambda(site) ? string.Empty : RenderInterceptedCallback(site),
            execution,
            RenderInterceptor(shape, site)
        });
        return GeneratorTemplates.InterceptorTemplate(
            InterceptorSourceHeader,
            source,
            InterceptorSourceFooter);
    }

    private static string RenderInterceptedCallback(InterceptionSite site)
    {
        IterationModel shape = site.IterationModel;
        string callbackName = "InvokeInterceptedCallback_" + site.Id;
        string[] parameters = InterceptedParameterNames(site);
        int parameterIndex = 0;
        var declarations = new List<string>();
        if (shape.HasContext)
        {
            declarations.Add(ContextParameter(shape.ContextMode, InterceptedContextType(shape), parameters[parameterIndex++]));
        }
        if (shape.HasEntity)
        {
            declarations.Add("global::Delta.ECS.Entity " + parameters[parameterIndex++]);
        }
        declarations.AddRange(Enumerable.Range(0, shape.ComponentModels.Length)
            .Select(index => shape.ComponentModels[index].ParameterModifier
                + CallbackComponentType(shape, index) + " " + parameters[parameterIndex + index]));
        string body = site.LambdaBody is not null
            ? AppendInterceptedLambdaBody(site, "    ")
            : AppendCallbackInvocation(shape, site.MethodGroupTarget!, parameters, "    ");
        string declaration = $$"""
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            private static void {{callbackName}}({{string.Join(", ", declarations)}})
            """.Trim();
        return GeneratorTemplates.RenderBlock(declaration, body);
    }

    private static bool CanInlineInterceptedLambda(InterceptionSite site)
    {
        return site.LambdaBody is not null && site.CanInlineLambda;
    }

    private static string GeneratedLocalName(
        InterceptionSite site,
        string prefix,
        int ordinal)
    {
        string baseName = "__deltaEcs_" + prefix + "_" + site.Id + "_" + ordinal;
        if (site.LambdaIdentifiers.IsEmpty)
        {
            return baseName;
        }

        string candidate = baseName;
        int suffix = 0;
        while (site.LambdaIdentifiers.Contains(candidate))
        {
            candidate = baseName + "_" + ++suffix;
        }

        return candidate;
    }

    private static string AppendInterceptedLambdaBody(InterceptionSite site, string indent)
    {
        if (site.LambdaBodyIsBlock)
        {
            return GeneratorTemplates.Indent(site.LambdaBody!, indent);
        }
        return site.LambdaBody is null ? string.Empty : indent + site.LambdaBody + ";";
    }

    private static string RenderInterceptedClosedMethod(IterationModel shape, InterceptionSite site)
    {
        IterationModel closedShape = new(
            ReceiverKind.World, shape.ExplicitIds, shape.HasEntity, shape.HasContext,
            isFunctor: true, implicitComponents: true, shape.Pattern, shape.Components,
            functorType: null, shape.ContextType, contextMode: shape.ContextMode,
            methodName: shape.MethodName, isStamp: shape.IsStamp);
        string[] parameters = InterceptedParameterNames(site);
        string methodName = "ExecuteInterceptedClosed_" + site.Id;
        string callbackName = "InvokeInterceptedCallback_" + site.Id;
        string countName = GeneratedLocalName(site, "count", 0);
        string indexName = GeneratedLocalName(site, "index", 0);
        string[] rowNames = shape.IsStamp
            ? Array.Empty<string>()
            : Enumerable.Range(0, closedShape.ComponentModels.Length).Select(index => GeneratedLocalName(site, "row", index)).ToArray();
        string componentParameters = closedShape.ExplicitIds ? ", " + ClosedComponentParameters(closedShape.Components.Length) : string.Empty;
        string contextParameter = closedShape.HasContext
            ? ", " + ContextParameter(closedShape.ContextMode, InterceptedContextType(closedShape), parameters[0])
            : string.Empty;
        string signature = $"private static void {methodName}(global::Delta.ECS.World world, in global::Delta.ECS.Query query{componentParameters}{contextParameter})";
        var lines = new List<string>
        {
            "[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]",
            signature,
            "{",
            GeneratorTemplates.Indent(AccessSetup(closedShape, closedShape.ExplicitIds ? ClosedComponentNames(closedShape.Components.Length) : string.Empty, closed: true, prepared: true).TrimEnd(), "    "),
        };
        if (shape.IsStamp)
        {
            lines.Add("    using var execution = GeneratedForEachRuntime.OpenReadDense(world, in query);");
        }
        else
        {
            lines.Add($"    using var execution = GeneratedForEachRuntime.{(closedShape.ComponentModels.Any(static component => component.IsWrite) ? "OpenWriteDense" : "OpenReadDense")}(world, in query);");
            lines.AddRange(SplitLines(AppendQueryComponentRoutes(closedShape, "    ")));
            lines.AddRange(SplitLines(AppendArchetypeWriteSetup(shape, "    ")));
        }
        lines.Add(shape.IsStamp || closedShape.HasEntity
            ? "    while (execution.MoveNextTrusted(out var slots))"
            : $$"""    while (execution.MoveNextTrusted(out var componentRows, out int {{countName}}))""");
        lines.Add("    {");
        if (!shape.IsStamp)
        {
            for (int index = 0; index < closedShape.ComponentModels.Length; index++)
            {
                string type = closedShape.Components[index];
                lines.Add(closedShape.HasEntity
                    ? $"        ref {type} {rowNames[index]} = ref slots.GetGenerated{(closedShape.ComponentModels[index].IsWrite ? "Write" : "Read")}Reference<{type}>(access{index});"
                    : $"        ref {type} {rowNames[index]} = ref GeneratedForEachRuntime.GetGeneratedRow<{type}>(componentRows, route{index});");
            }
        }
        if (shape.IsStamp || closedShape.HasEntity)
        {
            lines.Add($"        int {countName} = slots.Count;");
        }
        lines.Add(closedShape.HasEntity || shape.IsStamp
            ? $"        for (int {indexName} = 0; {indexName} < {countName}; {indexName}++)"
            : $"        int {indexName} = 0;\n        while ({indexName} < {countName})");
        lines.Add("        {");
        int parameterIndex = closedShape.HasContext ? 1 : 0;
        if (closedShape.HasEntity)
        {
            lines.Add($"            global::Delta.ECS.Entity {parameters[parameterIndex]} = slots.EntityAt({indexName});");
            parameterIndex++;
        }
        for (int index = 0; index < closedShape.ComponentModels.Length; index++)
        {
            if (shape.IsStamp)
            {
                lines.Add($"            Stamp {parameters[parameterIndex + index]} = slots.GetGeneratedStamp(access{index}, {indexName});");
            }
            else
            {
                string reference = closedShape.HasEntity
                    ? $"ref global::System.Runtime.CompilerServices.Unsafe.Add(ref {rowNames[index]}, {indexName})"
                    : $"ref {rowNames[index]}";
                lines.Add($"            {(closedShape.ComponentModels[index].IsWrite ? "ref " : "ref readonly ")}{closedShape.ComponentModels[index].ResolvedTypeName} {parameters[parameterIndex + index]} = {reference};");
            }
        }
        lines.Add(CanInlineInterceptedLambda(site)
            ? AppendInterceptedLambdaBody(site, "            ")
            : AppendCallbackInvocation(closedShape, callbackName, parameters, "            "));
        if (!shape.IsStamp && !closedShape.HasEntity)
        {
            lines.AddRange(Enumerable.Range(0, closedShape.ComponentModels.Length)
                .Select(index => $"        {rowNames[index]} = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref {rowNames[index]}, 1);"));
            lines.Add($"        {indexName}++;");
        }
        lines.Add("        }");
        lines.Add("    }");
        lines.Add("}");
        return string.Join("\n", lines);
    }

    private static string RenderInterceptedParallelInvoker(IterationModel shape, InterceptionSite site)
    {
        string name = "InterceptedParallelInvoker_" + site.Id;
        string[] parameters = InterceptedParameterNames(site);
        string callbackName = "InvokeInterceptedCallback_" + site.Id;
        string countName = GeneratedLocalName(site, "count", 0);
        string indexName = GeneratedLocalName(site, "index", 0);
        string[] rowNames = shape.IsStamp
            ? Array.Empty<string>()
            : Enumerable.Range(0, shape.ComponentModels.Length).Select(index => GeneratedLocalName(site, "row", index)).ToArray();
        var fields = new List<string>();
        if (shape.HasContext)
        {
            fields.Add($"    private {InterceptedContextType(shape)} _context;");
        }
        fields.AddRange(Enumerable.Range(0, shape.ComponentModels.Length).Select(index => $"    private readonly int _access{index};"));
        var constructorParameters = new List<string>();
        if (shape.HasContext)
        {
            constructorParameters.Add(InterceptedContextType(shape) + " context");
        }
        constructorParameters.Add(AccessTokenParameters(shape.ComponentModels));
        var constructorAssignments = new List<string>();
        if (shape.HasContext)
        {
            constructorAssignments.Add("        _context = context;");
        }
        constructorAssignments.AddRange(Enumerable.Range(0, shape.ComponentModels.Length).Select(index =>
            $"        _access{index} = GeneratedForEachRuntime.Get{(shape.IsStamp || !shape.ComponentModels[index].IsWrite ? "Read" : "Write")}QueryComponentIndex(access{index});"));
        var body = new List<string>();
        if (shape.HasContext)
        {
            body.Add(shape.ContextMode switch
            {
                ContextModeKind.Value => $"        {InterceptedContextType(shape)} {parameters[0]} = _context;",
                ContextModeKind.Ref => $"        ref {InterceptedContextType(shape)} {parameters[0]} = ref _context;",
                _ => $"        ref readonly {InterceptedContextType(shape)} {parameters[0]} = ref _context;",
            });
        }
        if (!shape.IsStamp)
        {
            body.AddRange(Enumerable.Range(0, shape.ComponentModels.Length).Select(index =>
                $"        ref {shape.ComponentModels[index].ResolvedTypeName} {rowNames[index]} = ref slots.GetGeneratedReadReference<{shape.ComponentModels[index].ResolvedTypeName}>(_access{index});"));
        }
        body.Add($"        int {countName} = slots.Count;");
        body.Add($"        for (int {indexName} = 0; {indexName} < {countName}; {indexName}++)");
        body.Add("        {");
        int parameterIndex = shape.HasContext ? 1 : 0;
        if (shape.HasEntity)
        {
            body.Add($"            global::Delta.ECS.Entity {parameters[parameterIndex++]} = slots.EntityAt({indexName});");
        }
        body.AddRange(Enumerable.Range(0, shape.ComponentModels.Length).Select(index => shape.IsStamp
            ? $"            Stamp {parameters[parameterIndex + index]} = slots.GetGeneratedStamp(_access{index}, {indexName});"
            : $"            {(shape.ComponentModels[index].IsWrite ? "ref " : "ref readonly ")}{shape.ComponentModels[index].ResolvedTypeName} {parameters[parameterIndex + index]} = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref {rowNames[index]}, {indexName});"));
        body.Add(CanInlineInterceptedLambda(site)
            ? AppendInterceptedLambdaBody(site, "            ")
            : AppendCallbackInvocation(shape, callbackName, parameters, "            "));
        body.Add("        }");
        string members = string.Join("\n", new[]
        {
            string.Join("\n", fields),
            $$"""
                internal {{name}}({{string.Join(", ", constructorParameters)}})
                {
                {{GeneratorTemplates.Indent(string.Join("\n", constructorAssignments), "    ")}}
                }
            """.Trim(),
            $"    public bool RequiresSingleThread => {(shape.ContextMode == ContextModeKind.Ref ? "true" : "false")};",
            "    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]",
            "    public void Invoke(ref GeneratedQuerySlots slots)",
            "    {",
            string.Join("\n", body),
            "    }",
            shape.HasContext ? $"    internal {InterceptedContextType(shape)} Context => _context;" : string.Empty,
        }.Where(static value => !string.IsNullOrEmpty(value)));
        return GeneratorTemplates.RenderBlock($"private struct {name} : IGeneratedParallelInvoker", members);
    }

    private static string AppendCallbackInvocation(
        IterationModel shape,
        string target,
        string[] parameters,
        string indent)
    {
        var invocationArguments = new List<string>();
        int parameterIndex = 0;
        if (shape.HasContext)
        {
            invocationArguments.Add(ContextInvocation(shape.ContextMode, parameters[parameterIndex++]));
        }

        if (shape.HasEntity)
        {
            invocationArguments.Add(parameters[parameterIndex++]);
        }
        invocationArguments.AddRange(Enumerable.Range(0, shape.ComponentModels.Length)
            .Select(index => shape.ComponentModels[index].InvocationModifier + parameters[parameterIndex + index]));
        return indent + target + "(" + string.Join(", ", invocationArguments) + ");";
    }

    private static string RenderInterceptedParallelClosedMethod(IterationModel shape, InterceptionSite site)
    {
        IterationModel accessShape = new(
            ReceiverKind.World, shape.ExplicitIds, shape.HasEntity, shape.HasContext,
            isFunctor: true, implicitComponents: true, shape.Pattern, shape.Components,
            functorType: null, shape.ContextType, parallel: shape.Parallel,
            contextMode: shape.ContextMode, methodName: shape.MethodName,
            hasEntityTarget: shape.HasEntityTarget, hasQuery: true, isStamp: shape.IsStamp);
        string[] parameters = InterceptedParameterNames(site);
        string methodName = "ExecuteInterceptedClosed_" + site.Id;
        string invokerType = "InterceptedParallelInvoker_" + site.Id;
        string componentParameters = shape.ExplicitIds ? ", " + ClosedComponentParameters(shape.Components.Length) : string.Empty;
        string contextParameter = shape.HasContext
            ? ", " + ContextParameter(shape.ContextMode, InterceptedContextType(shape), parameters[0])
            : string.Empty;
        string target = shape.HasEntityTarget ? ", global::System.ReadOnlySpan<global::Delta.ECS.Entity> entities" : string.Empty;
        string signature = $"private static void {methodName}(global::Delta.ECS.World world{target}, in global::Delta.ECS.Query query{componentParameters}{contextParameter}{(shape.Parallel ? ", int workerCount" : string.Empty)})";
        string constructorArguments = string.Join(", ", new[]
        {
            shape.HasContext ? parameters[0] : null,
            AccessArguments(shape.ComponentModels),
        }.Where(static value => !string.IsNullOrEmpty(value)));
        string execute = shape.HasEntityTarget
            ? $"GeneratedForEachRuntime.ExecuteEntityList{(shape.Parallel ? "Parallel" : string.Empty)}(world, in query, entities, ref invoker, {AppendParallelWriteIndices(accessShape)}{(shape.Parallel ? ", workerCount" : string.Empty)});"
            : $"GeneratedForEachRuntime.ExecuteParallelDense(world, in query, ref invoker, {AppendParallelWriteIndices(accessShape)}, workerCount);";
        string body = $$"""
                {{GeneratorTemplates.Indent(AccessSetup(accessShape, accessShape.ExplicitIds ? ClosedComponentNames(accessShape.Components.Length) : string.Empty, closed: true, prepared: true).TrimEnd(), "    ")}}
                var invoker = new {{invokerType}}({{constructorArguments}});
                {{execute}}
                {{(shape.HasContext && shape.ContextMode == ContextModeKind.Ref ? parameters[0] + " = invoker.Context;" : string.Empty)}}
            """;
        string declaration = $$"""
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            {{signature}}
            """.Trim();
        return GeneratorTemplates.RenderBlock(declaration, body);
    }

    private static string[] InterceptedParameterNames(InterceptionSite site)
    {
        return site.LambdaParameterNames;
    }

    private static string RenderInterceptor(IterationModel shape, InterceptionSite site)
    {
        var parameters = new List<string> { "this global::Delta.ECS.World world" };
        if (shape.HasEntityTarget)
        {
            parameters.Add("global::System.ReadOnlySpan<global::Delta.ECS.Entity> entities");
        }

        if (shape.HasQuery)
        {
            parameters.Add("in global::Delta.ECS.Query query");
        }
        if (shape.ExplicitIds)
        {
            parameters.AddRange(Enumerable.Range(0, shape.Components.Length)
                .Select(index => "global::Delta.ECS.ComponentId component" + index));
        }
        if (shape.HasContext)
        {
            parameters.Add(ContextParameter(shape.ContextMode, InterceptedContextType(shape), "context"));
        }

        parameters.Add("global::Delta.ECS." + ConcreteActionType(shape) + " _");
        if (shape.Parallel)
        {
            parameters.Add("int workerCount = 0");
        }
        string query = shape.HasQuery
            ? string.Empty
            : $$"""
                    global::Delta.ECS.Query query = world.WhereAll(stackalloc global::Delta.ECS.ComponentId[]
                    {
                        {{(shape.ExplicitIds
                            ? ComponentNames(shape.Components.Length)
                            : string.Join(", ", shape.Components.Select(component => "world.Layouts.GetPrimary(typeof(" + component + "))")))}}
                    });
                """;
        var invocation = new List<string> { "world" };
        if (shape.HasEntityTarget)
        {
            invocation.Add("entities");
        }
        invocation.Add("in query");
        if (shape.ExplicitIds)
        {
            invocation.Add(ComponentNames(shape.Components.Length));
        }

        if (shape.HasContext)
        {
            invocation.Add(ContextInvocation(shape.ContextMode, "context"));
        }

        if (shape.Parallel)
        {
            invocation.Add("workerCount");
        }
        string body = query + "        ExecuteInterceptedClosed_" + site.Id + "(" + string.Join(", ", invocation) + ");";
        string declaration = $$"""
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            {{site.Attribute}}
            internal static void Intercept_{{site.Id}}({{string.Join(", ", parameters)}})
            """.Trim();
        return GeneratorTemplates.Indent(GeneratorTemplates.RenderBlock(declaration, body), "    ");
    }

    private static string ConcreteActionType(IterationModel shape)
    {
        string suffix = IsAllWrite(shape.ComponentModels) ? string.Empty : "_" + shape.Pattern;
        string generic = shape.IsStamp
            ? string.Join(", ", Enumerable.Repeat("global::Delta.ECS.Stamp", shape.Components.Length))
            : string.Join(", ", shape.Components);
        if (shape.HasContext)
        {
            generic = JoinGeneric(InterceptedContextType(shape), generic);
            return TypeWithGenericArgs(
                (shape.HasEntity ? "ForEachContextEntityAction" : "ForEachContextAction") + ContextDelegateSuffix(shape.ContextMode) + suffix,
                generic);
        }

        return TypeWithGenericArgs(
            (shape.HasEntity ? "ForEachEntityAction" : "ForEachAction") + suffix,
            generic);
    }

    private static string InterceptedContextType(IterationModel shape)
        => shape.ContextType ?? "global::System.Object";

    private static string RenderClosedDenseMethod(
        IterationModel shape,
        string methodName,
        string ids,
        string componentParameters)
    {
        string generic = ComponentGenericTypes(shape);
        string genericPrefix = StateGeneric(shape, generic);
        string contextParameter = shape.HasContext
            ? ", " + ContextParameter(shape.ContextMode, ContextType(shape), "context")
            : string.Empty;
        string callbackParameter = shape.IsFunctor
            ? ", ref " + shape.FunctorType + " functor"
            : ", " + ActionType(shape) + " action";
        string target = shape.HasEntityTarget ? ", global::System.ReadOnlySpan<Entity> entities, in Query query" : ", in Query query";
        string signature = $"private static void {methodName}{genericPrefix}(World world{target}{componentParameters}{contextParameter}{callbackParameter})";
        var lines = new List<string>
        {
            "[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]",
            signature,
            "{",
            GeneratorTemplates.Indent(AccessSetup(shape, ids, closed: true, prepared: true).TrimEnd(), "    "),
        };
        if (shape.HasEntityTarget)
        {
            string invokerType = ParallelInvokerName(shape) + StateGeneric(shape, generic);
            string arguments = string.Join(", ", new[]
            {
                shape.HasContext ? "context" : null,
                shape.IsFunctor ? "functor" : "action",
                AccessArguments(shape.ComponentModels),
            }.Where(static value => !string.IsNullOrEmpty(value)));
            lines.Add($"    var invoker = new {invokerType}({arguments});");
            lines.Add($"    GeneratedForEachRuntime.ExecuteEntityList(world, in query, entities, ref invoker, {AppendParallelWriteIndices(shape)});");
            if (shape.HasContext && shape.ContextMode == ContextModeKind.Ref)
            {
                lines.Add("    context = invoker.Context;");
            }

            if (shape.IsFunctor)
            {
                lines.Add("    functor = invoker.Functor;");
            }
            lines.Add("}");
            return GeneratorTemplates.Indent(string.Join("\n", lines), "    ");
        }

        if (shape.IsStamp)
        {
            lines.Add("    using var execution = GeneratedForEachRuntime.OpenReadDense(world, in query);");
        }
        else
        {
            lines.Add($"    using var execution = GeneratedForEachRuntime.{(shape.ComponentModels.Any(static component => component.IsWrite) ? "OpenWriteDense" : "OpenReadDense")}(world, in query);");
            lines.AddRange(SplitLines(AppendQueryComponentRoutes(shape, "    ")));
            lines.AddRange(SplitLines(AppendArchetypeWriteSetup(shape, "    ")));
        }
        lines.Add(shape.IsStamp || shape.HasEntity
            ? "    while (execution.MoveNextTrusted(out var slots))"
            : "    while (execution.MoveNextTrusted(out var componentRows, out int count))");
        lines.Add("    {");
        if (shape.IsStamp || shape.HasEntity)
        {
            lines.Add("        int count = slots.Count;");
        }
        for (int index = 0; index < shape.ComponentModels.Length; index++)
        {
            if (shape.IsStamp)
            {
                continue;
            }
            string type = ComponentType(shape, index);
            string row = $"row{index}";
            lines.Add(shape.HasEntity
                ? $"        ref {type} {row} = ref slots.GetGenerated{(shape.ComponentModels[index].IsWrite ? "Write" : "Read")}Reference<{type}>(access{index});"
                : $"        ref {type} {row} = ref GeneratedForEachRuntime.GetGeneratedRow<{type}>(componentRows, route{index});");
        }
        lines.Add("        for (int index = 0; index < count; index++)");
        lines.Add("        {");
        if (shape.HasEntity)
        {
            lines.Add("            Entity entity = slots.EntityAt(index);");
        }
        for (int index = 0; index < shape.ComponentModels.Length; index++)
        {
            string type = ComponentType(shape, index);
            lines.Add(shape.IsStamp
                ? $"            Stamp component{index} = slots.GetGeneratedStamp(access{index}, index);"
                : $"            {(shape.ComponentModels[index].IsWrite ? "ref " : "ref readonly ")}{type} component{index} = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref row{index}, index);");
        }
        lines.Add("            " + AppendClosedInvocation(shape, "action", "functor", "context", "component", "entity") + ";");
        lines.Add("        }");
        lines.Add("    }");
        lines.Add("}");
        return GeneratorTemplates.Indent(string.Join("\n", lines), "    ");
    }

    private static string[] SplitLines(string text)
        => string.IsNullOrEmpty(text) ? Array.Empty<string>() : text.TrimEnd().Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);

    private static string RenderExtensionMethod(
        IterationModel shape,
        string prefix,
        string query,
        string contextParameter,
        string ids,
        string callback,
        string invokerName,
        string stateGeneric,
        string genericPrefix,
        string setup,
        string accessArguments,
        string className,
        bool profiling,
        string? closedMethodName)
    {
        string componentPart = string.IsNullOrEmpty(ids) ? string.Empty : $", {ids}";
        string methodName = shape.MethodName;
        string profileName = className + "." + methodName;
        string callbackName = shape.IsFunctor ? "functor" : "action";
        string callbackParameter = shape.IsFunctor
            ? ", ref " + shape.FunctorType + " " + callbackName
            : ", " + callback + " " + callbackName;
        string workerCountParameter = shape.Parallel ? ", int workerCount = 0" : string.Empty;
        string visibility = shape.IsFunctor || shape.ImplicitComponents ? "internal" : "public";
        string signature = $"{visibility} static void {methodName}{genericPrefix}({prefix}{query}{componentPart}{contextParameter}{callbackParameter}{workerCountParameter})";
        string body = BuildBody(
            shape,
            accessArguments,
            invokerName,
            stateGeneric,
            setup,
            callbackName,
            hasAction: !shape.IsFunctor,
            profiling,
            StableProfileMethodId(profileName),
            closedMethodName);
        return GeneratorTemplates.Indent(
            RenderMethod(
                GeneratorTemplates.Documentation(shape.Api),
                signature,
                body,
                profiling ? profileName : null),
            "    ");
    }

    private static string BuildBody(
        IterationModel shape,
        string accessArguments,
        string invokerName,
        string stateGeneric,
        string setup,
        string callbackName,
        bool hasAction,
        bool profiling,
        int methodId,
        string? closedMethodName)
    {
        var closedArguments = new List<string>(shape.HasEntityTarget
            ? new[] { "world", "entities", "in query" }
            : new[] { "world", "in query" });
        if (shape.ExplicitIds)
        {
            closedArguments.Add(ComponentNames(shape.Components.Length));
        }

        if (shape.HasContext)
        {
            closedArguments.Add(ContextInvocation(shape.ContextMode, "context"));
        }

        closedArguments.Add(shape.IsFunctor ? "ref functor" : "action");
        if (shape.Parallel)
        {
            closedArguments.Add("workerCount");
        }

        if (accessArguments.Length > 0 && closedMethodName is null)
        {
            closedArguments.Add(accessArguments);
        }
        string invoke = closedMethodName + StateGeneric(shape, ComponentGenericTypes(shape))
            + "(" + string.Join(", ", closedArguments) + ");";
        var lines = new List<string> { "{" };
        if (!shape.HasQuery)
        {
            string queryComponents = shape.ExplicitIds ? ComponentNames(shape.Components.Length) : PrimaryArguments(shape);
            lines.Add($"    Query query = world.WhereAll(stackalloc ComponentId[] {{ {queryComponents} }});");
        }
        string indent = "    ";
        if (profiling)
        {
            lines.Add($"    global::DeltaECS.Profiling.ProfilerRuntime.Enter({methodId});");
            lines.Add("    try");
            lines.Add("    {");
            indent = "        ";
        }
        if (hasAction)
        {
            lines.Add(indent + "global::Delta.ECS.GeneratedForEachRuntime.ThrowIfNull(action, nameof(action));");
        }

        if (!string.IsNullOrEmpty(setup))
        {
            lines.Add(indent + setup);
        }
        lines.Add(indent + invoke);
        if (profiling)
        {
            lines.Add("    }");
            lines.Add("    finally");
            lines.Add("    {");
            lines.Add($"        global::DeltaECS.Profiling.ProfilerRuntime.Leave({methodId});");
            lines.Add("    }");
        }
        lines.Add("}");
        return string.Join("\n", lines);
    }

    private static string RenderMethod(string documentation, string signature, string body, string? profileName)
    {
        string profile = profileName is null
            ? string.Empty
            : $$"""
                [global::DeltaECS.Profiling.ProfiledMethodMetadataAttribute({{StableProfileMethodId(profileName)}}, "{{profileName}}")]
                """.TrimEnd();
        return $$"""
            {{documentation}}
            {{profile}}
            [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            {{signature}}
            {{GeneratorTemplates.Indent(body, "    ")}}
            """.TrimEnd();
    }

    private static string AppendArchetypeWriteSetup(IterationModel shape, string indent)
    {
        int writeCount = shape.ComponentModels.Count(static component => component.IsWrite);
        if (writeCount > 1)
        {
            string routes = string.Join(", ", WriteIndices(shape.ComponentModels).Select(index => "route" + index));
            return $$"""
                {{indent}}var stampWriter = new {{ArchetypeStampWriterName(shape)}}({{routes}});
                {{indent}}execution.MarkArchetypeWrites(ref stampWriter);
                """.TrimEnd();
        }

        return string.Join("\n", WriteIndices(shape.ComponentModels)
            .Select(index => $"{indent}execution.MarkArchetypeWrite(route{index});"));
    }

    private static string AppendQueryComponentRoutes(IterationModel shape, string indent)
    {
        if (!shape.HasEntity && !shape.ExplicitIds)
        {
            return string.Empty;
        }

        return string.Join("\n", Enumerable.Range(0, shape.ComponentModels.Length)
            .Where(index => !shape.HasEntity || shape.ComponentModels[index].IsWrite)
            .Select(index => $"{indent}int route{index} = GeneratedForEachRuntime.Get{(shape.ComponentModels[index].IsWrite ? "Write" : "Read")}QueryComponentIndex(access{index});"));
    }

    private static string AccessSetup(IterationModel shape, string ids, bool closed, bool prepared = false)
    {
        string[] componentIds = shape.ExplicitIds
            ? ids.Split(new[] { ", " }, StringSplitOptions.None)
            : Array.Empty<string>();
        return string.Join("\n", Enumerable.Range(0, shape.ComponentModels.Length).Select(index =>
        {
            bool routeOnly = prepared
                && !shape.HasEntity
                && !shape.HasEntityTarget
                && !shape.ExplicitIds
                && !shape.Parallel;
            string componentType = ComponentType(shape, index);
            if (shape.IsStamp && prepared)
            {
                return shape.ExplicitIds
                    ? $"var access{index} = GeneratedForEachRuntime.GetPreparedStampAccess(in query, {componentIds[index]});"
                    : $"var access{index} = GeneratedForEachRuntime.GetPreparedStampAccess<{componentType}> (in query);";
            }
            string variable = (routeOnly ? "int route" : "var access") + index;
            string accessKind = shape.ComponentModels[index].IsWrite ? "Write" : "Read";
            string method = prepared
                ? (routeOnly ? "GetPrepared" + accessKind + "Route" : "GetPrepared" + accessKind + "Access")
                : closed
                    ? "Create" + accessKind + "Access"
                    : "Access" + accessKind;
            string generic = prepared && (!shape.ExplicitIds || routeOnly) ? $"<{componentType}>" : string.Empty;
            string arguments = string.Join(", ", new[]
            {
                prepared ? null : "world",
                "in query",
                shape.ExplicitIds ? componentIds[index] : null,
                prepared && (!shape.ExplicitIds || routeOnly) ? null : $"typeof({componentType})",
            }.Where(static value => !string.IsNullOrEmpty(value)));
            return $"{variable} = GeneratedForEachRuntime.{method}{generic}({arguments});";
        }));
    }

    private static string PrimaryArguments(IterationModel shape)
    {
        var result = new string[shape.ComponentModels.Length];
        const string owner = "world";
        for (int index = 0; index < shape.ComponentModels.Length; index++)
        {
            string componentType = ComponentType(shape, index);
            result[index] = owner + ".Layouts.GetPrimary(typeof(" + componentType + "))";
        }

        return string.Join(", ", result);
    }

    private static string AccessArguments(IReadOnlyList<ComponentModel> components)
        => GeneratorSupport.JoinIndexed(components.Count, static index => "access" + index);

    private static string ComponentParameters(int arity)
        => GeneratorSupport.JoinIndexed(arity, static index => "ComponentId component" + index);

    private static string ComponentNames(int arity)
        => GeneratorSupport.JoinIndexed(arity, static index => "component" + index);

    private static string ClosedComponentNames(int arity)
        => GeneratorSupport.JoinIndexed(arity, static index => "componentId" + index);

    private static string ClosedComponentParameters(int arity)
        => GeneratorSupport.JoinIndexed(arity, static index => "ComponentId componentId" + index);

    private static string RefParameters(IReadOnlyList<ComponentModel> components)
        => GeneratorSupport.JoinIndexed(
            components.Count,
            index => components[index].ParameterModifier + components[index].GenericTypeName + " component" + index);

    private static string AccessParameters(IReadOnlyList<ComponentModel> components)
        => GeneratorSupport.JoinIndexed(components.Count, static index => "int access" + index);

    private static string AccessTokenParameters(IReadOnlyList<ComponentModel> components)
        => GeneratorSupport.JoinIndexed(
            components.Count,
            index => (components[index].IsWrite ? "WriteAccess" : "ReadAccess") + " access" + index);

    private static string ActionType(IterationModel shape)
    {
        string generic = shape.IsStamp
            ? string.Join(", ", Enumerable.Repeat("Stamp", shape.Components.Length))
            : shape.GenericSelectors
                ? GeneratorSupport.GenericTypes(shape.Components.Length)
                : string.Join(", ", shape.ComponentModels.Select(static component => component.ResolvedTypeName));
        string suffix = IsAllWrite(shape.ComponentModels) ? string.Empty : "_" + shape.Pattern;
        if (shape.HasContext)
        {
            string contextSuffix = ContextDelegateSuffix(shape.ContextMode);
            return TypeWithGenericArgs(
                (shape.HasEntity ? "ForEachContextEntityAction" : "ForEachContextAction") + contextSuffix + suffix,
                JoinGeneric(shape.IsFunctor || !shape.GenericSelectors ? ContextType(shape) : "TContext", generic));
        }

        return TypeWithGenericArgs(shape.HasEntity ? "ForEachEntityAction" + suffix : "ForEachAction" + suffix, generic);
    }

    private static string ContextDelegateSuffix(ContextModeKind mode)
        => mode switch
        {
            ContextModeKind.In => "_In",
            ContextModeKind.RefReadonly => "_RefReadonly",
            ContextModeKind.Value => "_Value",
            _ => string.Empty
        };

    private static string ContextParameter(ContextModeKind mode, string type, string name)
        => mode switch
        {
            ContextModeKind.Ref => "ref " + type + " " + name,
            ContextModeKind.In => "in " + type + " " + name,
            ContextModeKind.RefReadonly => "ref readonly " + type + " " + name,
            _ => type + " " + name
        };

    private static string ContextInvocation(ContextModeKind mode, string name)
        => mode switch
        {
            ContextModeKind.Ref => "ref " + name,
            ContextModeKind.In or ContextModeKind.RefReadonly => "in " + name,
            _ => name
        };

    private static string StateGeneric(IterationModel shape, string generic)
        => !shape.GenericSelectors
            ? string.Empty
            : TypeParameterList(shape.IsFunctor ? generic : shape.HasContext ? JoinGeneric("TContext", generic) : generic);

    private static string InvokerName(IterationModel shape) => "DemandForEachInvoker_" + GeneratorSupport.StableName(shape.Key);

    private static string ParallelInvokerName(IterationModel shape)
        => "DemandForEachParallelInvoker_" + GeneratorSupport.StableName(shape.Key);

    private static string ArchetypeStampWriterName(IterationModel shape)
        => "DemandForEachArchetypeStampWriter_" + GeneratorSupport.StableName(shape.Key);

    private static string ComponentGenericTypes(IterationModel shape)
        => shape.GenericSelectors ? GeneratorSupport.GenericTypes(shape.Components.Length) : string.Empty;

    private static string ComponentType(IterationModel shape, int index)
        => shape.ComponentModels[index].TypeName;

    private static string CallbackComponentType(IterationModel shape, int index)
        => shape.IsStamp ? "global::Delta.ECS.Stamp" : shape.ComponentModels[index].ResolvedTypeName;

    private static string ContextType(IterationModel shape)
        => shape.IsFunctor || shape.ImplicitComponents
            ? shape.ContextType ?? "TContext"
            : "TContext";

    private static string JoinGeneric(params string[] values)
        => string.Join(", ", values.Where(static value => !string.IsNullOrEmpty(value)));

    private static string TypeWithGenericArgs(string name, string generic)
        => string.IsNullOrEmpty(generic) ? name : name + "<" + generic + ">";

    private static string TypeParameterList(string generic)
        => string.IsNullOrEmpty(generic) ? string.Empty : "<" + generic + ">";

    private static string JoinParameters(string prefix, string parameters)
        => string.IsNullOrEmpty(parameters) ? prefix : prefix + ", " + parameters;

    private static string ConstructorName(string name)
    {
        int index = name.IndexOf('<');
        return index < 0 ? name : name.Substring(0, index);
    }

    private static bool IsAllWrite(IReadOnlyList<ComponentModel> components)
        => components.All(static component => component.IsWrite);

    private static IEnumerable<int> WriteIndices(IReadOnlyList<ComponentModel> components)
    {
        for (int index = 0; index < components.Count; index++)
        {
            if (components[index].IsWrite)
            {
                yield return index;
            }
        }
    }


}
