using System.Collections.Immutable;

namespace Delta.ECS.Generators;

/// <summary>Raw-string templates for validated demand-driven iteration shapes.</summary>
internal static class DemandDrivenForEachTemplates
{
    private const string InterceptorSourceHeader = """
        // <auto-generated />
        #nullable enable
        #pragma warning disable CS0436 // Demand-generated callback contracts can also arrive through a referenced consumer assembly.

        """;
    private const string InterceptorSourceFooter = """
        }

        }

        namespace System.Runtime.CompilerServices
        {

        file sealed class InterceptsLocationAttribute : global::System.Attribute
        {
            internal InterceptsLocationAttribute(int version, string data) { }
        }
        }
        """;

    internal static string Render(IterationRenderModel model)
    {
        IterationModel shape = model.Shape;
        string? contracts = model.RenderContracts && !shape.IsFunctor && shape.ComponentModels.Length > 0
            ? RenderContracts(model)
            : null;
        string? stampWriter = shape.ComponentModels.Count(static component => component.IsWrite) > 1
            ? RenderArchetypeStampWriter(shape)
            : null;
        string? invoker = shape.Parallel || shape.HasEntityTarget
            ? RenderParallelInvoker(shape)
            : null;
        string extension = GeneratorTemplates.ExtensionTemplate(
            $$"""DemandForEachExtensions_{{GeneratorSupport.StableName(shape.Key)}}""",
            shape.IsFunctor,
            RenderExtensionsBody(model));
        string? componentSetKey = !shape.HasQuery && !shape.Api.Signature.HasExplicitIds
            ? GeneratorTemplates.PrimaryComponentSetKeyDeclaration(shape.Api.Selector.Arity)
            : null;
        string[] members = new[] { componentSetKey, contracts, stampWriter, invoker, extension }
            .OfType<string>()
            .ToArray();
        return GeneratorTemplates.FileTemplate(new GeneratedFileModel(
            "Delta.ECS",
            ImmutableArray.Create("using System;"),
            members.ToImmutableArray()));
    }

    private static string RenderContracts(IterationRenderModel model)
    {
        IterationModel shape = model.Shape;
        SignatureProjection slots = shape.Api.Signature;
        string generic = slots.GenericList();
        string parameters = slots.ComponentParameters();
        string suffix = IsAllWrite(shape.ComponentModels) ? string.Empty : "_" + shape.Pattern;
        IEnumerable<string> contracts = new[]
        {
            AppendContract("ForEachAction" + suffix, generic, parameters),
            AppendContract("ForEachEntityAction" + suffix, generic, SignatureProjection.JoinParameters("Entity entity", parameters)),
        }.Concat(model.SupportedContextModes
            .SelectMany(mode =>
            {
                string context = SignatureProjection.ContextParameter(mode, "TContext", "context");
                string contextGeneric = SignatureProjection.JoinGeneric("TContext", generic);
                string modeSuffix = ContextDelegateSuffix(mode);
                return new[]
                {
                    AppendContract("ForEachContextAction" + modeSuffix + suffix, contextGeneric, SignatureProjection.JoinParameters(context, parameters)),
                    AppendContract(
                        "ForEachContextEntityAction" + modeSuffix + suffix,
                        contextGeneric,
                        SignatureProjection.JoinParameters(SignatureProjection.JoinParameters(context, "Entity entity"), parameters)),
                };
            }));
        return string.Join("\n", contracts) + "\n";
    }

    private static string AppendContract(string name, string generic, string parameters)
        => $$"""public delegate void {{SignatureProjection.TypeWithArguments(name, generic)}}({{parameters}});""";

    private static string RenderArchetypeStampWriter(IterationModel shape)
    {
        string name = ArchetypeStampWriterName(shape);
        int[] writes = GeneratorTemplates.WriteIndices(shape.ComponentModels).ToArray();
        string fields = GeneratorTemplates.JoinNonEmpty(writes.Select(index => $$"""private readonly int _access{{index}};"""));
        string constructorParameters = string.Join(", ", writes.Select(index => $$"""int access{{index}}"""));
        string assignments = GeneratorTemplates.JoinNonEmpty(writes.Select(index => $$"""_access{{index}} = access{{index}};"""));
        string increments = GeneratorTemplates.JoinNonEmpty(writes.Select(index =>
            $$"""GeneratedForEachRuntime.IncrementArchetypeStamp(stamps, _access{{index}});"""));
        return $$"""
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            internal struct {{name}} : IGeneratedArchetypeStampWriter
            {
            {{fields}}

                internal {{name}}({{constructorParameters}})
                {
            {{assignments}}
                }

                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                void IGeneratedArchetypeStampWriter.Write(Stamp[] stamps)
                {
            {{increments}}
                }
            }
            """;
    }

    private static string RenderParallelInvoker(IterationModel shape)
    {
        SignatureProjection slots = shape.Api.Signature;
        string generic = slots.HasGenericSelectors ? slots.GenericList() : string.Empty;
        string stateGeneric = StateGeneric(shape, generic);
        string name = ParallelInvokerName(shape);
        string actionType = ActionType(shape);
        string rows = shape.IsStamp
            ? string.Empty
            : GeneratorTemplates.JoinNonEmpty(GeneratorTemplates.Indexed(shape.ComponentModels.Length, index =>
            {
                string componentType = shape.ComponentModels[index].TypeName;
                return $$"""ref {{componentType}} row{{index}} = ref slots.GetGeneratedReadReference<{{componentType}}>(_access{{index}});""";
            }));
        string components = GeneratorTemplates.JoinNonEmpty(GeneratorTemplates.Indexed(shape.ComponentModels.Length, index => shape.IsStamp
            ? $$"""Stamp component{{index}} = slots.GetGeneratedStamp(_access{{index}}, index);"""
            : $$"""{{(shape.ComponentModels[index].IsWrite ? "ref " : "ref readonly ")}}{{shape.ComponentModels[index].TypeName}} component{{index}} = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref row{{index}}, index);"""));
        return $$"""
            internal struct {{name}}{{stateGeneric}} : IGeneratedParallelInvoker
            {
            {{AppendInvokerFields(shape, actionType)}}
            {{AppendInvokerConstructor(shape, name, actionType)}}

                public bool RequiresSingleThread => {{(shape.ContextMode == ContextModeKind.Ref ? "true" : "false")}};

                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                public void Invoke(ref GeneratedQuerySlots slots)
                {
            {{rows}}
                    int count = slots.Count;
                    for (int index = 0; index < count; index++)
                    {
            {{components}}
                        {{AppendClosedInvocation(shape, "_action", "_functor", "_context", "component", "slots.EntityAt(index)")}};
                    }
                }
            {{AppendInvokerProperties(shape)}}
            }
            """;
    }

    private static string AppendInvokerFields(IterationModel shape, string actionType)
    {
        string context = shape.HasContext
            ? $$"""private {{ContextType(shape)}} _context;"""
            : string.Empty;
        string callback = shape.IsFunctor
            ? $$"""private {{shape.FunctorType}} _functor;"""
            : $$"""private readonly {{actionType}} _action;""";
        return GeneratorTemplates.JoinNonEmpty(new[] { context, callback }
            .Concat(GeneratorTemplates.Indexed(shape.ComponentModels.Length,
                index => $$"""private readonly int _access{{index}};""")));
    }

    private static string AppendInvokerConstructor(
        IterationModel shape,
        string name,
        string actionType)
    {
        string[] parameters = new[]
            {
                shape.HasContext ? $$"""{{ContextType(shape)}} context""" : string.Empty,
                shape.IsFunctor ? $$"""{{shape.FunctorType}} functor""" : $$"""{{actionType}} action""",
                shape.Api.Signature.AccessParameters(tokens: true)
            }
            .Where(static parameter => parameter.Length != 0)
            .ToArray();
        string[] assignments = new[]
            {
                shape.HasContext ? "_context = context;" : string.Empty,
                shape.IsFunctor ? "_functor = functor;" : "_action = action;"
            }
            .Concat(GeneratorTemplates.Indexed(shape.ComponentModels.Length, index =>
                $$"""_access{{index}} = GeneratedForEachRuntime.Get{{(shape.ComponentModels[index].IsWrite ? "Write" : "Read")}}QueryComponentIndex(access{{index}});"""))
            .Where(static assignment => assignment.Length != 0)
            .ToArray();
        return $$"""
                internal {{ConstructorName(name)}}({{string.Join(", ", parameters)}})
                {
            {{GeneratorTemplates.JoinNonEmpty(assignments)}}
                }
            """;
    }

    private static string AppendInvokerProperties(IterationModel shape)
        => GeneratorTemplates.JoinNonEmpty(new[]
        {
            shape.HasContext ? $$"""internal {{ContextType(shape)}} Context => _context;""" : string.Empty,
            shape.IsFunctor ? $$"""internal {{shape.FunctorType}} Functor => _functor;""" : string.Empty
        });

    private static string RenderClosedParallelMethod(
        IterationModel shape,
        string methodName,
        string componentParameters)
    {
        SignatureProjection slots = shape.Api.Signature;
        string generic = slots.HasGenericSelectors ? slots.GenericList() : string.Empty;
        string genericPrefix = StateGeneric(shape, generic);
        string contextParameter = shape.HasContext
            ? $$""", {{SignatureProjection.ContextParameter(shape.ContextMode, ContextType(shape), "context")}}"""
            : string.Empty;
        string callbackParameter = shape.IsFunctor
            ? $$""", ref {{shape.FunctorType}} functor"""
            : $$""", {{ActionType(shape)}} action""";
        string invokerType = $$"""{{ParallelInvokerName(shape)}}{{StateGeneric(shape, generic)}}""";
        string target = shape.HasEntityTarget
            ? ", global::System.ReadOnlySpan<Entity> entities, in Query query"
            : ", in Query query";
        string arguments = string.Join(", ", new[]
        {
            shape.HasContext ? "context" : null,
            shape.IsFunctor ? "functor" : "action",
            slots.AccessArguments(),
        }.Where(static value => !string.IsNullOrEmpty(value)));
        string execute = shape.HasEntityTarget
            ? "GeneratedForEachRuntime.ExecuteEntityListParallel(world, in query, entities, ref invoker, "
            : "GeneratedForEachRuntime.ExecuteParallelDense(world, in query, ref invoker, ";
        string body = $$"""
                {{GeneratorTemplates.Indent(AccessSetup(shape), "    ")}}
                var invoker = new {{invokerType}}({{arguments}});
                {{execute}}{{AppendParallelWriteIndices(shape)}}, workerCount);
                {{(shape.HasContext && shape.ContextMode == ContextModeKind.Ref ? "context = invoker.Context;" : string.Empty)}}
                {{(shape.IsFunctor ? "functor = invoker.Functor;" : string.Empty)}}
            """;
        string signature = $$"""private static void {{methodName}}{{genericPrefix}}(World world{{target}}{{componentParameters}}{{contextParameter}}{{callbackParameter}}, int workerCount)""";
        return GeneratorTemplates.Indent(GeneratorTemplates.RenderBlock(
            $$"""
                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                {{signature}}
                """.Trim(),
            body), "    ");
    }

    private static string AppendParallelWriteIndices(IterationModel shape)
    {
        if (!shape.ComponentModels.Any(static component => component.IsWrite))
        {
            return "global::System.ReadOnlySpan<int>.Empty";
        }

        string indices = string.Join(", ", GeneratorTemplates.WriteIndices(shape.ComponentModels)
            .Select(index => $$"""global::Delta.ECS.GeneratedForEachRuntime.GetWriteQueryComponentIndex(access{{index}})"""));
        return $$"""stackalloc int[] { {{indices}} }""";
    }

    private static int StableProfileMethodId(string methodName)
    {
        unchecked
        {
            uint hash = 2_166_136_261;
            foreach (char character in methodName)
            {
                hash ^= character;
                hash *= 16_777_619;
            }

            return (int)(hash & 0x7FFF_FFFF);
        }
    }

    private static string AppendClosedInvocation(
        IterationModel shape,
        string actionName,
        string functorName,
        string contextName,
        string componentPrefix,
        string entityExpression)
    {
        var invocationArguments = new List<string>();
        if (shape.HasContext)
        {
            invocationArguments.Add(SignatureProjection.ContextArgument(shape.ContextMode, contextName));
        }

        if (shape.HasEntity)
        {
            invocationArguments.Add(entityExpression);
        }

        string componentArguments = shape.Api.Signature.ComponentArguments(componentPrefix);
        if (componentArguments.Length != 0)
        {
            invocationArguments.Add(componentArguments);
        }
        string invocation = shape.IsFunctor ? $$"""{{functorName}}.Invoke""" : actionName;
        return $$"""{{invocation}}({{string.Join(", ", invocationArguments)}})""";
    }

    private static string RenderExtensionsBody(IterationRenderModel model)
    {
        IterationModel shape = model.Shape;
        SignatureProjection slots = shape.Api.Signature;
        string className = "DemandForEachExtensions_" + GeneratorSupport.StableName(shape.Key);
        string generic = slots.HasGenericSelectors ? slots.GenericList() : string.Empty;
        string ids = slots.HasExplicitIds ? slots.ComponentIdParameters() : string.Empty;
        string stateGeneric = StateGeneric(shape, generic);
        string callback = ActionType(shape);
        string componentParameters = slots.HasExplicitIds ? ", " + slots.ComponentIdParameters("componentId") : string.Empty;
        string prefix = shape.HasEntityTarget
            ? "this World world, global::System.ReadOnlySpan<Entity> entities"
            : "this World world";
        string query = shape.HasQuery ? ", in Query query" : string.Empty;
        string contextParameter = shape.HasContext
            ? ", " + SignatureProjection.ContextParameter(shape.ContextMode, ContextType(shape), "context")
            : string.Empty;
        string closedMethodName = "ExecuteClosed_" + GeneratorSupport.StableName(shape.Key);
        string closed = shape.Parallel
            ? RenderClosedParallelMethod(shape, closedMethodName, componentParameters)
            : RenderClosedDenseMethod(shape, closedMethodName, componentParameters);
        string extension = RenderExtensionMethod(
            shape,
            prefix,
            query,
            contextParameter,
            ids,
            callback,
            stateGeneric,
            className,
            model.Profiling,
            closedMethodName);
        return closed + "\n" + extension;
    }

    internal static string RenderInterceptorSource(InterceptionSite site)
    {
        IterationModel shape = site.IterationModel;
        string usings = string.Join(
            "\n",
            (!site.Usings.Any(static value => value.Trim() is "using Delta.ECS;" or "using global::Delta.ECS;")
                ? new[] { "using global::Delta.ECS;" }
                : Array.Empty<string>())
            .Concat(site.Usings.OrderBy(static value => value, StringComparer.Ordinal)));
        string execution = shape.HasEntityTarget || shape.Parallel
            ? GeneratorTemplates.JoinNonEmpty(new[]
            {
                RenderInterceptedParallelInvoker(shape, site),
                RenderInterceptedParallelClosedMethod(shape, site)
            })
            : RenderInterceptedClosedMethod(shape, site);
        string source = GeneratorTemplates.JoinNonEmpty(new[]
        {
            usings,
            $$"""
            namespace Delta.ECS.Generated
            {

            file static class ForEachInterceptor_{{site.Id}}
            {
            """,
            CanInlineInterceptedLambda(site) ? string.Empty : RenderInterceptedCallback(site),
            execution,
            RenderInterceptor(shape, site)
        });
        return GeneratorTemplates.InterceptorTemplate(
            InterceptorSourceHeader,
            source,
            InterceptorSourceFooter);
    }

    private static string RenderInterceptedCallback(InterceptionSite site)
    {
        IterationModel shape = site.IterationModel;
        SignatureProjection slots = shape.Api.Signature;
        string callbackName = "InvokeInterceptedCallback_" + site.Id;
        string[] parameters = InterceptedParameterNames(site);
        int parameterIndex = 0;
        var declarations = new List<string>();
        if (shape.HasContext)
        {
            declarations.Add(SignatureProjection.ContextParameter(shape.ContextMode, InterceptedContextType(shape), parameters[parameterIndex++]));
        }
        if (shape.HasEntity)
        {
            declarations.Add("global::Delta.ECS.Entity " + parameters[parameterIndex++]);
        }
        declarations.AddRange(Enumerable.Range(0, slots.Arity).Select(index =>
            slots.ComponentParameter(index, CallbackComponentType(shape, index), parameters[parameterIndex + index])));
        string body = site.Binding.LambdaBody is not null
            ? AppendInterceptedLambdaBody(site, "    ")
            : AppendCallbackInvocation(shape, site.Binding.MethodGroupTarget!, parameters, "    ");
        string declaration = $$"""
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            private static void {{callbackName}}({{string.Join(", ", declarations)}})
            """.Trim();
        return GeneratorTemplates.RenderBlock(declaration, body);
    }

    private static bool CanInlineInterceptedLambda(InterceptionSite site)
    {
        return site.Binding.LambdaBody is not null && site.Binding.CanInline;
    }

    private static string GeneratedLocalName(
        InterceptionSite site,
        string prefix,
        int ordinal)
    {
        string baseName = "__deltaEcs_" + prefix + "_" + site.Id + "_" + ordinal;
        if (site.Binding.LambdaIdentifiers.IsEmpty)
        {
            return baseName;
        }

        string candidate = baseName;
        int suffix = 0;
        while (site.Binding.LambdaIdentifiers.Contains(candidate))
        {
            candidate = baseName + "_" + ++suffix;
        }

        return candidate;
    }

    private static string AppendInterceptedLambdaBody(InterceptionSite site, string indent)
    {
        if (site.Binding.LambdaBodyIsBlock)
        {
            return GeneratorTemplates.Indent(site.Binding.LambdaBody!, indent);
        }
        return site.Binding.LambdaBody is null ? string.Empty : indent + site.Binding.LambdaBody + ";";
    }

    private static string RenderInterceptedClosedMethod(IterationModel shape, InterceptionSite site)
    {
        IterationModel closedShape = new(
            shape.RegistrationBinding,
            shape.HasEntity,
            shape.HasContext,
            isFunctor: true,
            shape.Pattern,
            shape.Components,
            functorType: null,
            contextType: shape.ContextType,
            contextMode: shape.ContextMode,
            methodName: shape.MethodName,
            isStamp: shape.IsStamp,
            typeBinding: TypeBindingKind.CallbackInferred);
        string[] parameters = InterceptedParameterNames(site);
        string methodName = "ExecuteInterceptedClosed_" + site.Id;
        string callbackName = "InvokeInterceptedCallback_" + site.Id;
        string countName = GeneratedLocalName(site, "count", 0);
        string indexName = GeneratedLocalName(site, "index", 0);
        string[] rowNames = shape.IsStamp
            ? Array.Empty<string>()
            : GeneratorTemplates.Indexed(closedShape.ComponentModels.Length, index => GeneratedLocalName(site, "row", index)).ToArray();
        SignatureProjection slots = closedShape.Api.Signature;
        string componentParameters = slots.HasExplicitIds ? ", " + slots.ComponentIdParameters("componentId") : string.Empty;
        string contextParameter = closedShape.HasContext
            ? ", " + SignatureProjection.ContextParameter(closedShape.ContextMode, InterceptedContextType(closedShape), parameters[0])
            : string.Empty;
        string signature = $"private static void {methodName}(global::Delta.ECS.World world, in global::Delta.ECS.Query query{componentParameters}{contextParameter})";
        var lines = new List<string>
        {
            "[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]",
            signature,
            "{",
            GeneratorTemplates.Indent(AccessSetup(closedShape).TrimEnd(), "    "),
        };
        if (shape.IsStamp)
        {
            lines.Add("    using var execution = GeneratedForEachRuntime.OpenReadDense(world, in query);");
        }
        else
        {
            lines.Add($"    using var execution = GeneratedForEachRuntime.{(closedShape.ComponentModels.Any(static component => component.IsWrite) ? "OpenWriteDense" : "OpenReadDense")}(world, in query);");
            lines.AddRange(SplitLines(AppendQueryComponentRoutes(closedShape, "    ")));
            lines.AddRange(SplitLines(AppendArchetypeWriteSetup(shape, "    ")));
        }
        lines.Add(shape.IsStamp || closedShape.HasEntity
            ? "    while (execution.MoveNextTrusted(out var slots))"
            : $$"""    while (execution.MoveNextTrusted(out var componentRows, out int {{countName}}))""");
        lines.Add("    {");
        if (!shape.IsStamp)
        {
            for (int index = 0; index < closedShape.ComponentModels.Length; index++)
            {
                string type = closedShape.Components[index];
                lines.Add(closedShape.HasEntity
                    ? $"        ref {type} {rowNames[index]} = ref slots.GetGenerated{(closedShape.ComponentModels[index].IsWrite ? "Write" : "Read")}Reference<{type}>(access{index});"
                    : $"        ref {type} {rowNames[index]} = ref GeneratedForEachRuntime.GetGeneratedRow<{type}>(componentRows, route{index});");
            }
        }
        if (shape.IsStamp || closedShape.HasEntity)
        {
            lines.Add($"        int {countName} = slots.Count;");
        }
        lines.Add(closedShape.HasEntity || shape.IsStamp
            ? $"        for (int {indexName} = 0; {indexName} < {countName}; {indexName}++)"
            : $"        int {indexName} = 0;\n        while ({indexName} < {countName})");
        lines.Add("        {");
        int parameterIndex = closedShape.HasContext ? 1 : 0;
        if (closedShape.HasEntity)
        {
            lines.Add($"            global::Delta.ECS.Entity {parameters[parameterIndex]} = slots.EntityAt({indexName});");
            parameterIndex++;
        }
        for (int index = 0; index < closedShape.ComponentModels.Length; index++)
        {
            if (shape.IsStamp)
            {
                lines.Add($"            Stamp {parameters[parameterIndex + index]} = slots.GetGeneratedStamp(access{index}, {indexName});");
            }
            else
            {
                string reference = closedShape.HasEntity
                    ? $"ref global::System.Runtime.CompilerServices.Unsafe.Add(ref {rowNames[index]}, {indexName})"
                    : $"ref {rowNames[index]}";
                lines.Add($"            {(closedShape.ComponentModels[index].IsWrite ? "ref " : "ref readonly ")}{closedShape.ComponentModels[index].ResolvedTypeName} {parameters[parameterIndex + index]} = {reference};");
            }
        }
        lines.Add(CanInlineInterceptedLambda(site)
            ? AppendInterceptedLambdaBody(site, "            ")
            : AppendCallbackInvocation(closedShape, callbackName, parameters, "            "));
        if (!shape.IsStamp && !closedShape.HasEntity)
        {
            lines.AddRange(GeneratorTemplates.Indexed(closedShape.ComponentModels.Length,
                index => $"        {rowNames[index]} = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref {rowNames[index]}, 1);"));
            lines.Add($"        {indexName}++;");
        }
        lines.Add("        }");
        lines.Add("    }");
        lines.Add("}");
        return string.Join("\n", lines);
    }

    private static string RenderInterceptedParallelInvoker(IterationModel shape, InterceptionSite site)
    {
        string name = "InterceptedParallelInvoker_" + site.Id;
        string[] parameters = InterceptedParameterNames(site);
        string callbackName = "InvokeInterceptedCallback_" + site.Id;
        string countName = GeneratedLocalName(site, "count", 0);
        string indexName = GeneratedLocalName(site, "index", 0);
        string[] rowNames = shape.IsStamp
            ? Array.Empty<string>()
            : GeneratorTemplates.Indexed(shape.ComponentModels.Length, index => GeneratedLocalName(site, "row", index)).ToArray();
        var fields = new List<string>();
        if (shape.HasContext)
        {
            fields.Add($"    private {InterceptedContextType(shape)} _context;");
        }
        fields.AddRange(GeneratorTemplates.Indexed(shape.ComponentModels.Length, index => $"    private readonly int _access{index};"));
        var constructorParameters = new List<string>();
        if (shape.HasContext)
        {
            constructorParameters.Add(InterceptedContextType(shape) + " context");
        }
        string accessParameters = shape.Api.Signature.AccessParameters(tokens: true);
        if (accessParameters.Length != 0)
        {
            constructorParameters.Add(accessParameters);
        }
        var constructorAssignments = new List<string>();
        if (shape.HasContext)
        {
            constructorAssignments.Add("        _context = context;");
        }
        constructorAssignments.AddRange(GeneratorTemplates.Indexed(shape.ComponentModels.Length, index =>
            $"        _access{index} = GeneratedForEachRuntime.Get{(shape.IsStamp || !shape.ComponentModels[index].IsWrite ? "Read" : "Write")}QueryComponentIndex(access{index});"));
        var body = new List<string>();
        if (shape.HasContext)
        {
            body.Add(shape.ContextMode switch
            {
                ContextModeKind.Value => $"        {InterceptedContextType(shape)} {parameters[0]} = _context;",
                ContextModeKind.Ref => $"        ref {InterceptedContextType(shape)} {parameters[0]} = ref _context;",
                _ => $"        ref readonly {InterceptedContextType(shape)} {parameters[0]} = ref _context;",
            });
        }
        if (!shape.IsStamp)
        {
            body.AddRange(GeneratorTemplates.Indexed(shape.ComponentModels.Length, index =>
                $"        ref {shape.ComponentModels[index].ResolvedTypeName} {rowNames[index]} = ref slots.GetGeneratedReadReference<{shape.ComponentModels[index].ResolvedTypeName}>(_access{index});"));
        }
        body.Add($"        int {countName} = slots.Count;");
        body.Add($"        for (int {indexName} = 0; {indexName} < {countName}; {indexName}++)");
        body.Add("        {");
        int parameterIndex = shape.HasContext ? 1 : 0;
        if (shape.HasEntity)
        {
            body.Add($"            global::Delta.ECS.Entity {parameters[parameterIndex++]} = slots.EntityAt({indexName});");
        }
        body.AddRange(GeneratorTemplates.Indexed(shape.ComponentModels.Length, index => shape.IsStamp
            ? $"            Stamp {parameters[parameterIndex + index]} = slots.GetGeneratedStamp(_access{index}, {indexName});"
            : $"            {(shape.ComponentModels[index].IsWrite ? "ref " : "ref readonly ")}{shape.ComponentModels[index].ResolvedTypeName} {parameters[parameterIndex + index]} = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref {rowNames[index]}, {indexName});"));
        body.Add(CanInlineInterceptedLambda(site)
            ? AppendInterceptedLambdaBody(site, "            ")
            : AppendCallbackInvocation(shape, callbackName, parameters, "            "));
        body.Add("        }");
        string members = string.Join("\n", new[]
        {
            string.Join("\n", fields),
            $$"""
                internal {{name}}({{string.Join(", ", constructorParameters)}})
                {
                {{GeneratorTemplates.Indent(string.Join("\n", constructorAssignments), "    ")}}
                }
            """.Trim(),
            $"    public bool RequiresSingleThread => {(shape.ContextMode == ContextModeKind.Ref ? "true" : "false")};",
            "    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]",
            "    public void Invoke(ref GeneratedQuerySlots slots)",
            "    {",
            string.Join("\n", body),
            "    }",
            shape.HasContext ? $"    internal {InterceptedContextType(shape)} Context => _context;" : string.Empty,
        }.Where(static value => !string.IsNullOrEmpty(value)));
        return GeneratorTemplates.RenderBlock($"private struct {name} : IGeneratedParallelInvoker", members);
    }

    private static string AppendCallbackInvocation(
        IterationModel shape,
        string target,
        string[] parameters,
        string indent)
    {
        var invocationArguments = new List<string>();
        int parameterIndex = 0;
        if (shape.HasContext)
        {
            invocationArguments.Add(SignatureProjection.ContextArgument(shape.ContextMode, parameters[parameterIndex++]));
        }

        if (shape.HasEntity)
        {
            invocationArguments.Add(parameters[parameterIndex++]);
        }
        invocationArguments.AddRange(Enumerable.Range(0, shape.ComponentModels.Length)
            .Select(index => shape.Api.Signature.ComponentArgument(index, parameters[parameterIndex + index])));
        return indent + target + "(" + string.Join(", ", invocationArguments) + ");";
    }

    private static string RenderInterceptedParallelClosedMethod(IterationModel shape, InterceptionSite site)
    {
        IterationModel accessShape = new(
            shape.RegistrationBinding,
            shape.HasEntity,
            shape.HasContext,
            isFunctor: true,
            shape.Pattern,
            shape.Components,
            functorType: null,
            contextType: shape.ContextType,
            parallel: shape.Parallel,
            contextMode: shape.ContextMode,
            methodName: shape.MethodName,
            hasEntityTarget: shape.HasEntityTarget,
            hasQuery: true,
            isStamp: shape.IsStamp,
            typeBinding: TypeBindingKind.CallbackInferred);
        string[] parameters = InterceptedParameterNames(site);
        string methodName = "ExecuteInterceptedClosed_" + site.Id;
        string invokerType = "InterceptedParallelInvoker_" + site.Id;
        SignatureProjection slots = shape.Api.Signature;
        string componentParameters = slots.HasExplicitIds ? ", " + slots.ComponentIdParameters("componentId") : string.Empty;
        string contextParameter = shape.HasContext
            ? ", " + SignatureProjection.ContextParameter(shape.ContextMode, InterceptedContextType(shape), parameters[0])
            : string.Empty;
        string target = shape.HasEntityTarget ? ", global::System.ReadOnlySpan<global::Delta.ECS.Entity> entities" : string.Empty;
        string signature = $"private static void {methodName}(global::Delta.ECS.World world{target}, in global::Delta.ECS.Query query{componentParameters}{contextParameter}{(shape.Parallel ? ", int workerCount" : string.Empty)})";
        string constructorArguments = string.Join(", ", new[]
        {
            shape.HasContext ? parameters[0] : null,
            slots.AccessArguments(),
        }.Where(static value => !string.IsNullOrEmpty(value)));
        string execute = shape.HasEntityTarget
            ? $"GeneratedForEachRuntime.ExecuteEntityList{(shape.Parallel ? "Parallel" : string.Empty)}(world, in query, entities, ref invoker, {AppendParallelWriteIndices(accessShape)}{(shape.Parallel ? ", workerCount" : string.Empty)});"
            : $"GeneratedForEachRuntime.ExecuteParallelDense(world, in query, ref invoker, {AppendParallelWriteIndices(accessShape)}, workerCount);";
        string body = $$"""
                {{GeneratorTemplates.Indent(AccessSetup(accessShape).TrimEnd(), "    ")}}
                var invoker = new {{invokerType}}({{constructorArguments}});
                {{execute}}
                {{(shape.HasContext && shape.ContextMode == ContextModeKind.Ref ? parameters[0] + " = invoker.Context;" : string.Empty)}}
            """;
        string declaration = $$"""
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            {{signature}}
            """.Trim();
        return GeneratorTemplates.RenderBlock(declaration, body);
    }

    private static string[] InterceptedParameterNames(InterceptionSite site)
    {
        return site.Binding.LambdaParameterNames;
    }

    private static string RenderInterceptor(IterationModel shape, InterceptionSite site)
    {
        SignatureProjection slots = shape.Api.Signature;
        var parameters = new List<string> { "this global::Delta.ECS.World world" };
        if (shape.HasEntityTarget)
        {
            parameters.Add("global::System.ReadOnlySpan<global::Delta.ECS.Entity> entities");
        }

        if (shape.HasQuery)
        {
            parameters.Add("in global::Delta.ECS.Query query");
        }
        if (slots.HasExplicitIds)
        {
            parameters.Add(slots.ComponentIdParameters());
        }
        if (shape.HasContext)
        {
            parameters.Add(SignatureProjection.ContextParameter(shape.ContextMode, InterceptedContextType(shape), "context"));
        }

        parameters.Add("global::Delta.ECS." + ConcreteActionType(shape) + " _");
        if (shape.Parallel)
        {
            parameters.Add("int workerCount = 0");
        }
        string query = shape.HasQuery
            ? string.Empty
            : slots.HasExplicitIds
                ? $$"""
                    global::Delta.ECS.Query query = world.WhereAll(stackalloc global::Delta.ECS.ComponentId[]
                    {
                        {{slots.ComponentIdArguments()}}
                    });
                """
                : $$"""
                    global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> components = {{GeneratorTemplates.PrimaryComponentIds("world", shape.Components)}};
                    global::Delta.ECS.Query query = world.WhereAll(components);
                """;
        var invocation = new List<string> { "world" };
        if (shape.HasEntityTarget)
        {
            invocation.Add("entities");
        }
        invocation.Add("in query");
        if (slots.HasExplicitIds)
        {
            invocation.Add(slots.ComponentIdArguments());
        }

        if (shape.HasContext)
        {
            invocation.Add(SignatureProjection.ContextArgument(shape.ContextMode, "context"));
        }

        if (shape.Parallel)
        {
            invocation.Add("workerCount");
        }
        string body = query + "        ExecuteInterceptedClosed_" + site.Id + "(" + string.Join(", ", invocation) + ");";
        string declaration = $$"""
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            {{site.Attribute}}
            internal static void Intercept_{{site.Id}}({{string.Join(", ", parameters)}})
            """.Trim();
        return GeneratorTemplates.Indent(GeneratorTemplates.RenderBlock(declaration, body), "    ");
    }

    private static string ConcreteActionType(IterationModel shape)
    {
        SignatureProjection slots = shape.Api.Signature;
        string suffix = IsAllWrite(shape.ComponentModels) ? string.Empty : "_" + shape.Pattern;
        string generic = shape.IsStamp
            ? string.Join(", ", Enumerable.Repeat("global::Delta.ECS.Stamp", shape.Components.Length))
            : string.Join(", ", shape.Components);
        if (shape.HasContext)
        {
            generic = SignatureProjection.JoinGeneric(InterceptedContextType(shape), generic);
            return SignatureProjection.TypeWithArguments(
                (shape.HasEntity ? "ForEachContextEntityAction" : "ForEachContextAction") + ContextDelegateSuffix(shape.ContextMode) + suffix,
                generic);
        }

        return SignatureProjection.TypeWithArguments(
            (shape.HasEntity ? "ForEachEntityAction" : "ForEachAction") + suffix,
            generic);
    }

    private static string InterceptedContextType(IterationModel shape)
        => shape.ContextType ?? "global::System.Object";

    private static string RenderClosedDenseMethod(
        IterationModel shape,
        string methodName,
        string componentParameters)
    {
        SignatureProjection slots = shape.Api.Signature;
        string generic = slots.HasGenericSelectors ? slots.GenericList() : string.Empty;
        string genericPrefix = StateGeneric(shape, generic);
        string contextParameter = shape.HasContext
            ? ", " + SignatureProjection.ContextParameter(shape.ContextMode, ContextType(shape), "context")
            : string.Empty;
        string callbackParameter = shape.IsFunctor
            ? ", ref " + shape.FunctorType + " functor"
            : ", " + ActionType(shape) + " action";
        string target = shape.HasEntityTarget ? ", global::System.ReadOnlySpan<Entity> entities, in Query query" : ", in Query query";
        string signature = $"private static void {methodName}{genericPrefix}(World world{target}{componentParameters}{contextParameter}{callbackParameter})";
        var lines = new List<string>
        {
            "[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]",
            signature,
            "{",
            GeneratorTemplates.Indent(AccessSetup(shape).TrimEnd(), "    "),
        };
        if (shape.HasEntityTarget)
        {
            string invokerType = ParallelInvokerName(shape) + StateGeneric(shape, generic);
            string arguments = string.Join(", ", new[]
            {
                shape.HasContext ? "context" : null,
                shape.IsFunctor ? "functor" : "action",
                slots.AccessArguments(),
            }.Where(static value => !string.IsNullOrEmpty(value)));
            lines.Add($"    var invoker = new {invokerType}({arguments});");
            lines.Add($"    GeneratedForEachRuntime.ExecuteEntityList(world, in query, entities, ref invoker, {AppendParallelWriteIndices(shape)});");
            if (shape.HasContext && shape.ContextMode == ContextModeKind.Ref)
            {
                lines.Add("    context = invoker.Context;");
            }

            if (shape.IsFunctor)
            {
                lines.Add("    functor = invoker.Functor;");
            }
            lines.Add("}");
            return GeneratorTemplates.Indent(string.Join("\n", lines), "    ");
        }

        if (shape.IsStamp)
        {
            lines.Add("    using var execution = GeneratedForEachRuntime.OpenReadDense(world, in query);");
        }
        else
        {
            lines.Add($"    using var execution = GeneratedForEachRuntime.{(shape.ComponentModels.Any(static component => component.IsWrite) ? "OpenWriteDense" : "OpenReadDense")}(world, in query);");
            lines.AddRange(SplitLines(AppendQueryComponentRoutes(shape, "    ")));
            lines.AddRange(SplitLines(AppendArchetypeWriteSetup(shape, "    ")));
        }
        lines.Add(shape.IsStamp || shape.HasEntity
            ? "    while (execution.MoveNextTrusted(out var slots))"
            : "    while (execution.MoveNextTrusted(out var componentRows, out int count))");
        lines.Add("    {");
        if (shape.IsStamp || shape.HasEntity)
        {
            lines.Add("        int count = slots.Count;");
        }
        for (int index = 0; index < shape.ComponentModels.Length; index++)
        {
            if (shape.IsStamp)
            {
                continue;
            }
            string type = ComponentType(shape, index);
            string row = $"row{index}";
            lines.Add(shape.HasEntity
                ? $"        ref {type} {row} = ref slots.GetGenerated{(shape.ComponentModels[index].IsWrite ? "Write" : "Read")}Reference<{type}>(access{index});"
                : $"        ref {type} {row} = ref GeneratedForEachRuntime.GetGeneratedRow<{type}>(componentRows, route{index});");
        }
        lines.Add("        for (int index = 0; index < count; index++)");
        lines.Add("        {");
        if (shape.HasEntity)
        {
            lines.Add("            Entity entity = slots.EntityAt(index);");
        }
        for (int index = 0; index < shape.ComponentModels.Length; index++)
        {
            string type = ComponentType(shape, index);
            lines.Add(shape.IsStamp
                ? $"            Stamp component{index} = slots.GetGeneratedStamp(access{index}, index);"
                : $"            {(shape.ComponentModels[index].IsWrite ? "ref " : "ref readonly ")}{type} component{index} = ref global::System.Runtime.CompilerServices.Unsafe.Add(ref row{index}, index);");
        }
        lines.Add("            " + AppendClosedInvocation(shape, "action", "functor", "context", "component", "entity") + ";");
        lines.Add("        }");
        lines.Add("    }");
        lines.Add("}");
        return GeneratorTemplates.Indent(string.Join("\n", lines), "    ");
    }

    private static string[] SplitLines(string text)
        => string.IsNullOrEmpty(text) ? Array.Empty<string>() : text.TrimEnd().Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);

    private static string RenderExtensionMethod(
        IterationModel shape,
        string prefix,
        string query,
        string contextParameter,
        string ids,
        string callback,
        string genericPrefix,
        string className,
        bool profiling,
        string closedMethodName)
    {
        string componentPart = string.IsNullOrEmpty(ids) ? string.Empty : $", {ids}";
        string methodName = shape.MethodName;
        string profileName = className + "." + methodName;
        string callbackName = shape.IsFunctor ? "functor" : "action";
        string callbackParameter = shape.IsFunctor
            ? ", ref " + shape.FunctorType + " " + callbackName
            : ", " + callback + " " + callbackName;
        string workerCountParameter = shape.Parallel ? ", int workerCount = 0" : string.Empty;
        string visibility = shape.IsFunctor || shape.ImplicitComponents ? "internal" : "public";
        string signature = $"{visibility} static void {methodName}{genericPrefix}({prefix}{query}{componentPart}{contextParameter}{callbackParameter}{workerCountParameter})";
        string body = BuildBody(
            shape,
            profiling,
            StableProfileMethodId(profileName),
            closedMethodName);
        return GeneratorTemplates.Indent(
            RenderMethod(
                GeneratorTemplates.Documentation(shape.Api),
                signature,
                body,
                profiling ? profileName : null),
            "    ");
    }

    private static string BuildBody(
        IterationModel shape,
        bool profiling,
        int methodId,
        string closedMethodName)
    {
        SignatureProjection slots = shape.Api.Signature;
        var closedArguments = new List<string>(shape.HasEntityTarget
            ? new[] { "world", "entities", "in query" }
            : new[] { "world", "in query" });
        if (slots.HasExplicitIds)
        {
            closedArguments.Add(slots.ComponentIdArguments());
        }

        if (shape.HasContext)
        {
            closedArguments.Add(SignatureProjection.ContextArgument(shape.ContextMode, "context"));
        }

        closedArguments.Add(shape.IsFunctor ? "ref functor" : "action");
        if (shape.Parallel)
        {
            closedArguments.Add("workerCount");
        }

        string invoke = closedMethodName + StateGeneric(shape, slots.HasGenericSelectors ? slots.GenericList() : string.Empty)
            + "(" + string.Join(", ", closedArguments) + ");";
        var lines = new List<string> { "{" };
        if (!shape.HasQuery)
        {
            if (slots.HasExplicitIds)
            {
                lines.Add($"    Query query = world.WhereAll(stackalloc ComponentId[] {{ {slots.ComponentIdArguments()} }});");
            }
            else
            {
                string components = GeneratorTemplates.PrimaryComponentIds(
                    "world",
                    GeneratorTemplates.Indexed(shape.ComponentModels.Length, index => ComponentType(shape, index)).ToArray());
                lines.Add($"    global::System.ReadOnlySpan<ComponentId> components = {components};");
                lines.Add("    Query query = world.WhereAll(components);");
            }
        }
        string indent = "    ";
        if (profiling)
        {
            lines.Add($"    global::DeltaECS.Profiling.ProfilerRuntime.Enter({methodId});");
            lines.Add("    try");
            lines.Add("    {");
            indent = "        ";
        }
        if (!shape.IsFunctor)
        {
            lines.Add(indent + "global::Delta.ECS.GeneratedForEachRuntime.ThrowIfNull(action, nameof(action));");
        }

        lines.Add(indent + invoke);
        if (profiling)
        {
            lines.Add("    }");
            lines.Add("    finally");
            lines.Add("    {");
            lines.Add($"        global::DeltaECS.Profiling.ProfilerRuntime.Leave({methodId});");
            lines.Add("    }");
        }
        lines.Add("}");
        return string.Join("\n", lines);
    }

    private static string RenderMethod(string documentation, string signature, string body, string? profileName)
    {
        string profile = profileName is null
            ? string.Empty
            : $$"""
                [global::DeltaECS.Profiling.ProfiledMethodMetadataAttribute({{StableProfileMethodId(profileName)}}, "{{profileName}}")]
                """.TrimEnd();
        return $$"""
            {{documentation}}
            {{profile}}
            [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            {{signature}}
            {{GeneratorTemplates.Indent(body, "    ")}}
            """.TrimEnd();
    }

    private static string AppendArchetypeWriteSetup(IterationModel shape, string indent)
    {
        int writeCount = shape.ComponentModels.Count(static component => component.IsWrite);
        if (writeCount > 1)
        {
            string routes = string.Join(", ", GeneratorTemplates.WriteIndices(shape.ComponentModels).Select(index => "route" + index));
            return $$"""
                {{indent}}var stampWriter = new {{ArchetypeStampWriterName(shape)}}({{routes}});
                {{indent}}execution.MarkArchetypeWrites(ref stampWriter);
                """.TrimEnd();
        }

        return string.Join("\n", GeneratorTemplates.WriteIndices(shape.ComponentModels)
            .Select(index => $"{indent}execution.MarkArchetypeWrite(route{index});"));
    }

    private static string AppendQueryComponentRoutes(IterationModel shape, string indent)
    {
        SignatureProjection slots = shape.Api.Signature;
        if (!shape.HasEntity && !slots.HasExplicitIds)
        {
            return string.Empty;
        }

        return string.Join("\n", GeneratorTemplates.Indexed(
            shape.ComponentModels.Length,
            index => !shape.HasEntity || shape.ComponentModels[index].IsWrite,
            index => $"{indent}int route{index} = GeneratedForEachRuntime.Get{(shape.ComponentModels[index].IsWrite ? "Write" : "Read")}QueryComponentIndex(access{index});"
            ));
    }

    private static string AccessSetup(IterationModel shape)
    {
        SignatureProjection slots = shape.Api.Signature;
        return string.Join("\n", GeneratorTemplates.Indexed(shape.ComponentModels.Length, index =>
        {
            bool routeOnly = !shape.HasEntity
                && !shape.HasEntityTarget
                && !slots.HasExplicitIds
                && !shape.Parallel;
            string componentType = ComponentType(shape, index);
            if (shape.IsStamp)
            {
                return slots.HasExplicitIds
                    ? $"var access{index} = GeneratedForEachRuntime.GetPreparedStampAccess(in query, {slots.ComponentIdArgument(index, "componentId")});"
                    : $"var access{index} = GeneratedForEachRuntime.GetPreparedStampAccess<{componentType}> (in query);";
            }
            string variable = (routeOnly ? "int route" : "var access") + index;
            string accessKind = shape.ComponentModels[index].IsWrite ? "Write" : "Read";
            string method = routeOnly ? "GetPrepared" + accessKind + "Route" : "GetPrepared" + accessKind + "Access";
            string generic = !slots.HasExplicitIds || routeOnly ? $"<{componentType}>" : string.Empty;
            string arguments = string.Join(", ", new[]
            {
                "in query",
                slots.HasExplicitIds ? slots.ComponentIdArgument(index, "componentId") : null,
                !slots.HasExplicitIds || routeOnly ? null : $"typeof({componentType})",
            }.Where(static value => !string.IsNullOrEmpty(value)));
            return $"{variable} = GeneratedForEachRuntime.{method}{generic}({arguments});";
        }));
    }

    private static string ActionType(IterationModel shape)
    {
        SignatureProjection slots = shape.Api.Signature;
        string generic = shape.IsStamp
            ? string.Join(", ", Enumerable.Repeat("Stamp", shape.Components.Length))
            : slots.HasGenericSelectors
                ? slots.GenericList()
                : string.Join(", ", shape.ComponentModels.Select(static component => component.ResolvedTypeName));
        string suffix = IsAllWrite(shape.ComponentModels) ? string.Empty : "_" + shape.Pattern;
        if (shape.HasContext)
        {
            string contextSuffix = ContextDelegateSuffix(shape.ContextMode);
            return SignatureProjection.TypeWithArguments(
                (shape.HasEntity ? "ForEachContextEntityAction" : "ForEachContextAction") + contextSuffix + suffix,
                SignatureProjection.JoinGeneric(shape.IsFunctor || !slots.HasGenericSelectors ? ContextType(shape) : "TContext", generic));
        }

        return SignatureProjection.TypeWithArguments(shape.HasEntity ? "ForEachEntityAction" + suffix : "ForEachAction" + suffix, generic);
    }

    private static string ContextDelegateSuffix(ContextModeKind mode) => mode == ContextModeKind.In ? "_In" : mode == ContextModeKind.RefReadonly ? "_RefReadonly" : mode == ContextModeKind.Value ? "_Value" : string.Empty;

    private static string StateGeneric(IterationModel shape, string generic)
        => !shape.Api.Signature.HasGenericSelectors
            ? string.Empty
            : SignatureProjection.TypeArguments(shape.IsFunctor
                ? generic
                : shape.HasContext ? SignatureProjection.JoinGeneric("TContext", generic) : generic);

    private static string ParallelInvokerName(IterationModel shape) => "DemandForEachParallelInvoker_" + GeneratorSupport.StableName(shape.Key);
    private static string ArchetypeStampWriterName(IterationModel shape) => "DemandForEachArchetypeStampWriter_" + GeneratorSupport.StableName(shape.Key);

    private static string ComponentType(IterationModel shape, int index) => shape.ComponentModels[index].TypeName;

    private static string CallbackComponentType(IterationModel shape, int index) => shape.IsStamp ? "global::Delta.ECS.Stamp" : shape.ComponentModels[index].ResolvedTypeName;

    private static string ContextType(IterationModel shape) => shape.IsFunctor || shape.ImplicitComponents
            ? shape.ContextType ?? "TContext"
            : "TContext";

    private static string ConstructorName(string name)
    {
        int index = name.IndexOf('<');
        return index < 0 ? name : name.Substring(0, index);
    }

    private static bool IsAllWrite(IReadOnlyList<ComponentModel> components)
        => components.All(static component => component.IsWrite);


}
