namespace Delta.ECS.Generators;

/// <summary>Template for a complete generated source file.</summary>
internal static partial class GeneratorTemplates
{
    internal static string FileTemplate(GeneratedFileModel model)
    {
        string usings = model.Usings.IsDefaultOrEmpty
            ? string.Empty
            : string.Join("\n", model.Usings) + "\n";
        string members = model.Members.IsDefaultOrEmpty
            ? string.Empty
            : string.Join("\n", model.Members) + "\n";
        return GeneratedSourceFormatter.Format($$"""
            // <auto-generated />
            #nullable enable
            {{usings}}namespace {{model.Namespace}}
            {
            {{members}}}
            """);
    }
}
