using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Delta.ECS.Generators;

[Generator]
public sealed class ForEachGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("ForEach.g.cs", SourceText.From(Render(), Encoding.UTF8)));
    }

    private static string Render()
    {
        var source = new StringBuilder(128 * 1024);
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("namespace Delta.ECS;");
        source.AppendLine();
        RenderContracts(source);
        RenderStates(source);
        RenderWorld(source);
        return source.ToString();
    }

    private static void RenderContracts(StringBuilder source)
    {
        source.AppendLine("public readonly struct ForEachEntityTag");
        source.AppendLine("{");
        source.AppendLine("    public static ForEachEntityTag Instance => default;");
        source.AppendLine("}");
        source.AppendLine("public delegate void ForEachEntityAction(Entity entity);");
        source.AppendLine("public delegate void ForEachAction();");
        source.AppendLine("public delegate void ForEachContextAction<TContext>(ref TContext context);");
        source.AppendLine("public delegate void ForEachContextEntityAction<TContext>(ref TContext context, Entity entity);");
        source.AppendLine("public interface IForEachEntity { void Invoke(Entity entity); }");
        source.AppendLine("public interface IForEach { void Invoke(); }");
        source.AppendLine("public interface IForEachContext<TContext> { void Invoke(ref TContext context); }");
        source.AppendLine("public interface IForEachContextEntity<TContext> { void Invoke(ref TContext context, Entity entity); }");
        source.AppendLine();

        for (int arity = 1; arity <= 4; arity++)
        {
            var generic = GenericTypes(arity);
            var refs = RefParameters(arity);
            source.Append("public delegate void ForEachAction<").Append(generic).Append(">(")
                .Append(refs).AppendLine(");");
            source.Append("public delegate void ForEachEntityAction<").Append(generic).Append(">(Entity entity, ")
                .Append(refs).AppendLine(");");
            source.Append("public delegate void ForEachContextAction<TContext, ").Append(generic).Append(">(ref TContext context, ")
                .Append(refs).AppendLine(");");
            source.Append("public delegate void ForEachContextEntityAction<TContext, ").Append(generic).Append(">(ref TContext context, Entity entity, ")
                .Append(refs).AppendLine(");");
            source.Append("public interface IForEach<").Append(generic).Append("> { void Invoke(")
                .Append(refs).AppendLine("); }");
            source.Append("public interface IForEachEntity<").Append(generic).Append("> { void Invoke(Entity entity, ")
                .Append(refs).AppendLine("); }");
            source.Append("public interface IForEachContext<TContext, ").Append(generic).Append("> { void Invoke(ref TContext context, ")
                .Append(refs).AppendLine("); }");
            source.Append("public interface IForEachContextEntity<TContext, ").Append(generic).Append("> { void Invoke(ref TContext context, Entity entity, ")
                .Append(refs).AppendLine("); }");
            source.AppendLine();
        }
    }

    private static void RenderStates(StringBuilder source)
    {
        RenderZeroStates(source);
        for (int arity = 1; arity <= 4; arity++)
        {
            var generic = GenericTypes(arity);
            var accesses = AccessParameters(arity);
            var values = ValueStatements(arity);
            RenderState(source, $"ForEachDelegateState<{generic}>", $"ForEachAction<{generic}> action, {accesses}", $"_action = action; {AssignAccessFields(arity)}", $"_action({values});", $"ForEachAction<{generic}>");
            RenderState(source, $"ForEachEntityDelegateState<{generic}>", $"ForEachEntityAction<{generic}> action, {accesses}", $"_action = action; {AssignAccessFields(arity)}", $"_action(cursor.Entities[cursor.CurrentIndex], {values});", $"ForEachEntityAction<{generic}>");
            RenderState(source, $"ForEachContextDelegateState<TContext, {generic}>", $"TContext context, ForEachContextAction<TContext, {generic}> action, {accesses}", $"Context = context; _action = action; {AssignAccessFields(arity)}", $"_action(ref Context, {values});", $"ForEachContextAction<TContext, {generic}>", "TContext");
            RenderState(source, $"ForEachContextEntityDelegateState<TContext, {generic}>", $"TContext context, ForEachContextEntityAction<TContext, {generic}> action, {accesses}", $"Context = context; _action = action; {AssignAccessFields(arity)}", $"_action(ref Context, cursor.Entities[cursor.CurrentIndex], {values});", $"ForEachContextEntityAction<TContext, {generic}>", "TContext");
            RenderState(source, $"ForEachFunctorState<TFunctor, {generic}>", $"TFunctor functor, {accesses}", $"Functor = functor; {AssignAccessFields(arity)}", $"Functor.Invoke({values});", null, "TFunctor", $"IForEach<{generic}>");
            RenderState(source, $"ForEachEntityFunctorState<TFunctor, {generic}>", $"TFunctor functor, {accesses}", $"Functor = functor; {AssignAccessFields(arity)}", $"Functor.Invoke(cursor.Entities[cursor.CurrentIndex], {values});", null, "TFunctor", $"IForEachEntity<{generic}>");
            RenderState(source, $"ForEachContextFunctorState<TContext, TFunctor, {generic}>", $"TContext context, TFunctor functor, {accesses}", $"Context = context; Functor = functor; {AssignAccessFields(arity)}", $"Functor.Invoke(ref Context, {values});", null, "TContext, TFunctor", $"IForEachContext<TContext, {generic}>");
            RenderState(source, $"ForEachContextEntityFunctorState<TContext, TFunctor, {generic}>", $"TContext context, TFunctor functor, {accesses}", $"Context = context; Functor = functor; {AssignAccessFields(arity)}", $"Functor.Invoke(ref Context, cursor.Entities[cursor.CurrentIndex], {values});", null, "TContext, TFunctor", $"IForEachContextEntity<TContext, {generic}>");
        }
    }

    private static void RenderZeroStates(StringBuilder source)
    {
        source.AppendLine("internal struct ForEachDelegateState : IForEachInvoker");
        source.AppendLine("{");
        source.AppendLine("    private readonly ForEachAction _action;");
        source.AppendLine("    internal ForEachDelegateState(ForEachAction action) => _action = action;");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) _action(); }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("internal struct ForEachContextDelegateState<TContext> : IForEachInvoker");
        source.AppendLine("{");
        source.AppendLine("    internal TContext Context;");
        source.AppendLine("    private readonly ForEachContextAction<TContext> _action;");
        source.AppendLine("    internal ForEachContextDelegateState(TContext context, ForEachContextAction<TContext> action) { Context = context; _action = action; }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) _action(ref Context); }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("internal struct ForEachEntityDelegateState : IForEachInvoker");
        source.AppendLine("{");
        source.AppendLine("    private readonly ForEachEntityAction _action;");
        source.AppendLine("    internal ForEachEntityDelegateState(ForEachEntityAction action) => _action = action;");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) _action(cursor.Entities[cursor.CurrentIndex]); }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("internal struct ForEachContextEntityDelegateState<TContext> : IForEachInvoker");
        source.AppendLine("{");
        source.AppendLine("    internal TContext Context;");
        source.AppendLine("    private readonly ForEachContextEntityAction<TContext> _action;");
        source.AppendLine("    internal ForEachContextEntityDelegateState(TContext context, ForEachContextEntityAction<TContext> action) { Context = context; _action = action; }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) _action(ref Context, cursor.Entities[cursor.CurrentIndex]); }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("internal struct ForEachEntityFunctorState<TFunctor> : IForEachInvoker where TFunctor : struct, IForEachEntity");
        source.AppendLine("{");
        source.AppendLine("    internal TFunctor Functor;");
        source.AppendLine("    internal ForEachEntityFunctorState(TFunctor functor) => Functor = functor;");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) Functor.Invoke(cursor.Entities[cursor.CurrentIndex]); }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("internal struct ForEachFunctorState<TFunctor> : IForEachInvoker where TFunctor : struct, IForEach");
        source.AppendLine("{");
        source.AppendLine("    internal TFunctor Functor;");
        source.AppendLine("    internal ForEachFunctorState(TFunctor functor) => Functor = functor;");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) Functor.Invoke(); }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("internal struct ForEachContextFunctorState<TContext, TFunctor> : IForEachInvoker where TFunctor : struct, IForEachContext<TContext>");
        source.AppendLine("{");
        source.AppendLine("    internal TContext Context;");
        source.AppendLine("    internal TFunctor Functor;");
        source.AppendLine("    internal ForEachContextFunctorState(TContext context, TFunctor functor) { Context = context; Functor = functor; }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) Functor.Invoke(ref Context); }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("internal struct ForEachContextEntityFunctorState<TContext, TFunctor> : IForEachInvoker where TFunctor : struct, IForEachContextEntity<TContext>");
        source.AppendLine("{");
        source.AppendLine("    internal TContext Context;");
        source.AppendLine("    internal TFunctor Functor;");
        source.AppendLine("    internal ForEachContextEntityFunctorState(TContext context, TFunctor functor) { Context = context; Functor = functor; }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) Functor.Invoke(ref Context, cursor.Entities[cursor.CurrentIndex]); }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void RenderState(StringBuilder source, string name, string constructorParameters, string constructorBody, string invocation, string? actionType = null, string? stateTypes = null, string? interfaceType = null)
    {
        source.Append("internal struct ").Append(name).Append(" : IForEachInvoker");
        if (interfaceType is not null)
        {
            source.Append(" where TFunctor : struct, ").Append(interfaceType);
        }

        source.AppendLine();
        source.AppendLine("{");
        if (stateTypes is not null)
        {
            if (stateTypes.Contains("TContext", StringComparison.Ordinal))
            {
                source.AppendLine("    internal TContext Context;");
            }

            if (stateTypes.Contains("TFunctor", StringComparison.Ordinal))
            {
                source.AppendLine("    internal TFunctor Functor;");
            }
        }

        if (actionType is not null)
        {
            source.Append("    private readonly ").Append(actionType).AppendLine(" _action;");
        }
        var count = constructorParameters.Split(new[] { "WriteAccess" }, StringSplitOptions.None).Length - 1;
        for (int index = 1; index <= count; index++)
        {
            source.Append("    private readonly WriteAccess _component").Append(index).AppendLine(";");
        }

        source.Append("    internal ").Append(ConstructorName(name)).Append('(').Append(constructorParameters).Append(") { ").Append(constructorBody).AppendLine(" }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor)");
        source.AppendLine("    {");
        for (int index = 1; index <= count; index++)
        {
            source.Append("        var value").Append(index).Append(" = cursor.GetWrite(_component").Append(index).AppendLine(");");
        }

        source.AppendLine("        while (cursor.MoveNext())");
        source.AppendLine("        {");
        source.Append("            ").AppendLine(invocation);
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void RenderWorld(StringBuilder source)
    {
        source.AppendLine("public sealed partial class World");
        source.AppendLine("{");
        Append(source, "public void ForEach(in Query query, ForEachAction action)", "ArgumentNullException.ThrowIfNull(action); var state = new ForEachDelegateState(action); ForEachRuntime.Execute(this, in query, ref state);");
        Append(source, "public void ForEach<TContext>(in Query query, ref TContext context, ForEachContextAction<TContext> action)", "ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextDelegateState<TContext>(context, action); ForEachRuntime.Execute(this, in query, ref state); context = state.Context;");
        Append(source, "public void ForEach(in Query query, ForEachEntityAction action)", "ArgumentNullException.ThrowIfNull(action); var state = new ForEachEntityDelegateState(action); ForEachRuntime.Execute(this, in query, ref state);");
        Append(source, "public void ForEach<TContext>(in Query query, ref TContext context, ForEachContextEntityAction<TContext> action)", "ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextEntityDelegateState<TContext>(context, action); ForEachRuntime.Execute(this, in query, ref state); context = state.Context;");
        Append(source, "public void ForEach<TFunctor>(in Query query, ref TFunctor functor, ForEachEntityTag entity)", "var state = new ForEachEntityFunctorState<TFunctor>(functor); ForEachRuntime.Execute(this, in query, ref state); functor = state.Functor;", "where TFunctor : struct, IForEachEntity");
        Append(source, "public void ForEach<TContext, TFunctor>(in Query query, ref TContext context, ref TFunctor functor, ForEachEntityTag entity)", "var state = new ForEachContextEntityFunctorState<TContext, TFunctor>(context, functor); ForEachRuntime.Execute(this, in query, ref state); context = state.Context; functor = state.Functor;", "where TFunctor : struct, IForEachContextEntity<TContext>");
        Append(source, "public void ForEach<TFunctor>(in Query query, ref TFunctor functor)", "var state = new ForEachFunctorState<TFunctor>(functor); ForEachRuntime.Execute(this, in query, ref state); functor = state.Functor;", "where TFunctor : struct, IForEach");
        Append(source, "public void ForEach<TContext, TFunctor>(in Query query, ref TContext context, ref TFunctor functor)", "var state = new ForEachContextFunctorState<TContext, TFunctor>(context, functor); ForEachRuntime.Execute(this, in query, ref state); context = state.Context; functor = state.Functor;", "where TFunctor : struct, IForEachContext<TContext>");
        for (int arity = 1; arity <= 4; arity++)
        {
            RenderDelegateOverloads(source, arity, true);
            RenderDelegateOverloads(source, arity, false);
            RenderFunctorOverloads(source, arity, true);
            RenderFunctorOverloads(source, arity, false);
        }

        source.AppendLine("}");
    }

    private static void RenderDelegateOverloads(StringBuilder source, int arity, bool explicitIds)
    {
        var generic = GenericTypes(arity);
        var parameters = explicitIds ? ComponentParameters(arity) : string.Empty;
        var suffix = explicitIds ? ", " + parameters : string.Empty;
        var setup = explicitIds ? string.Empty : ComponentSetup(arity);
        var accesses = explicitIds ? AccessArguments(arity) : AccessArgumentsFromSpan(arity);
        Append(source, $"public void ForEach<{generic}>(in Query query{suffix}, ForEachAction<{generic}> action)", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachDelegateState<{generic}>(action, {accesses}); ForEachRuntime.Execute(this, in query, ref state);");
        Append(source, $"public void ForEach<{generic}>(in Query query{suffix}, ForEachEntityAction<{generic}> action)", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachEntityDelegateState<{generic}>(action, {accesses}); ForEachRuntime.Execute(this, in query, ref state);");
        Append(source, $"public void ForEach<TContext, {generic}>(in Query query, ref TContext context{suffix}, ForEachContextAction<TContext, {generic}> action)", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextDelegateState<TContext, {generic}>(context, action, {accesses}); ForEachRuntime.Execute(this, in query, ref state); context = state.Context;");
        Append(source, $"public void ForEach<TContext, {generic}>(in Query query, ref TContext context{suffix}, ForEachContextEntityAction<TContext, {generic}> action)", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextEntityDelegateState<TContext, {generic}>(context, action, {accesses}); ForEachRuntime.Execute(this, in query, ref state); context = state.Context;");
    }

    private static void RenderFunctorOverloads(StringBuilder source, int arity, bool explicitIds)
    {
        var generic = GenericTypes(arity);
        var parameters = explicitIds ? ComponentParameters(arity) : string.Empty;
        var suffix = explicitIds ? ", " + parameters : string.Empty;
        var setup = explicitIds ? string.Empty : ComponentSetup(arity);
        var accesses = explicitIds ? AccessArguments(arity) : AccessArgumentsFromSpan(arity);
        Append(source, $"public void ForEach<TFunctor, {generic}>(in Query query{suffix}, ref TFunctor functor)", setup + $"var state = new ForEachFunctorState<TFunctor, {generic}>(functor, {accesses}); ForEachRuntime.Execute(this, in query, ref state); functor = state.Functor;", $"where TFunctor : struct, IForEach<{generic}>");
        Append(source, $"public void ForEach<TFunctor, {generic}>(in Query query{suffix}, ref TFunctor functor, ForEachEntityTag entity)", setup + $"var state = new ForEachEntityFunctorState<TFunctor, {generic}>(functor, {accesses}); ForEachRuntime.Execute(this, in query, ref state); functor = state.Functor;", $"where TFunctor : struct, IForEachEntity<{generic}>");
        Append(source, $"public void ForEach<TContext, TFunctor, {generic}>(in Query query, ref TContext context{suffix}, ref TFunctor functor)", setup + $"var state = new ForEachContextFunctorState<TContext, TFunctor, {generic}>(context, functor, {accesses}); ForEachRuntime.Execute(this, in query, ref state); context = state.Context; functor = state.Functor;", $"where TFunctor : struct, IForEachContext<TContext, {generic}>");
        Append(source, $"public void ForEach<TContext, TFunctor, {generic}>(in Query query, ref TContext context{suffix}, ref TFunctor functor, ForEachEntityTag entity)", setup + $"var state = new ForEachContextEntityFunctorState<TContext, TFunctor, {generic}>(context, functor, {accesses}); ForEachRuntime.Execute(this, in query, ref state); context = state.Context; functor = state.Functor;", $"where TFunctor : struct, IForEachContextEntity<TContext, {generic}>");
    }

    private static void Append(StringBuilder source, string signature, string body, string? constraint = null)
    {
        source.Append("    ").AppendLine(signature);
        if (constraint is not null)
        {
            source.Append("        ").AppendLine(constraint);
        }
        source.AppendLine("    {");
        foreach (var line in body.Split('\n'))
        {
            source.Append("        ").AppendLine(line);
        }
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static string GenericTypes(int arity) => string.Join(", ", TypeNames(arity, "T"));

    private static string[] TypeNames(int arity, string prefix)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = prefix + (index + 1);
        }
        return result;
    }

    private static string[] ComponentIds(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "component" + (index + 1);
        }
        return result;
    }

    private static string ComponentParameters(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "ComponentId component" + (index + 1);
        }
        return string.Join(", ", result);
    }

    private static string RefParameters(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "ref T" + (index + 1) + " component" + (index + 1);
        }
        return string.Join(", ", result);
    }

    private static string AccessParameters(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "WriteAccess component" + (index + 1);
        }
        return string.Join(", ", result);
    }

    private static string AssignAccessFields(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "_component" + (index + 1) + " = component" + (index + 1) + ";";
        }
        return string.Join(" ", result);
    }

    private static string AccessArguments(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "ForEachRuntime.AccessWrite<T" + (index + 1) + ">(this, in query, component" + (index + 1) + ")";
        }
        return string.Join(", ", result);
    }

    private static string AccessArgumentsFromSpan(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "ForEachRuntime.AccessWrite<T" + (index + 1) + ">(this, in query, componentIds[" + index + "])";
        }
        return string.Join(", ", result);
    }

    private static string ComponentSetup(int arity) => $"Span<ComponentId> componentIds = stackalloc ComponentId[{arity}]; ForEachRuntime.ResolveComponentIds(in query, componentIds); ";

    private static string AccessNames(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "access" + (index + 1);
        }
        return string.Join(", ", result);
    }

    private static string ValueStatements(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "ref value" + (index + 1) + ".Ref<T" + (index + 1) + ">(cursor)";
        }
        return string.Join(", ", result);
    }

    private static string ConstructorName(string name)
    {
        int genericStart = name.IndexOf('<');
        return genericStart < 0 ? name : name.Substring(0, genericStart);
    }
}
