using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Delta.ECS.Generators;

[Generator]
public sealed class ForEachGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("ForEach.g.cs", SourceText.From(Render(), Encoding.UTF8)));
    }

    private static string Render()
    {
        var source = new StringBuilder(512 * 1024);
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("namespace Delta.ECS;");
        source.AppendLine();
        RenderContracts(source);
        RenderStates(source);
        RenderWorld(source);
        return source.ToString();
    }

    private static void RenderContracts(StringBuilder source)
    {
        source.AppendLine("public readonly struct ForEachEntityTag");
        source.AppendLine("{");
        source.AppendLine("    public static ForEachEntityTag Instance => default;");
        source.AppendLine("}");
        source.AppendLine("public delegate void ForEachEntityAction(Entity entity);");
        source.AppendLine("public delegate void ForEachAction();");
        source.AppendLine("public delegate void ForEachContextAction<TContext>(ref TContext context);");
        source.AppendLine("public delegate void ForEachContextEntityAction<TContext>(ref TContext context, Entity entity);");
        source.AppendLine("public interface IForEachEntity { void Invoke(Entity entity); }");
        source.AppendLine("public interface IForEach { void Invoke(); }");
        source.AppendLine("public interface IForEachContext<TContext> { void Invoke(ref TContext context); }");
        source.AppendLine("public interface IForEachContextEntity<TContext> { void Invoke(ref TContext context, Entity entity); }");
        source.AppendLine();

        for (int arity = 1; arity <= 4; arity++)
        {
            int patternCount = 1 << arity;
            for (int bits = 0; bits < patternCount; bits++)
            {
                string pattern = AccessPattern(arity, bits);
                string suffix = PatternSuffix(pattern);
                string generic = GenericTypes(arity);
                string parameters = RefParameters(pattern);

                source.Append("public delegate void ForEachAction").Append(suffix).Append('<').Append(generic).Append(">(")
                    .Append(parameters).AppendLine(");");
                source.Append("public delegate void ForEachEntityAction").Append(suffix).Append('<').Append(generic).Append(">(Entity entity, ")
                    .Append(parameters).AppendLine(");");
                source.Append("public delegate void ForEachContextAction").Append(suffix).Append("<TContext, ").Append(generic).Append(">(ref TContext context, ")
                    .Append(parameters).AppendLine(");");
                source.Append("public delegate void ForEachContextEntityAction").Append(suffix).Append("<TContext, ").Append(generic).Append(">(ref TContext context, Entity entity, ")
                    .Append(parameters).AppendLine(");");
                source.Append("public interface IForEach").Append(suffix).Append('<').Append(generic).Append("> { void Invoke(")
                    .Append(parameters).AppendLine("); }");
                source.Append("public interface IForEachEntity").Append(suffix).Append('<').Append(generic).Append("> { void Invoke(Entity entity, ")
                    .Append(parameters).AppendLine("); }");
                source.Append("public interface IForEachContext").Append(suffix).Append("<TContext, ").Append(generic).Append("> { void Invoke(ref TContext context, ")
                    .Append(parameters).AppendLine("); }");
                source.Append("public interface IForEachContextEntity").Append(suffix).Append("<TContext, ").Append(generic).Append("> { void Invoke(ref TContext context, Entity entity, ")
                    .Append(parameters).AppendLine("); }");

                if (!IsAllWrite(pattern))
                {
                    source.Append("public readonly struct ForEachAccessTag_").Append(pattern).AppendLine();
                    source.AppendLine("{");
                    source.Append("    public static ForEachAccessTag_").Append(pattern).AppendLine(" Instance => default;");
                    source.AppendLine("}");
                }

                source.AppendLine();
            }
        }
    }

    private static void RenderStates(StringBuilder source)
    {
        RenderZeroStates(source);
        for (int arity = 1; arity <= 4; arity++)
        {
            int patternCount = 1 << arity;
            for (int bits = 0; bits < patternCount; bits++)
            {
                string pattern = AccessPattern(arity, bits);
                string suffix = PatternSuffix(pattern);
                string generic = GenericTypes(arity);
                string accesses = AccessParameters(pattern);
                string values = ValueStatements(pattern);

                RenderState(source, $"ForEachDelegateState{suffix}<{generic}>", pattern, $"ForEachAction{suffix}<{generic}> action, {accesses}", $"_action = action; {AssignAccessFields(arity)}", $"_action({values});", $"ForEachAction{suffix}<{generic}>");
                RenderState(source, $"ForEachEntityDelegateState{suffix}<{generic}>", pattern, $"ForEachEntityAction{suffix}<{generic}> action, {accesses}", $"_action = action; {AssignAccessFields(arity)}", $"_action(cursor.Entities[cursor.CurrentIndex], {values});", $"ForEachEntityAction{suffix}<{generic}>");
                RenderState(source, $"ForEachContextDelegateState{suffix}<TContext, {generic}>", pattern, $"TContext context, ForEachContextAction{suffix}<TContext, {generic}> action, {accesses}", $"Context = context; _action = action; {AssignAccessFields(arity)}", $"_action(ref Context, {values});", $"ForEachContextAction{suffix}<TContext, {generic}>", "TContext");
                RenderState(source, $"ForEachContextEntityDelegateState{suffix}<TContext, {generic}>", pattern, $"TContext context, ForEachContextEntityAction{suffix}<TContext, {generic}> action, {accesses}", $"Context = context; _action = action; {AssignAccessFields(arity)}", $"_action(ref Context, cursor.Entities[cursor.CurrentIndex], {values});", $"ForEachContextEntityAction{suffix}<TContext, {generic}>", "TContext");
                RenderState(source, $"ForEachFunctorState{suffix}<TFunctor, {generic}>", pattern, $"TFunctor functor, {accesses}", $"Functor = functor; {AssignAccessFields(arity)}", $"Functor.Invoke({values});", null, "TFunctor", $"IForEach{suffix}<{generic}>");
                RenderState(source, $"ForEachEntityFunctorState{suffix}<TFunctor, {generic}>", pattern, $"TFunctor functor, {accesses}", $"Functor = functor; {AssignAccessFields(arity)}", $"Functor.Invoke(cursor.Entities[cursor.CurrentIndex], {values});", null, "TFunctor", $"IForEachEntity{suffix}<{generic}>");
                RenderState(source, $"ForEachContextFunctorState{suffix}<TContext, TFunctor, {generic}>", pattern, $"TContext context, TFunctor functor, {accesses}", $"Context = context; Functor = functor; {AssignAccessFields(arity)}", $"Functor.Invoke(ref Context, {values});", null, "TContext, TFunctor", $"IForEachContext{suffix}<TContext, {generic}>");
                RenderState(source, $"ForEachContextEntityFunctorState{suffix}<TContext, TFunctor, {generic}>", pattern, $"TContext context, TFunctor functor, {accesses}", $"Context = context; Functor = functor; {AssignAccessFields(arity)}", $"Functor.Invoke(ref Context, cursor.Entities[cursor.CurrentIndex], {values});", null, "TContext, TFunctor", $"IForEachContextEntity{suffix}<TContext, {generic}>");
            }
        }
    }

    private static void RenderZeroStates(StringBuilder source)
    {
        source.AppendLine("internal struct ForEachDelegateState : IForEachInvoker");
        source.AppendLine("{");
        source.AppendLine("    private readonly ForEachAction _action;");
        source.AppendLine("    internal ForEachDelegateState(ForEachAction action) => _action = action;");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) _action(); }");
        source.AppendLine("}");
        source.AppendLine("internal struct ForEachContextDelegateState<TContext> : IForEachInvoker");
        source.AppendLine("{");
        source.AppendLine("    internal TContext Context;");
        source.AppendLine("    private readonly ForEachContextAction<TContext> _action;");
        source.AppendLine("    internal ForEachContextDelegateState(TContext context, ForEachContextAction<TContext> action) { Context = context; _action = action; }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) _action(ref Context); }");
        source.AppendLine("}");
        source.AppendLine("internal struct ForEachEntityDelegateState : IForEachInvoker");
        source.AppendLine("{");
        source.AppendLine("    private readonly ForEachEntityAction _action;");
        source.AppendLine("    internal ForEachEntityDelegateState(ForEachEntityAction action) => _action = action;");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) _action(cursor.Entities[cursor.CurrentIndex]); }");
        source.AppendLine("}");
        source.AppendLine("internal struct ForEachContextEntityDelegateState<TContext> : IForEachInvoker");
        source.AppendLine("{");
        source.AppendLine("    internal TContext Context;");
        source.AppendLine("    private readonly ForEachContextEntityAction<TContext> _action;");
        source.AppendLine("    internal ForEachContextEntityDelegateState(TContext context, ForEachContextEntityAction<TContext> action) { Context = context; _action = action; }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) _action(ref Context, cursor.Entities[cursor.CurrentIndex]); }");
        source.AppendLine("}");
        source.AppendLine("internal struct ForEachEntityFunctorState<TFunctor> : IForEachInvoker where TFunctor : struct, IForEachEntity");
        source.AppendLine("{");
        source.AppendLine("    internal TFunctor Functor;");
        source.AppendLine("    internal ForEachEntityFunctorState(TFunctor functor) => Functor = functor;");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) Functor.Invoke(cursor.Entities[cursor.CurrentIndex]); }");
        source.AppendLine("}");
        source.AppendLine("internal struct ForEachFunctorState<TFunctor> : IForEachInvoker where TFunctor : struct, IForEach");
        source.AppendLine("{");
        source.AppendLine("    internal TFunctor Functor;");
        source.AppendLine("    internal ForEachFunctorState(TFunctor functor) => Functor = functor;");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) Functor.Invoke(); }");
        source.AppendLine("}");
        source.AppendLine("internal struct ForEachContextFunctorState<TContext, TFunctor> : IForEachInvoker where TFunctor : struct, IForEachContext<TContext>");
        source.AppendLine("{");
        source.AppendLine("    internal TContext Context;");
        source.AppendLine("    internal TFunctor Functor;");
        source.AppendLine("    internal ForEachContextFunctorState(TContext context, TFunctor functor) { Context = context; Functor = functor; }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) Functor.Invoke(ref Context); }");
        source.AppendLine("}");
        source.AppendLine("internal struct ForEachContextEntityFunctorState<TContext, TFunctor> : IForEachInvoker where TFunctor : struct, IForEachContextEntity<TContext>");
        source.AppendLine("{");
        source.AppendLine("    internal TContext Context;");
        source.AppendLine("    internal TFunctor Functor;");
        source.AppendLine("    internal ForEachContextEntityFunctorState(TContext context, TFunctor functor) { Context = context; Functor = functor; }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor) { while (cursor.MoveNext()) Functor.Invoke(ref Context, cursor.Entities[cursor.CurrentIndex]); }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void RenderState(StringBuilder source, string name, string pattern, string constructorParameters, string constructorBody, string invocation, string? actionType = null, string? stateTypes = null, string? interfaceType = null)
    {
        source.Append("internal struct ").Append(name).Append(" : IForEachInvoker, ISequenceInvoker");
        if (interfaceType is not null)
        {
            source.Append(" where TFunctor : struct, ").Append(interfaceType);
        }

        source.AppendLine();
        source.AppendLine("{");
        if (stateTypes is not null)
        {
            if (stateTypes.Contains("TContext", StringComparison.Ordinal))
            {
                source.AppendLine("    internal TContext Context;");
            }

            if (stateTypes.Contains("TFunctor", StringComparison.Ordinal))
            {
                source.AppendLine("    internal TFunctor Functor;");
            }
        }

        if (actionType is not null)
        {
            source.Append("    private readonly ").Append(actionType).AppendLine(" _action;");
        }
        for (int index = 0; index < pattern.Length; index++)
        {
            source.Append("    private readonly ").Append(pattern[index] == 'R' ? "ReadAccess" : "WriteAccess")
                .Append(" _component").Append(index + 1).AppendLine(";");
        }

        source.Append("    internal ").Append(ConstructorName(name)).Append('(').Append(constructorParameters).Append(") { ").Append(constructorBody).AppendLine(" }");
        source.AppendLine("    public void Invoke(ref QueryChunkCursor cursor)");
        source.AppendLine("    {");
        for (int index = 0; index < pattern.Length; index++)
        {
            source.Append("        var value").Append(index + 1).Append(" = cursor.")
                .Append(pattern[index] == 'R' ? "GetRead" : "GetWrite")
                .Append("(_component").Append(index + 1).AppendLine(");");
        }

        source.AppendLine("        while (cursor.MoveNext())");
        source.AppendLine("        {");
        source.Append("            ").AppendLine(invocation);
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("    public void Invoke(ref SequenceElementCursor cursor)");
        source.AppendLine("    {");
        for (int index = 0; index < pattern.Length; index++)
        {
            source.Append("        var value").Append(index + 1).Append(" = cursor.Get(_component")
                .Append(index + 1).AppendLine(");");
        }

        source.Append("        ").AppendLine(SequenceInvocation(invocation));
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void RenderWorld(StringBuilder source)
    {
        source.AppendLine("public sealed partial class World");
        source.AppendLine("{");
        Append(source, "public void ForEach(in Query query, ForEachAction action)", "ArgumentNullException.ThrowIfNull(action); var state = new ForEachDelegateState(action); ForEachRuntime.Execute(this, in query, ref state, hasWrites: false);");
        Append(source, "public void ForEach<TContext>(in Query query, ref TContext context, ForEachContextAction<TContext> action)", "ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextDelegateState<TContext>(context, action); ForEachRuntime.Execute(this, in query, ref state, hasWrites: false); context = state.Context;");
        Append(source, "public void ForEach(in Query query, ForEachEntityAction action)", "ArgumentNullException.ThrowIfNull(action); var state = new ForEachEntityDelegateState(action); ForEachRuntime.Execute(this, in query, ref state, hasWrites: false);");
        Append(source, "public void ForEach<TContext>(in Query query, ref TContext context, ForEachContextEntityAction<TContext> action)", "ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextEntityDelegateState<TContext>(context, action); ForEachRuntime.Execute(this, in query, ref state, hasWrites: false); context = state.Context;");
        Append(source, "public void ForEach<TFunctor>(in Query query, ref TFunctor functor, ForEachEntityTag entity)", "var state = new ForEachEntityFunctorState<TFunctor>(functor); ForEachRuntime.Execute(this, in query, ref state, hasWrites: false); functor = state.Functor;", "where TFunctor : struct, IForEachEntity");
        Append(source, "public void ForEach<TContext, TFunctor>(in Query query, ref TContext context, ref TFunctor functor, ForEachEntityTag entity)", "var state = new ForEachContextEntityFunctorState<TContext, TFunctor>(context, functor); ForEachRuntime.Execute(this, in query, ref state, hasWrites: false); context = state.Context; functor = state.Functor;", "where TFunctor : struct, IForEachContextEntity<TContext>");
        Append(source, "public void ForEach<TFunctor>(in Query query, ref TFunctor functor)", "var state = new ForEachFunctorState<TFunctor>(functor); ForEachRuntime.Execute(this, in query, ref state, hasWrites: false); functor = state.Functor;", "where TFunctor : struct, IForEach");
        Append(source, "public void ForEach<TContext, TFunctor>(in Query query, ref TContext context, ref TFunctor functor)", "var state = new ForEachContextFunctorState<TContext, TFunctor>(context, functor); ForEachRuntime.Execute(this, in query, ref state, hasWrites: false); context = state.Context; functor = state.Functor;", "where TFunctor : struct, IForEachContext<TContext>");

        for (int arity = 1; arity <= 4; arity++)
        {
            int patternCount = 1 << arity;
            for (int bits = 0; bits < patternCount; bits++)
            {
                string pattern = AccessPattern(arity, bits);
                RenderDelegateOverloads(source, pattern, explicitIds: true);
                RenderDelegateOverloads(source, pattern, explicitIds: false);
                RenderFunctorOverloads(source, pattern, explicitIds: true);
                RenderFunctorOverloads(source, pattern, explicitIds: false);
                RenderSequenceDelegateOverloads(source, pattern, filtered: false, explicitIds: true);
                RenderSequenceDelegateOverloads(source, pattern, filtered: true, explicitIds: true);
                RenderSequenceDelegateOverloads(source, pattern, filtered: true, explicitIds: false);
                RenderSequenceFunctorOverloads(source, pattern, filtered: false, explicitIds: true);
                RenderSequenceFunctorOverloads(source, pattern, filtered: true, explicitIds: true);
                RenderSequenceFunctorOverloads(source, pattern, filtered: true, explicitIds: false);
            }
        }

        source.AppendLine("}");
        RenderSequenceFacade(source, filtered: false);
        RenderSequenceFacade(source, filtered: true);
    }

    private static void RenderDelegateOverloads(StringBuilder source, string pattern, bool explicitIds)
    {
        int arity = pattern.Length;
        string suffix = PatternSuffix(pattern);
        string generic = GenericTypes(arity);
        string parameters = explicitIds ? ComponentParameters(arity) : string.Empty;
        string parameterSuffix = explicitIds ? ", " + parameters : string.Empty;
        string setup = explicitIds ? string.Empty : ComponentSetup(arity);
        string accesses = explicitIds ? AccessArguments(pattern) : AccessArgumentsFromSpan(pattern);
        string tag = IsAllWrite(pattern) ? string.Empty : $", ForEachAccessTag_{pattern} access";
        bool hasWrites = pattern.IndexOf('W') >= 0;

        Append(source, $"public void ForEach<{generic}>(in Query query{parameterSuffix}, ForEachAction{suffix}<{generic}> action{tag})", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachDelegateState{suffix}<{generic}>(action, {accesses}); ForEachRuntime.Execute(this, in query, ref state, hasWrites: {Bool(hasWrites)});");
        Append(source, $"public void ForEach<{generic}>(in Query query{parameterSuffix}, ForEachEntityAction{suffix}<{generic}> action{tag})", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachEntityDelegateState{suffix}<{generic}>(action, {accesses}); ForEachRuntime.Execute(this, in query, ref state, hasWrites: {Bool(hasWrites)});");
        Append(source, $"public void ForEach<TContext, {generic}>(in Query query, ref TContext context{parameterSuffix}, ForEachContextAction{suffix}<TContext, {generic}> action{tag})", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextDelegateState{suffix}<TContext, {generic}>(context, action, {accesses}); ForEachRuntime.Execute(this, in query, ref state, hasWrites: {Bool(hasWrites)}); context = state.Context;");
        Append(source, $"public void ForEach<TContext, {generic}>(in Query query, ref TContext context{parameterSuffix}, ForEachContextEntityAction{suffix}<TContext, {generic}> action{tag})", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextEntityDelegateState{suffix}<TContext, {generic}>(context, action, {accesses}); ForEachRuntime.Execute(this, in query, ref state, hasWrites: {Bool(hasWrites)}); context = state.Context;");
    }

    private static void RenderFunctorOverloads(StringBuilder source, string pattern, bool explicitIds)
    {
        int arity = pattern.Length;
        string suffix = PatternSuffix(pattern);
        string generic = GenericTypes(arity);
        string parameters = explicitIds ? ComponentParameters(arity) : string.Empty;
        string parameterSuffix = explicitIds ? ", " + parameters : string.Empty;
        string setup = explicitIds ? string.Empty : ComponentSetup(arity);
        string accesses = explicitIds ? AccessArguments(pattern) : AccessArgumentsFromSpan(pattern);
        string tag = IsAllWrite(pattern) ? string.Empty : $", ForEachAccessTag_{pattern} access";
        bool hasWrites = pattern.IndexOf('W') >= 0;

        Append(source, $"public void ForEach<TFunctor, {generic}>(in Query query{parameterSuffix}, ref TFunctor functor{tag})", setup + $"var state = new ForEachFunctorState{suffix}<TFunctor, {generic}>(functor, {accesses}); ForEachRuntime.Execute(this, in query, ref state, hasWrites: {Bool(hasWrites)}); functor = state.Functor;", $"where TFunctor : struct, IForEach{suffix}<{generic}>");
        Append(source, $"public void ForEach<TFunctor, {generic}>(in Query query{parameterSuffix}, ref TFunctor functor, ForEachEntityTag entity{tag})", setup + $"var state = new ForEachEntityFunctorState{suffix}<TFunctor, {generic}>(functor, {accesses}); ForEachRuntime.Execute(this, in query, ref state, hasWrites: {Bool(hasWrites)}); functor = state.Functor;", $"where TFunctor : struct, IForEachEntity{suffix}<{generic}>");
        Append(source, $"public void ForEach<TContext, TFunctor, {generic}>(in Query query, ref TContext context{parameterSuffix}, ref TFunctor functor{tag})", setup + $"var state = new ForEachContextFunctorState{suffix}<TContext, TFunctor, {generic}>(context, functor, {accesses}); ForEachRuntime.Execute(this, in query, ref state, hasWrites: {Bool(hasWrites)}); context = state.Context; functor = state.Functor;", $"where TFunctor : struct, IForEachContext{suffix}<TContext, {generic}>");
        Append(source, $"public void ForEach<TContext, TFunctor, {generic}>(in Query query, ref TContext context{parameterSuffix}, ref TFunctor functor, ForEachEntityTag entity{tag})", setup + $"var state = new ForEachContextEntityFunctorState{suffix}<TContext, TFunctor, {generic}>(context, functor, {accesses}); ForEachRuntime.Execute(this, in query, ref state, hasWrites: {Bool(hasWrites)}); context = state.Context; functor = state.Functor;", $"where TFunctor : struct, IForEachContextEntity{suffix}<TContext, {generic}>");
    }

    private static void RenderSequenceDelegateOverloads(StringBuilder source, string pattern, bool filtered, bool explicitIds)
    {
        int arity = pattern.Length;
        string suffix = PatternSuffix(pattern);
        string generic = GenericTypes(arity);
        string componentParameters = explicitIds ? ComponentParameters(arity) : string.Empty;
        string componentSuffix = explicitIds ? ", " + componentParameters : string.Empty;
        string queryParameter = filtered ? ", in Query query" : string.Empty;
        string setup = SequenceSetup(pattern, filtered, explicitIds);
        string tag = IsAllWrite(pattern) ? string.Empty : $", ForEachAccessTag_{pattern} access";
        bool hasWrites = pattern.IndexOf('W') >= 0;

        Append(source, $"public void ForEach<{generic}>(ReadOnlySpan<Entity> entities{queryParameter}{componentSuffix}, ForEachAction{suffix}<{generic}> action{tag})", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachDelegateState{suffix}<{generic}>(action, {SequenceAccessArguments(pattern, explicitIds)}); ExecuteSequenceComponents(entities, in query, ref state, hasWrites: {Bool(hasWrites)});");
        Append(source, $"public void ForEach<{generic}>(ReadOnlySpan<Entity> entities{queryParameter}{componentSuffix}, ForEachEntityAction{suffix}<{generic}> action{tag})", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachEntityDelegateState{suffix}<{generic}>(action, {SequenceAccessArguments(pattern, explicitIds)}); ExecuteSequenceComponents(entities, in query, ref state, hasWrites: {Bool(hasWrites)});");
        Append(source, $"public void ForEach<TContext, {generic}>(ReadOnlySpan<Entity> entities{queryParameter}, ref TContext context{componentSuffix}, ForEachContextAction{suffix}<TContext, {generic}> action{tag})", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextDelegateState{suffix}<TContext, {generic}>(context, action, {SequenceAccessArguments(pattern, explicitIds)}); ExecuteSequenceComponents(entities, in query, ref state, hasWrites: {Bool(hasWrites)}); context = state.Context;");
        Append(source, $"public void ForEach<TContext, {generic}>(ReadOnlySpan<Entity> entities{queryParameter}, ref TContext context{componentSuffix}, ForEachContextEntityAction{suffix}<TContext, {generic}> action{tag})", setup + $"ArgumentNullException.ThrowIfNull(action); var state = new ForEachContextEntityDelegateState{suffix}<TContext, {generic}>(context, action, {SequenceAccessArguments(pattern, explicitIds)}); ExecuteSequenceComponents(entities, in query, ref state, hasWrites: {Bool(hasWrites)}); context = state.Context;");
    }

    private static void RenderSequenceFunctorOverloads(StringBuilder source, string pattern, bool filtered, bool explicitIds)
    {
        int arity = pattern.Length;
        string suffix = PatternSuffix(pattern);
        string generic = GenericTypes(arity);
        string componentParameters = explicitIds ? ComponentParameters(arity) : string.Empty;
        string componentSuffix = explicitIds ? ", " + componentParameters : string.Empty;
        string queryParameter = filtered ? ", in Query query" : string.Empty;
        string setup = SequenceSetup(pattern, filtered, explicitIds);
        string tag = IsAllWrite(pattern) ? string.Empty : $", ForEachAccessTag_{pattern} access";
        bool hasWrites = pattern.IndexOf('W') >= 0;

        Append(source, $"public void ForEach<TFunctor, {generic}>(ReadOnlySpan<Entity> entities{queryParameter}{componentSuffix}, ref TFunctor functor{tag})", setup + $"var state = new ForEachFunctorState{suffix}<TFunctor, {generic}>(functor, {SequenceAccessArguments(pattern, explicitIds)}); ExecuteSequenceComponents(entities, in query, ref state, hasWrites: {Bool(hasWrites)}); functor = state.Functor;", $"where TFunctor : struct, IForEach{suffix}<{generic}>");
        Append(source, $"public void ForEach<TFunctor, {generic}>(ReadOnlySpan<Entity> entities{queryParameter}{componentSuffix}, ref TFunctor functor, ForEachEntityTag entity{tag})", setup + $"var state = new ForEachEntityFunctorState{suffix}<TFunctor, {generic}>(functor, {SequenceAccessArguments(pattern, explicitIds)}); ExecuteSequenceComponents(entities, in query, ref state, hasWrites: {Bool(hasWrites)}); functor = state.Functor;", $"where TFunctor : struct, IForEachEntity{suffix}<{generic}>");
        Append(source, $"public void ForEach<TContext, TFunctor, {generic}>(ReadOnlySpan<Entity> entities{queryParameter}, ref TContext context{componentSuffix}, ref TFunctor functor{tag})", setup + $"var state = new ForEachContextFunctorState{suffix}<TContext, TFunctor, {generic}>(context, functor, {SequenceAccessArguments(pattern, explicitIds)}); ExecuteSequenceComponents(entities, in query, ref state, hasWrites: {Bool(hasWrites)}); context = state.Context; functor = state.Functor;", $"where TFunctor : struct, IForEachContext{suffix}<TContext, {generic}>");
        Append(source, $"public void ForEach<TContext, TFunctor, {generic}>(ReadOnlySpan<Entity> entities{queryParameter}, ref TContext context{componentSuffix}, ref TFunctor functor, ForEachEntityTag entity{tag})", setup + $"var state = new ForEachContextEntityFunctorState{suffix}<TContext, TFunctor, {generic}>(context, functor, {SequenceAccessArguments(pattern, explicitIds)}); ExecuteSequenceComponents(entities, in query, ref state, hasWrites: {Bool(hasWrites)}); context = state.Context; functor = state.Functor;", $"where TFunctor : struct, IForEachContextEntity{suffix}<TContext, {generic}>");
    }

    private static void RenderSequenceFacade(StringBuilder source, bool filtered)
    {
        string typeName = filtered ? "FilteredEntitySequence" : "EntitySequence";
        source.Append("public readonly ref partial struct ").AppendLine(typeName);
        source.AppendLine("{");
        for (int arity = 1; arity <= 4; arity++)
        {
            int patternCount = 1 << arity;
            for (int bits = 0; bits < patternCount; bits++)
            {
                string pattern = AccessPattern(arity, bits);
                string suffix = PatternSuffix(pattern);
                string generic = GenericTypes(arity);
                string components = ComponentParameters(arity);
                string componentNames = ComponentNames(arity);
                string worldPrefix = filtered ? "_world.ForEach(_entities, in _query, " : "_world.ForEach(_entities, ";
                string functorWorldPrefix = filtered
                    ? $"_world.ForEach<TFunctor, {generic}>(_entities, in _query, "
                    : $"_world.ForEach<TFunctor, {generic}>(_entities, ";
                string contextFunctorWorldPrefix = filtered
                    ? $"_world.ForEach<TContext, TFunctor, {generic}>(_entities, in _query, "
                    : $"_world.ForEach<TContext, TFunctor, {generic}>(_entities, ";
                string tag = IsAllWrite(pattern) ? string.Empty : $", ForEachAccessTag_{pattern} access";
                string tagArgument = IsAllWrite(pattern) ? string.Empty : ", access";

                AppendInline(source, $"public void ForEach<{generic}>({components}, ForEachAction{suffix}<{generic}> action{tag})", $"{worldPrefix}{componentNames}, action{tagArgument});");
                AppendInline(source, $"public void ForEach<{generic}>({components}, ForEachEntityAction{suffix}<{generic}> action{tag})", $"{worldPrefix}{componentNames}, action{tagArgument});");
                AppendInline(source, $"public void ForEach<TContext, {generic}>(ref TContext context, {components}, ForEachContextAction{suffix}<TContext, {generic}> action{tag})", $"{worldPrefix}ref context, {componentNames}, action{tagArgument});");
                AppendInline(source, $"public void ForEach<TContext, {generic}>(ref TContext context, {components}, ForEachContextEntityAction{suffix}<TContext, {generic}> action{tag})", $"{worldPrefix}ref context, {componentNames}, action{tagArgument});");
                AppendInline(source, $"public void ForEach<TFunctor, {generic}>({components}, ref TFunctor functor{tag})", $"{functorWorldPrefix}{componentNames}, ref functor{tagArgument});", $"where TFunctor : struct, IForEach{suffix}<{generic}>");
                AppendInline(source, $"public void ForEach<TFunctor, {generic}>({components}, ref TFunctor functor, ForEachEntityTag entity{tag})", $"{functorWorldPrefix}{componentNames}, ref functor, entity{tagArgument});", $"where TFunctor : struct, IForEachEntity{suffix}<{generic}>");
                AppendInline(source, $"public void ForEach<TContext, TFunctor, {generic}>(ref TContext context, {components}, ref TFunctor functor{tag})", $"{contextFunctorWorldPrefix}ref context, {componentNames}, ref functor{tagArgument});", $"where TFunctor : struct, IForEachContext{suffix}<TContext, {generic}>");
                AppendInline(source, $"public void ForEach<TContext, TFunctor, {generic}>(ref TContext context, {components}, ref TFunctor functor, ForEachEntityTag entity{tag})", $"{contextFunctorWorldPrefix}ref context, {componentNames}, ref functor, entity{tagArgument});", $"where TFunctor : struct, IForEachContextEntity{suffix}<TContext, {generic}>");
            }
        }

        source.AppendLine("}");
    }

    private static void Append(StringBuilder source, string signature, string body, string? constraint = null)
    {
        source.Append("    ").AppendLine(signature);
        if (constraint is not null)
        {
            source.Append("        ").AppendLine(constraint);
        }
        source.AppendLine("    {");
        source.Append("        ").AppendLine(body);
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void AppendInline(StringBuilder source, string signature, string body, string? constraint = null)
    {
        source.AppendLine("    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        Append(source, signature, body, constraint);
    }

    private static string AccessPattern(int arity, int bits)
    {
        var result = new char[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = (bits & (1 << index)) == 0 ? 'R' : 'W';
        }

        return new string(result);
    }

    private static bool IsAllWrite(string pattern)
    {
        for (int index = 0; index < pattern.Length; index++)
        {
            if (pattern[index] != 'W')
            {
                return false;
            }
        }

        return true;
    }

    private static string PatternSuffix(string pattern) => IsAllWrite(pattern) ? string.Empty : "_" + pattern;

    private static string GenericTypes(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "T" + (index + 1);
        }

        return string.Join(", ", result);
    }

    private static string ComponentParameters(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "ComponentId component" + (index + 1);
        }

        return string.Join(", ", result);
    }

    private static string ComponentNames(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "component" + (index + 1);
        }

        return string.Join(", ", result);
    }

    private static string RefParameters(string pattern)
    {
        var result = new string[pattern.Length];
        for (int index = 0; index < pattern.Length; index++)
        {
            result[index] = (pattern[index] == 'R' ? "in " : "ref ") + "T" + (index + 1) + " component" + (index + 1);
        }

        return string.Join(", ", result);
    }

    private static string AccessParameters(string pattern)
    {
        var result = new string[pattern.Length];
        for (int index = 0; index < pattern.Length; index++)
        {
            result[index] = (pattern[index] == 'R' ? "ReadAccess" : "WriteAccess") + " component" + (index + 1);
        }

        return string.Join(", ", result);
    }

    private static string AssignAccessFields(int arity)
    {
        var result = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            result[index] = "_component" + (index + 1) + " = component" + (index + 1) + ";";
        }

        return string.Join(" ", result);
    }

    private static string AccessArguments(string pattern)
    {
        var result = new string[pattern.Length];
        for (int index = 0; index < pattern.Length; index++)
        {
            result[index] = "ForEachRuntime.Access" + (pattern[index] == 'R' ? "Read" : "Write") + "<T" + (index + 1) + ">(this, in query, component" + (index + 1) + ")";
        }

        return string.Join(", ", result);
    }

    private static string AccessArgumentsFromSpan(string pattern)
    {
        var result = new string[pattern.Length];
        for (int index = 0; index < pattern.Length; index++)
        {
            result[index] = "ForEachRuntime.Access" + (pattern[index] == 'R' ? "Read" : "Write") + "<T" + (index + 1) + ">(this, in query, componentIds[" + index + "])";
        }

        return string.Join(", ", result);
    }

    private static string SequenceAccessArguments(string pattern, bool explicitIds)
        => explicitIds ? AccessArguments(pattern) : AccessArgumentsFromSpan(pattern);

    private static string SequenceSetup(string pattern, bool filtered, bool explicitIds)
    {
        if (filtered)
        {
            return explicitIds ? string.Empty : ComponentSetup(pattern.Length);
        }

        var assignments = new string[pattern.Length];
        for (int index = 0; index < pattern.Length; index++)
        {
            assignments[index] = $"componentIds[{index}] = component{index + 1};";
        }

        return $"Span<ComponentId> componentIds = stackalloc ComponentId[{pattern.Length}]; {string.Join(" ", assignments)} Query query = CreateSequenceQuery(componentIds); ";
    }

    private static string ComponentSetup(int arity) => $"Span<ComponentId> componentIds = stackalloc ComponentId[{arity}]; ForEachRuntime.ResolveComponentIds(in query, componentIds); ";

    private static string ValueStatements(string pattern)
    {
        var result = new string[pattern.Length];
        for (int index = 0; index < pattern.Length; index++)
        {
            result[index] = (pattern[index] == 'R' ? "in " : "ref ") + "value" + (index + 1) + ".Ref<T" + (index + 1) + ">(cursor)";
        }

        return string.Join(", ", result);
    }

    private static string ConstructorName(string name)
    {
        int genericStart = name.IndexOf('<');
        return genericStart < 0 ? name : name.Substring(0, genericStart);
    }

    private static string Bool(bool value) => value ? "true" : "false";

    private static string SequenceInvocation(string invocation) => invocation
        .Replace("cursor.Entities[cursor.CurrentIndex]", "cursor.Entity")
        .Replace("(cursor)", "(cursor.Slot)");
}
