using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Delta.ECS.Generators;

/// <summary>
/// Generates typed World factories and composable Query extensions only for
/// the WhereAll, WhereAny and WhereNone shapes used by a consumer compilation.
/// </summary>
[Generator]
public sealed class GeneratedQueryGenerator : IIncrementalGenerator
{
    private const int MaxArity = 256;
    private const string Header = """
        // <auto-generated />
        #nullable enable
        namespace Delta.ECS
        {

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (productionContext, compilation) => Execute(compilation, productionContext));
    }

    private static void Execute(Compilation compilation, SourceProductionContext context)
    {
        var shapes = new Dictionary<string, QueryShape>(StringComparer.Ordinal);
        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            SemanticModel model = compilation.GetSemanticModel(tree);
            foreach (InvocationExpressionSyntax invocation in tree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                if (!TryReadShape(model, invocation, out QueryShape? shape)
                    || shape is null)
                {
                    continue;
                }

                // The emitted extension signature depends only on the query
                // kind and arity. Component types are supplied by the call's
                // type arguments, so different systems using the same arity
                // must share one generated method instead of declaring
                // duplicate extension methods with identical signatures.
                if (!shapes.ContainsKey(shape.Key))
                {
                    shapes.Add(shape.Key, shape);
                }
            }
        }

        foreach (QueryShape shape in shapes.Values.OrderBy(static value => value.Key, StringComparer.Ordinal))
        {
            context.AddSource(
                "GeneratedQuery_" + StableName(shape.Key) + ".g.cs",
                Render(shape));
        }
    }

    private static bool TryReadShape(
        SemanticModel model,
        InvocationExpressionSyntax invocation,
        out QueryShape? shape)
    {
        shape = null;
        if (invocation.Expression is not MemberAccessExpressionSyntax member
            || member.Name is not GenericNameSyntax genericName
            || genericName.Identifier.ValueText is not ("WhereAll" or "WhereAny" or "WhereNone")
            || invocation.ArgumentList.Arguments.Count != 0)
        {
            return false;
        }

        if (!IsWorldReceiver(model, member.Expression)
            && !IsQueryReceiver(model, member.Expression))
        {
            return false;
        }

        int arity = genericName.TypeArgumentList.Arguments.Count;
        if (arity is < 1 or > MaxArity)
        {
            return false;
        }

        for (int index = 0; index < arity; index++)
        {
            ITypeSymbol? type = model.GetTypeInfo(genericName.TypeArgumentList.Arguments[index]).Type;
            if (type is null
                || type.TypeKind == TypeKind.Error
                || type is ITypeParameterSymbol
                || !IsAccessibleToGeneratedCode(type))
            {
                return false;
            }
        }

        shape = new QueryShape(genericName.Identifier.ValueText, arity);
        return true;
    }

    private static bool IsWorldReceiver(SemanticModel model, ExpressionSyntax expression)
        => IsNamedType(model.GetTypeInfo(expression).Type, "World");

    private static bool IsQueryReceiver(SemanticModel model, ExpressionSyntax expression)
    {
        if (IsNamedType(model.GetTypeInfo(expression).Type, "Query"))
        {
            return true;
        }

        // Earlier generated extension calls are not part of the input
        // compilation's semantic model, so recognize a fluent factory chain
        // syntactically as well as a resolved Query receiver.
        if (expression is InvocationExpressionSyntax invocation
            && invocation.ArgumentList.Arguments.Count == 0
            && invocation.Expression is MemberAccessExpressionSyntax member
            && member.Name is GenericNameSyntax genericName
            && genericName.Identifier.ValueText is ("WhereAll" or "WhereAny" or "WhereNone"))
        {
            return IsWorldReceiver(model, member.Expression)
                || IsQueryReceiver(model, member.Expression);
        }

        if (expression is IdentifierNameSyntax identifier
            && model.GetSymbolInfo(identifier).Symbol is ILocalSymbol local
            && local.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() is VariableDeclaratorSyntax declarator
            && declarator.Initializer?.Value is ExpressionSyntax initializer)
        {
            return IsWorldReceiver(model, initializer)
                || IsQueryReceiver(model, initializer);
        }

        return false;
    }

    private static bool IsNamedType(ITypeSymbol? type, string name)
        => type is INamedTypeSymbol named
            && named.Name == name
            && named.ContainingNamespace.ToDisplayString() == "Delta.ECS";

    private static bool IsAccessibleToGeneratedCode(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array)
        {
            return IsAccessibleToGeneratedCode(array.ElementType);
        }

        if (type is not INamedTypeSymbol named)
        {
            return true;
        }

        if (named.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
        {
            return false;
        }

        return named.ContainingType is null || IsAccessibleToGeneratedCode(named.ContainingType);
    }

    private static string Render(QueryShape shape)
    {
        var source = new StringBuilder(8 * 1024);
        source.Append(Header);
        source.Append("public static class GeneratedQueryExtensions_")
            .Append(StableName(shape.Key))
            .AppendLine();
        source.AppendLine("{");
        RenderFactory(source, shape, "World", "world", "world.CreateQuery");
        RenderFactory(source, shape, "Query", "query", "GeneratedForEachRuntime.ComposeGeneratedQuery");
        source.AppendLine("}");
        source.AppendLine("}");
        return GeneratedSourceFormatter.Format(source.ToString());
    }

    private static void RenderFactory(
        StringBuilder source,
        QueryShape shape,
        string receiverType,
        string receiverName,
        string createCall)
    {
        source.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        source.Append("    public static Query ")
            .Append(shape.Kind)
            .Append('<')
            .Append(GenericTypes(shape.Arity))
            .Append(">(this ")
            .Append(receiverType)
            .Append(' ')
            .Append(receiverName)
            .AppendLine(")");
        source.AppendLine("    {");
        source.Append("        global::System.Span<ComponentId> components = stackalloc ComponentId[")
            .Append(shape.Arity.ToString(CultureInfo.InvariantCulture))
            .AppendLine("];");

        for (int index = 0; index < shape.Arity; index++)
        {
            source.Append("        components[")
                .Append(index.ToString(CultureInfo.InvariantCulture))
                .Append("] = ")
                .Append(receiverType == "World"
                    ? "world.Layouts.GetPrimary<T"
                    : "GeneratedForEachRuntime.GetGeneratedPrimary<T")
                .Append((index + 1).ToString(CultureInfo.InvariantCulture))
                .Append(receiverType == "World"
                    ? ">();"
                    : ">(in query);")
                .AppendLine();
        }

        source.Append("        QuerySpec additions = QuerySpec.")
            .Append(shape.Kind)
            .AppendLine("(components);");
        if (receiverType == "World")
        {
            source.Append("        return ").Append(createCall).AppendLine("(additions);");
        }
        else
        {
            source.Append("        return ").Append(createCall).Append("(in ").Append(receiverName).AppendLine(", additions);");
        }

        source.AppendLine("    }");
    }

    private static string GenericTypes(int arity)
    {
        var values = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            values[index] = "T" + (index + 1).ToString(CultureInfo.InvariantCulture);
        }

        return string.Join(", ", values);
    }

    private static string StableName(string value)
    {
        unchecked
        {
            uint hash = 2166136261;
            foreach (char character in value)
            {
                hash = (hash ^ character) * 16777619;
            }

            return hash.ToString("X8", CultureInfo.InvariantCulture);
        }
    }

    private sealed class QueryShape
    {
        internal QueryShape(string kind, int arity)
        {
            Kind = kind;
            Arity = arity;
        }

        internal string Kind { get; }
        internal int Arity { get; }
        internal string Key => Kind + "|" + Arity.ToString(CultureInfo.InvariantCulture);
    }
}
