using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Delta.ECS.Generators;

/// <summary>
/// Generates generic structural-operation façades only for the
/// Add/Remove/Set/Create shapes used by a consumer assembly.
/// </summary>
[Generator]
public sealed class GeneratedStructuralGenerator : IIncrementalGenerator
{
    private const string Header = """
        // <auto-generated />
        #nullable enable
        namespace Delta.ECS
        {

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            GeneratorPipeline.ShapeProvider<StructuralShape>(
                    context,
                    static syntaxContext => TryReadShape(
                        syntaxContext.SemanticModel,
                        (Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax)syntaxContext.Node,
                        out StructuralShape? shape)
                        ? shape
                        : null)
                .Where(static shape => shape is not null)
                .Select(static (shape, _) => shape!)
                .Collect(),
            static (productionContext, shapes) => GeneratorPipeline.EmitShapes<StructuralShape>(
                shapes,
                productionContext,
                "GeneratedStructural_",
                static shape => shape.Key,
                static shape => GeneratedStructuralGenerator.Render(shape)));
    }

    private static bool TryReadShape(
        SemanticModel model,
        InvocationExpressionSyntax invocation,
        out StructuralShape? shape)
    {
        shape = null;
        if (invocation.Expression is not MemberAccessExpressionSyntax member)
        {
            return false;
        }

        if (member.Name is IdentifierNameSyntax identifier)
        {
            return identifier.Identifier.ValueText switch
            {
                "Add" => TryReadValueShape(model, invocation, isAdd: true, out shape),
                "Set" => TryReadValueShape(model, invocation, isAdd: false, out shape),
                "Create" => TryReadExplicitCreateShape(model, invocation, out shape),
                _ => false
            };
        }

        if (member.Name is not GenericNameSyntax genericName
            || genericName.Identifier.ValueText is not ("Add" or "Remove" or "Set" or "Create"))
        {
            return false;
        }

        int arity = genericName.TypeArgumentList.Arguments.Count;
        if (arity < 1)
        {
            return false;
        }

        Receiver receiver = ReadReceiver(model.GetTypeInfo(member.Expression).Type);
        if (receiver == Receiver.None)
        {
            return false;
        }

        if (genericName.Identifier.ValueText == "Create")
        {
            if (receiver != Receiver.World)
            {
                return false;
            }

            SeparatedSyntaxList<ArgumentSyntax> arguments = invocation.ArgumentList.Arguments;
            int countIndex = arguments.Count - 1;
            bool hasOutput = countIndex >= 0
                && GeneratorSupport.IsEntityOutput(model.GetTypeInfo(arguments[countIndex].Expression).Type);
            if (hasOutput)
            {
                countIndex--;
            }

            if (countIndex >= 0 && GeneratorSupport.IsInt32(model.GetTypeInfo(arguments[countIndex].Expression).Type))
            {
                int selectorCount = countIndex;
                bool hasExplicitSelectors = selectorCount == arity;
                if (hasExplicitSelectors)
                {
                    for (int index = 0; index < selectorCount; index++)
                    {
                        if (!GeneratorSupport.IsComponentId(model.GetTypeInfo(arguments[index].Expression).Type))
                        {
                            hasExplicitSelectors = false;
                            break;
                        }
                    }
                }

                if (selectorCount != 0 && !hasExplicitSelectors)
                {
                    return false;
                }

                shape = new StructuralShape(
                    receiver,
                    hasOutput ? StructuralMode.CreateOutput : StructuralMode.Create,
                    false,
                    arity,
                    isExplicitIds: hasExplicitSelectors);
                return true;
            }

            if (arguments.Count == 0)
            {
                shape = new StructuralShape(receiver, StructuralMode.CreateSingle, false, arity);
                return true;
            }

            return false;
        }

        if (genericName.Identifier.ValueText is "Add" or "Set"
            && TryReadValueShape(
                model,
                invocation,
                genericName.Identifier.ValueText == "Add",
                out shape))
        {
            return true;
        }

        if (genericName.Identifier.ValueText == "Set")
        {
            return false;
        }

        StructuralMode mode;
        bool explicitIds = false;
        if (receiver == Receiver.World)
        {
            int argumentCount = invocation.ArgumentList.Arguments.Count;
            if (argumentCount != 1 && argumentCount != arity + 1)
            {
                return false;
            }

            ArgumentSyntax argument = invocation.ArgumentList.Arguments[0];
            if (argument.RefKindKeyword.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.InKeyword)
                && GeneratorSupport.IsNamedType(model.GetTypeInfo(argument.Expression).Type, "Query"))
            {
                mode = StructuralMode.Query;
            }
            else if (GeneratorSupport.IsEntityBatch(model.GetTypeInfo(argument.Expression).Type))
            {
                mode = StructuralMode.Entities;
            }
            else if (GeneratorSupport.IsEntityType(model.GetTypeInfo(argument.Expression).Type))
            {
                mode = StructuralMode.SingleEntity;
            }
            else
            {
                return false;
            }

            if (argumentCount == arity + 1)
            {
                for (int index = 1; index < argumentCount; index++)
                {
                    if (!GeneratorSupport.IsComponentId(model.GetTypeInfo(invocation.ArgumentList.Arguments[index].Expression).Type))
                    {
                        return false;
                    }
                }

                explicitIds = true;
            }
        }
        else
        {
            return false;
        }

        shape = new StructuralShape(
            receiver,
            mode,
            genericName.Identifier.ValueText == "Add",
            arity,
            isExplicitIds: explicitIds);
        return true;
    }

    private static bool TryReadValueShape(
        SemanticModel model,
        InvocationExpressionSyntax invocation,
        bool isAdd,
        out StructuralShape? shape)
    {
        shape = null;
        if (ReadReceiver(model.GetTypeInfo(((MemberAccessExpressionSyntax)invocation.Expression).Expression).Type)
            != Receiver.World)
        {
            return false;
        }

        SeparatedSyntaxList<ArgumentSyntax> arguments = invocation.ArgumentList.Arguments;
        int arity = arguments.Count - 1;
        if (arity < 2
            || !GeneratorSupport.IsEntityType(model.GetTypeInfo(arguments[0].Expression).Type))
        {
            return false;
        }

        for (int index = 1; index < arguments.Count; index++)
        {
            ITypeSymbol? valueType = model.GetTypeInfo(arguments[index].Expression).Type;
            if (valueType is null || GeneratorSupport.IsComponentId(valueType))
            {
                return false;
            }
        }

        shape = new StructuralShape(
            Receiver.World,
            StructuralMode.SingleEntity,
            isAdd,
            arity: arity,
            hasValues: true);
        return true;
    }

    private static bool TryReadExplicitCreateShape(
        SemanticModel model,
        InvocationExpressionSyntax invocation,
        out StructuralShape? shape)
    {
        shape = null;
        if (invocation.Expression is not MemberAccessExpressionSyntax member
            || ReadReceiver(model.GetTypeInfo(member.Expression).Type) != Receiver.World)
        {
            return false;
        }

        SeparatedSyntaxList<ArgumentSyntax> arguments = invocation.ArgumentList.Arguments;
        if (arguments.Count < 2)
        {
            return false;
        }

        int countIndex = arguments.Count - 1;
        bool hasOutput = false;
        if (GeneratorSupport.IsEntityOutput(model.GetTypeInfo(arguments[countIndex].Expression).Type))
        {
            hasOutput = true;
            countIndex--;
        }

        if (countIndex < 1
            || !GeneratorSupport.IsInt32(model.GetTypeInfo(arguments[countIndex].Expression).Type))
        {
            return false;
        }

        for (int index = 0; index < countIndex; index++)
        {
            if (!GeneratorSupport.IsComponentId(model.GetTypeInfo(arguments[index].Expression).Type))
            {
                return false;
            }
        }

        shape = new StructuralShape(
            Receiver.World,
            hasOutput ? StructuralMode.ExplicitCreateOutput : StructuralMode.ExplicitCreate,
            isAdd: false,
            countIndex,
            isGeneric: false);
        return true;
    }

    private static Receiver ReadReceiver(ITypeSymbol? type)
    {
        string name = type?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? string.Empty;
        return name switch
        {
            "global::Delta.ECS.World" => Receiver.World,
            _ => Receiver.None
        };
    }

    private static string Render(StructuralShape shape)
    {
        StringBuilder source = GeneratorSupport.CreateSource(8 * 1024, Header);
        source.Append("public static class GeneratedStructuralExtensions_")
            .Append(GeneratorSupport.StableName(shape.Key))
            .AppendLine();
        source.AppendLine("{");
        source.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        source.Append("    public static ")
            .Append(ReturnType(shape))
            .Append(' ')
            .Append(MethodName(shape));
        if (shape.IsGeneric)
        {
            source.Append('<').Append(GeneratorSupport.GenericTypes(shape.Arity)).Append('>');
        }
        source.Append("(this ").Append(ReceiverType(shape.Receiver)).Append(" target");
        switch (shape.Mode)
        {
            case StructuralMode.Entities:
                source.Append(", global::System.ReadOnlySpan<Entity> entities");
                break;
            case StructuralMode.SingleEntity:
                source.Append(", Entity entity");
                if (shape.HasValues)
                {
                    source.Append(", ").Append(ValueParameters(shape.Arity));
                }
                break;
            case StructuralMode.Query:
                source.Append(", in Query query");
                break;
            case StructuralMode.Create:
                if (shape.IsExplicitIds)
                {
                    source.Append(", ").Append(ComponentParameters(shape.Arity));
                }
                source.Append(", int count");
                break;
            case StructuralMode.CreateOutput:
                if (shape.IsExplicitIds)
                {
                    source.Append(", ").Append(ComponentParameters(shape.Arity));
                }
                source.Append(", int count, global::System.Span<Entity> output");
                break;
            case StructuralMode.ExplicitCreate:
                source.Append(", ").Append(ComponentParameters(shape.Arity)).Append(", int count");
                break;
            case StructuralMode.ExplicitCreateOutput:
                source.Append(", ").Append(ComponentParameters(shape.Arity)).Append(", int count, global::System.Span<Entity> output");
                break;
        }

        if (shape.IsExplicitIds
            && shape.Mode is not (StructuralMode.Create or StructuralMode.CreateOutput))
        {
            source.Append(", ").Append(ComponentParameters(shape.Arity));
        }

        source.AppendLine(")");
        source.AppendLine("    {");
        if (shape.HasValues)
        {
            AppendComponents(source, shape);
            source.Append("        var initializer = new Generated")
                .Append(shape.Plan.Operation == StructuralOperation.Add ? "Add" : "Set")
                .Append("Values<")
                .Append(GeneratorSupport.GenericTypes(shape.Arity))
                .AppendLine(">");
            source.AppendLine("        (");
            for (int index = 0; index < shape.Arity; index++)
            {
                source.Append("            components[").Append(index).Append("], in value").Append(index);
                source.AppendLine(index == shape.Arity - 1 ? string.Empty : ",");
            }

            source.AppendLine("        );");
            source.Append("        return GeneratedForEachRuntime.ExecuteGenerated")
                .Append(shape.Plan.Operation == StructuralOperation.Add ? "Add" : "Set")
                .AppendLine("(");
            source.AppendLine("            target,");
            source.AppendLine("            entity,");
            source.AppendLine("            components,");
            source.AppendLine("            ref initializer);");
        }
        else if (shape.Mode is StructuralMode.CreateSingle
            or StructuralMode.Create
            or StructuralMode.CreateOutput)
        {
            AppendComponents(source, shape);
            switch (shape.Mode)
            {
                case StructuralMode.CreateSingle:
                    source.AppendLine("        return target.Create(components);");
                    break;
                case StructuralMode.Create:
                    source.AppendLine("        return target.Create(components, count);");
                    break;
                case StructuralMode.CreateOutput:
                    source.AppendLine("        return target.Create(components, count, output);");
                    break;
            }
        }
        else if (shape.Mode is StructuralMode.ExplicitCreate or StructuralMode.ExplicitCreateOutput)
        {
            AppendComponents(source, shape);

            source.AppendLine(shape.Mode == StructuralMode.ExplicitCreate
                ? "        return target.Create(components, count);"
                : "        return target.Create(components, count, output);");
        }
        else
        {
            AppendComponents(source, shape);
            source.Append("        return target.").Append(shape.Plan.Operation == StructuralOperation.Add ? "Add" : "Remove");
            if (shape.Mode == StructuralMode.Query)
            {
                source.AppendLine("(in query, components);");
            }
            else if (shape.Mode == StructuralMode.SingleEntity)
            {
                source.AppendLine("(entity, components);");
            }
            else
            {
                source.AppendLine("(entities, components);");
            }
        }

        source.AppendLine("    }");

        if (shape.HasValues)
        {
            RenderValueInitializer(source, shape.Arity, shape.Plan.Operation == StructuralOperation.Add);
        }

        source.AppendLine("}");
        source.AppendLine("}");
        return GeneratorSupport.FinishSource(source);
    }

    private static void RenderValueInitializer(StringBuilder source, int arity, bool isAdd)
    {
        source.Append("    private struct Generated")
            .Append(isAdd ? "Add" : "Set")
            .Append("Values<")
            .Append(GeneratorSupport.GenericTypes(arity))
            .AppendLine("> : global::Delta.ECS.IGeneratedComponentValueInitializer");
        source.AppendLine("    {");
        for (int index = 0; index < arity; index++)
        {
            source.Append("        private readonly ComponentId component").Append(index).AppendLine(";");
            source.Append("        private readonly T").Append(index + 1).Append(" value").Append(index).AppendLine(";");
        }

        source.Append("        public Generated")
            .Append(isAdd ? "Add" : "Set")
            .Append("Values(");
        for (int index = 0; index < arity; index++)
        {
            if (index != 0)
            {
                source.Append(", ");
            }

            source.Append("ComponentId component").Append(index)
                .Append(", in T").Append(index + 1).Append(" value").Append(index);
        }

        source.AppendLine(")");
        source.AppendLine("        {");
        for (int index = 0; index < arity; index++)
        {
            source.Append("            this.component").Append(index).Append(" = component").Append(index).AppendLine(";");
            source.Append("            this.value").Append(index).Append(" = value").Append(index).AppendLine(";");
        }

        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void Initialize(ref global::Delta.ECS.GeneratedComponentValueWriter writer)");
        source.AppendLine("        {");
        for (int index = 0; index < arity; index++)
        {
            source.Append("            writer.Set")
                .Append(isAdd ? string.Empty : "Unsafe")
                .Append("(component")
                .Append(index)
                .Append(", in value")
                .Append(index)
                .AppendLine(");");
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    private static void AppendComponents(StringBuilder source, StructuralShape shape)
    {
        source.Append("        global::System.Span<ComponentId> components = stackalloc ComponentId[")
            .Append(shape.Arity)
            .AppendLine("];");
        bool explicitIds = shape.IsExplicitIds
            || shape.Mode is StructuralMode.ExplicitCreate or StructuralMode.ExplicitCreateOutput;
        if (explicitIds)
        {
            AppendComponentAssignments(source, "components", shape.Arity, "component", "        ");
        }
        else
        {
            AppendPrimaryAssignments(source, "target.Layouts", "components", shape.Arity, "        ");
        }
    }

    private static void AppendComponentAssignments(
        StringBuilder source,
        string destination,
        int arity,
        string parameterPrefix,
        string indent)
    {
        for (int index = 0; index < arity; index++)
        {
            source.Append(indent).Append(destination).Append('[').Append(index).Append("] = ")
                .Append(parameterPrefix).Append(index).AppendLine(";");
        }
    }

    private static string MethodName(StructuralShape shape)
        => shape.Plan.Operation switch
        {
            StructuralOperation.Create => "Create",
            StructuralOperation.Set => "Set",
            StructuralOperation.Add => "Add",
            StructuralOperation.Remove => "Remove",
            _ => "Set"
        };

    private static string ReturnType(StructuralShape shape)
        => shape.Mode switch
        {
            StructuralMode.CreateSingle => "Entity",
            StructuralMode.SingleEntity => "bool",
            _ => "int"
        };

    private static string ComponentParameters(int arity)
        => string.Join(", ", Enumerable.Range(0, arity).Select(static index => "ComponentId component" + index));

    private static string ValueParameters(int arity)
        => string.Join(", ", Enumerable.Range(0, arity).Select(static index => "in T" + (index + 1) + " value" + index));

    private static void AppendPrimaryAssignments(
        StringBuilder source,
        string registry,
        string destination,
        int arity,
        string indent)
    {
        for (int index = 0; index < arity; index++)
        {
            source.Append(indent)
                .Append(destination)
                .Append('[')
                .Append(index)
                .Append("] = ")
                .Append(registry)
                .Append(".GetPrimary<T")
                .Append(index + 1)
                .AppendLine(">();");
        }
    }

    private static string ReceiverType(Receiver receiver)
        => receiver switch
        {
            Receiver.World => "World",
            _ => string.Empty
        };

    private enum Receiver
    {
        None,
        World,
    }

    private enum StructuralMode
    {
        Entities,
        SingleEntity,
        Query,
        CreateSingle,
        Create,
        CreateOutput,
        ExplicitCreate,
        ExplicitCreateOutput
    }

    private sealed class StructuralShape
    {
        internal StructuralShape(
            Receiver receiver,
            StructuralMode mode,
            bool isAdd,
            int arity,
            bool isGeneric = true,
            bool isExplicitIds = false,
            bool hasValues = false)
        {
            Receiver = receiver;
            Mode = mode;
            Arity = arity;
            IsGeneric = isGeneric;
            IsExplicitIds = isExplicitIds;
            HasValues = hasValues;
            SelectorKind selector = isExplicitIds ? SelectorKind.ComponentIds : isGeneric ? SelectorKind.Generic : SelectorKind.ComponentIds;
            var slots = GeneratorSupport.ComponentSlots(arity, selector, AccessKind.Value);

            StructuralOperation operation = mode == StructuralMode.SingleEntity && hasValues
                ? (isAdd ? StructuralOperation.Add : StructuralOperation.Set)
                : mode is StructuralMode.CreateSingle
                    or StructuralMode.Create
                    or StructuralMode.CreateOutput
                    or StructuralMode.ExplicitCreate
                    or StructuralMode.ExplicitCreateOutput
                    ? StructuralOperation.Create
                    : isAdd ? StructuralOperation.Add : StructuralOperation.Remove;
            TargetKind target = mode switch
            {
                StructuralMode.Entities => TargetKind.EntityList,
                StructuralMode.SingleEntity => TargetKind.Entity,
                StructuralMode.Query => TargetKind.Query,
                _ => TargetKind.World
            };
            Api = new ApiShape(
                OperationKind.Structural,
                target,
                mode == StructuralMode.Query ? QueryMode.Required : QueryMode.None,
                new SelectorSpec(selector, slots),
                new ContextSpec(ContextModeKind.None, null),
                null,
                new ExecutionSpec(ExecutionKind.Dense, ValueKind.Component),
                operation + "|" + mode + "|" + isAdd + "|" + hasValues);
            Plan = new StructuralPlan(operation);
        }

        internal Receiver Receiver { get; }
        internal StructuralMode Mode { get; }
        internal int Arity { get; }
        internal bool IsGeneric { get; }
        internal bool IsExplicitIds { get; }
        internal bool HasValues { get; }
        internal ApiShape Api { get; }
        internal StructuralPlan Plan { get; }
        internal string Key => Api.SignatureKey;
    }
}
