using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Delta.ECS.Generators;

/// <summary>Generates stack-only read-only predicate views for query-wide mutation terminals.</summary>
[Generator]
public sealed class GeneratedWhereGenerator : IIncrementalGenerator
{
    private const int MaxArity = 256;
    private static readonly DiagnosticDescriptor WritablePredicate = new(
        "DECSGEN006",
        "Where predicate is read-only",
        "Where predicates cannot write components; use 'in' or 'ref readonly' parameters and mutate in a terminal callback",
        "Where",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private const string Header = """
        // <auto-generated />
        #nullable enable
        using global::System;
        namespace Delta.ECS
        {

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (productionContext, compilation) => Execute(compilation, productionContext));
    }

    private static void Execute(Compilation compilation, SourceProductionContext context)
    {
        var shapes = new Dictionary<string, PredicateShape>(StringComparer.Ordinal);
        var whereCalls = new Dictionary<InvocationExpressionSyntax, PredicateShape>();
        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            SemanticModel model = compilation.GetSemanticModel(tree);
            foreach (InvocationExpressionSyntax invocation in tree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                if (!TryReadPredicate(model, invocation, out PredicateShape? candidate)
                    || candidate is null)
                {
                    if (IsWritablePredicate(model, invocation))
                    {
                        context.ReportDiagnostic(Diagnostic.Create(WritablePredicate, invocation.GetLocation()));
                    }

                    continue;
                }

                if (!shapes.TryGetValue(candidate.Key, out PredicateShape? shape))
                {
                    shape = candidate;
                    shapes.Add(shape.Key, shape);
                }

                whereCalls[invocation] = shape;
            }
        }

        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            SemanticModel model = compilation.GetSemanticModel(tree);
            foreach (InvocationExpressionSyntax invocation in tree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                if (!TryGetWhereReceiver(invocation, out InvocationExpressionSyntax? whereInvocation)
                    || !whereCalls.TryGetValue(whereInvocation, out PredicateShape? shape)
                    || !TryReadTerminal(model, invocation, out TerminalShape? terminal)
                    || terminal is null)
                {
                    continue;
                }

                if (!shape.Terminals.ContainsKey(terminal.Key))
                {
                    shape.Terminals.Add(terminal.Key, terminal);
                }
            }
        }

        foreach (PredicateShape shape in shapes.Values.OrderBy(static value => value.Key, StringComparer.Ordinal))
        {
            context.AddSource("GeneratedWhere_" + StableName(shape.Key) + ".g.cs", Render(shape));
        }
    }

    private static bool TryReadPredicate(
        SemanticModel model,
        InvocationExpressionSyntax invocation,
        out PredicateShape? shape)
    {
        shape = null;
        if (invocation.Expression is not MemberAccessExpressionSyntax member
            || member.Name is not IdentifierNameSyntax { Identifier.ValueText: "Where" }
            || invocation.ArgumentList.Arguments.Count != 2
            || !invocation.ArgumentList.Arguments[0].RefKindKeyword.IsKind(SyntaxKind.InKeyword)
            || !IsNamedType(model.GetTypeInfo(member.Expression).Type, "World")
            || invocation.ArgumentList.Arguments[1].Expression is not LambdaExpressionSyntax lambda)
        {
            return false;
        }

        ParameterSyntax[] parameters = LambdaParameters(lambda);
        if (parameters.Length == 0 || !IsEntityParameter(model, parameters[0]))
        {
            return false;
        }

        string pattern = new string(parameters
            .Skip(1)
            .Select(parameter => PatternLetter(parameter))
            .ToArray());
        if (pattern.Length > MaxArity
            || parameters.Skip(1).Any(parameter =>
                !HasTypedAccessibleParameter(model, parameter)
                || PatternLetter(parameter) == 'W'))
        {
            return false;
        }

        shape = new PredicateShape(pattern);
        return true;
    }

    private static bool IsWritablePredicate(SemanticModel model, InvocationExpressionSyntax invocation)
    {
        if (invocation.Expression is not MemberAccessExpressionSyntax member
            || member.Name is not IdentifierNameSyntax { Identifier.ValueText: "Where" }
            || invocation.ArgumentList.Arguments.Count != 2
            || !invocation.ArgumentList.Arguments[0].RefKindKeyword.IsKind(SyntaxKind.InKeyword)
            || !IsNamedType(model.GetTypeInfo(member.Expression).Type, "World")
            || invocation.ArgumentList.Arguments[1].Expression is not LambdaExpressionSyntax lambda)
        {
            return false;
        }

        ParameterSyntax[] parameters = LambdaParameters(lambda);
        return parameters.Length > 1
            && IsEntityParameter(model, parameters[0])
            && parameters.Skip(1).Any(static parameter => PatternLetter(parameter) == 'W');
    }

    private static bool TryGetWhereReceiver(
        InvocationExpressionSyntax invocation,
        out InvocationExpressionSyntax whereInvocation)
    {
        whereInvocation = null!;
        return invocation.Expression is MemberAccessExpressionSyntax member
            && member.Expression is InvocationExpressionSyntax candidate
            && candidate.Expression is MemberAccessExpressionSyntax whereMember
            && whereMember.Name is IdentifierNameSyntax { Identifier.ValueText: "Where" }
            && (whereInvocation = candidate) is not null;
    }

    private static bool TryReadTerminal(
        SemanticModel model,
        InvocationExpressionSyntax invocation,
        out TerminalShape? terminal)
    {
        terminal = null;
        if (invocation.Expression is not MemberAccessExpressionSyntax member)
        {
            return false;
        }

        string name = member.Name.Identifier.ValueText;
        if (name == "Destroy" && member.Name is IdentifierNameSyntax && invocation.ArgumentList.Arguments.Count == 0)
        {
            terminal = new TerminalShape(TerminalKind.Destroy, string.Empty, 0, hasEntity: false);
            return true;
        }

        if (name is "Add" or "Remove"
            && member.Name is GenericNameSyntax genericName
            && invocation.ArgumentList.Arguments.Count == 0
            && genericName.TypeArgumentList.Arguments.Count is >= 1 and <= MaxArity)
        {
            terminal = new TerminalShape(
                name == "Add" ? TerminalKind.Add : TerminalKind.Remove,
                string.Empty,
                genericName.TypeArgumentList.Arguments.Count,
                hasEntity: false);
            return true;
        }

        if (name is not ("ForEach" or "ForEachEntity")
            || member.Name is not IdentifierNameSyntax
            || invocation.ArgumentList.Arguments.Count != 1
            || invocation.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lambda)
        {
            return false;
        }

        ParameterSyntax[] parameters = LambdaParameters(lambda);
        bool hasEntity = name == "ForEachEntity";
        int componentStart = 0;
        if (hasEntity)
        {
            if (parameters.Length == 0 || !IsEntityParameter(model, parameters[0], allowImplicit: true))
            {
                return false;
            }

            componentStart = 1;
        }

        ParameterSyntax[] components = parameters.Skip(componentStart).ToArray();
        if (components.Length > MaxArity || components.Any(parameter => !HasTypedAccessibleParameter(model, parameter)))
        {
            return false;
        }

        terminal = new TerminalShape(
            hasEntity ? TerminalKind.ForEachEntity : TerminalKind.ForEach,
            new string(components.Select(PatternLetter).ToArray()),
            components.Length,
            hasEntity);
        return true;
    }

    private static bool HasTypedAccessibleParameter(SemanticModel model, ParameterSyntax parameter)
    {
        ITypeSymbol? type = parameter.Type is null ? null : model.GetTypeInfo(parameter.Type).Type;
        return type is not null
            && type.TypeKind != TypeKind.Error
            && type is not ITypeParameterSymbol
            && IsAccessibleToGeneratedCode(type)
            && IsSupportedRefKind(parameter);
    }

    private static bool IsSupportedRefKind(ParameterSyntax parameter)
    {
        bool hasRef = parameter.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.RefKeyword));
        bool hasReadonly = parameter.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.ReadOnlyKeyword));
        bool hasIn = parameter.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.InKeyword));
        return !hasIn || (!hasRef && !hasReadonly);
    }

    private static bool IsEntityParameter(SemanticModel model, ParameterSyntax parameter, bool allowImplicit = false)
        => parameter.Modifiers.Count == 0
            && ((parameter.Type is not null && IsNamedType(model.GetTypeInfo(parameter.Type).Type, "Entity"))
                || (allowImplicit && parameter.Type is null));

    private static bool IsNamedType(ITypeSymbol? type, string name)
        => type is INamedTypeSymbol named
            && named.Name == name
            && named.ContainingNamespace.ToDisplayString() == "Delta.ECS";

    private static ParameterSyntax[] LambdaParameters(LambdaExpressionSyntax lambda)
        => lambda switch
        {
            ParenthesizedLambdaExpressionSyntax parenthesized => parenthesized.ParameterList.Parameters.ToArray(),
            SimpleLambdaExpressionSyntax simple => new[] { simple.Parameter },
            _ => Array.Empty<ParameterSyntax>()
        };

    private static char PatternLetter(ParameterSyntax parameter)
    {
        bool hasRef = parameter.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.RefKeyword));
        bool hasReadonly = parameter.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.ReadOnlyKeyword));
        if (hasRef && hasReadonly)
        {
            return 'R';
        }

        if (hasRef)
        {
            return 'W';
        }

        return parameter.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.InKeyword)) ? 'I' : 'V';
    }

    private static bool IsAccessibleToGeneratedCode(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array)
        {
            return IsAccessibleToGeneratedCode(array.ElementType);
        }

        if (type is not INamedTypeSymbol named)
        {
            return true;
        }

        return named.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal
            && (named.ContainingType is null || IsAccessibleToGeneratedCode(named.ContainingType));
    }

    private static string Render(PredicateShape shape)
    {
        string hash = StableName(shape.Key);
        var source = new StringBuilder(32 * 1024);
        source.Append(Header);
        RenderPredicateDelegate(source, shape, hash);
        foreach (TerminalShape terminal in shape.Terminals.Values.OrderBy(static value => value.Key, StringComparer.Ordinal))
        {
            RenderActionDelegate(source, terminal, hash);
            RenderInvoker(source, shape, terminal, hash);
        }

        RenderView(source, shape, hash);
        RenderExtension(source, shape, hash);
        source.AppendLine("}");
        return GeneratedSourceFormatter.Format(source.ToString());
    }

    private static void RenderPredicateDelegate(StringBuilder source, PredicateShape shape, string hash)
    {
        source.Append("public delegate bool GeneratedWherePredicate_").Append(hash).Append(GenericParameters(shape.Arity));
        source.Append("(Entity entity");
        for (int index = 0; index < shape.Arity; index++)
        {
            source.Append(", ").Append(ParameterPrefix(shape.Pattern[index])).Append("T").Append(index + 1).Append(" component").Append(index);
        }

        source.AppendLine(");");
    }

    private static void RenderActionDelegate(StringBuilder source, TerminalShape terminal, string predicateHash)
    {
        if (!terminal.IsCallback)
        {
            return;
        }

        string hash = StableName(terminal.Key);
        source.Append("public delegate void GeneratedWhereAction_").Append(predicateHash).Append('_').Append(hash)
            .Append(GenericTypes(terminal.Arity, "U")).Append('(');
        var parameters = new List<string>();
        if (terminal.HasEntity)
        {
            parameters.Add("Entity entity");
        }

        for (int index = 0; index < terminal.Arity; index++)
        {
            parameters.Add(ParameterPrefix(terminal.Pattern[index]) + "U" + (index + 1) + " component" + index);
        }

        source.Append(string.Join(", ", parameters)).AppendLine(");");
    }

    private static void RenderInvoker(StringBuilder source, PredicateShape shape, TerminalShape terminal, string hash)
    {
        string terminalHash = StableName(terminal.Key);
        string invokerName = "GeneratedWhereInvoker_" + hash + '_' + terminalHash;
        string generic = JoinGeneric(GenericList(shape.Arity), terminal.IsCallback ? GenericList(terminal.Arity, "U") : string.Empty);
        source.Append("internal struct ").Append(invokerName).Append(GenericParameters(generic)).AppendLine(" : IGeneratedWhereInvoker");
        source.AppendLine("{");
        source.Append("    private readonly GeneratedWherePredicate_").Append(hash).Append(GenericTypes(shape.Arity)).AppendLine(" _predicate;");
        if (terminal.IsCallback)
        {
            source.Append("    private readonly GeneratedWhereAction_").Append(hash).Append('_').Append(terminalHash).Append(GenericTypes(terminal.Arity, "U")).AppendLine(" _action;");
        }

        int accessCount = shape.Arity + (terminal.IsCallback ? terminal.Arity : 0);
        for (int index = 0; index < accessCount; index++)
        {
            source.Append("    private readonly int _access").Append(index).AppendLine(";");
        }

        source.Append("    internal ").Append(invokerName).Append('(')
            .Append("GeneratedWherePredicate_").Append(hash).Append(GenericTypes(shape.Arity)).Append(" predicate");
        if (terminal.IsCallback)
        {
            source.Append(", GeneratedWhereAction_").Append(hash).Append('_').Append(terminalHash).Append(GenericTypes(terminal.Arity, "U")).Append(" action");
        }

        for (int index = 0; index < accessCount; index++)
        {
            source.Append(", ").Append(AccessType(index < shape.Arity ? shape.Pattern[index] : terminal.Pattern[index - shape.Arity]))
                .Append(" access").Append(index);
        }

        source.AppendLine(")");
        source.AppendLine("    {");
        source.AppendLine("        _predicate = predicate;");
        if (terminal.IsCallback)
        {
            source.AppendLine("        _action = action;");
        }

        for (int index = 0; index < accessCount; index++)
        {
            source.Append("        _access").Append(index).Append(" = GeneratedForEachRuntime.Get")
                .Append(index < shape.Arity ? IsWrite(shape.Pattern[index]) ? "Write" : "Read" : IsWrite(terminal.Pattern[index - shape.Arity]) ? "Write" : "Read")
                .AppendLine("QueryComponentIndex(access" + index + ");");
        }

        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public bool Invoke(ref GeneratedQuerySlots slots, int index)");
        source.AppendLine("    {");
        RenderComponentLocals(source, shape.Pattern, shape.Arity, "T", "        ");
        source.AppendLine("        Entity entity = slots.EntityAt(index);");
        source.Append("        if (!_predicate(entity");
        for (int index = 0; index < shape.Arity; index++)
        {
            source.Append(", ").Append(InvocationPrefix(shape.Pattern[index])).Append("component").Append(index);
        }

        source.AppendLine("))");
        source.AppendLine("        {");
        source.AppendLine("            return false;");
        source.AppendLine("        }");
        if (terminal.IsCallback)
        {
            RenderComponentLocals(source, terminal.Pattern, terminal.Arity, "U", "        ", shape.Arity);
            source.Append("        _action(");
            var arguments = new List<string>();
            if (terminal.HasEntity)
            {
                arguments.Add("entity");
            }

            for (int index = 0; index < terminal.Arity; index++)
            {
                arguments.Add(InvocationPrefix(terminal.Pattern[index]) + "component" + (shape.Arity + index));
            }

            source.Append(string.Join(", ", arguments)).AppendLine(");");
        }

        source.AppendLine("        return true;");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void RenderComponentLocals(
        StringBuilder source,
        string pattern,
        int arity,
        string genericPrefix,
        string indent,
        int indexOffset = 0)
    {
        for (int index = 0; index < arity; index++)
        {
            int accessIndex = index + indexOffset;
            source.Append(indent).Append(IsWrite(pattern[index]) ? "ref " : "ref readonly ")
                .Append(genericPrefix).Append(index + 1).Append(" row").Append(accessIndex)
                .Append(" = ref slots.GetGenerated").Append(IsWrite(pattern[index]) ? "Write" : "Read")
                .Append("Reference<").Append(genericPrefix).Append(index + 1).Append(">(_access").Append(accessIndex).AppendLine(");");
            source.Append(indent).Append(IsWrite(pattern[index]) ? "ref " : "ref readonly ")
                .Append(genericPrefix).Append(index + 1).Append(" component").Append(accessIndex)
                .Append(" = ref global::System.Runtime.CompilerServices.Unsafe.Add(")
                .Append(IsWrite(pattern[index])
                    ? "ref row"
                    : "ref global::System.Runtime.CompilerServices.Unsafe.AsRef(in row")
                .Append(accessIndex)
                .Append(IsWrite(pattern[index]) ? ", index);" : "), index);")
                .AppendLine();
        }
    }

    private static void RenderView(StringBuilder source, PredicateShape shape, string hash)
    {
        string typeName = "GeneratedWhereQuery_" + hash;
        source.Append("public readonly ref struct ").Append(typeName).Append(GenericParameters(shape.Arity)).AppendLine();
        source.AppendLine("{");
        source.AppendLine("    private readonly World _world;");
        source.AppendLine("    private readonly Query _query;");
        source.Append("    private readonly GeneratedWherePredicate_").Append(hash).Append(GenericTypes(shape.Arity)).AppendLine(" _predicate;");
        source.Append("    internal ").Append(typeName).Append('(').Append("World world, in Query query, GeneratedWherePredicate_").Append(hash).Append(GenericTypes(shape.Arity)).AppendLine(" predicate)");
        source.AppendLine("    {");
        source.AppendLine("        _world = world;");
        source.AppendLine("        _query = query;");
        source.AppendLine("        _predicate = predicate;");
        source.AppendLine("    }");

        foreach (TerminalShape terminal in shape.Terminals.Values.OrderBy(static value => value.Key, StringComparer.Ordinal))
        {
            RenderViewTerminal(source, shape, terminal, hash);
        }

        source.AppendLine("}");
        source.AppendLine();
    }

    private static void RenderViewTerminal(StringBuilder source, PredicateShape shape, TerminalShape terminal, string hash)
    {
        string terminalHash = StableName(terminal.Key);
        string invokerName = "GeneratedWhereInvoker_" + hash + '_' + terminalHash;
        string generic = terminal.Kind is TerminalKind.Add or TerminalKind.Remove || terminal.IsCallback
            ? GenericList(terminal.Arity, "U")
            : string.Empty;
        string genericParameters = GenericParameters(generic);
        string actionType = terminal.IsCallback
            ? "GeneratedWhereAction_" + hash + '_' + terminalHash + GenericTypes(terminal.Arity, "U")
            : string.Empty;
        string signature = terminal.Kind switch
        {
            TerminalKind.Destroy => "public int Destroy()",
            TerminalKind.Add => "public int Add" + genericParameters + "()",
            TerminalKind.Remove => "public int Remove" + genericParameters + "()",
            TerminalKind.ForEach => "public void ForEach" + genericParameters + "(" + actionType + " action)",
            TerminalKind.ForEachEntity => "public void ForEachEntity" + genericParameters + "(" + actionType + " action)",
            _ => string.Empty
        };
        source.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        source.Append("    ").AppendLine(signature);
        source.AppendLine("    {");
        if (terminal.IsCallback)
        {
            source.AppendLine("        GeneratedForEachRuntime.ThrowIfNull(action, nameof(action));");
        }

        source.AppendLine("        GeneratedForEachRuntime.ValidateGeneratedWhere(_world, in _query);");
        int accessCount = shape.Arity + (terminal.IsCallback ? terminal.Arity : 0);
        for (int index = 0; index < accessCount; index++)
        {
            string componentType = index < shape.Arity ? "T" + (index + 1) : "U" + (index - shape.Arity + 1);
            string pattern = index < shape.Arity ? shape.Pattern : terminal.Pattern;
            int patternIndex = index < shape.Arity ? index : index - shape.Arity;
            source.Append("        var access").Append(index).Append(" = GeneratedForEachRuntime.GetPrepared")
                .Append(IsWrite(pattern[patternIndex]) ? "Write" : "Read")
                .Append("Access<").Append(componentType).AppendLine(">(in _query);");
        }

        string invokerGeneric = GenericParameters(
            JoinGeneric(GenericList(shape.Arity), terminal.IsCallback ? GenericList(terminal.Arity, "U") : string.Empty));
        source.Append("        var invoker = new ").Append(invokerName).Append(invokerGeneric).Append("(_predicate");
        if (terminal.IsCallback)
        {
            source.Append(", action");
        }

        for (int index = 0; index < accessCount; index++)
        {
            source.Append(", access").Append(index);
        }

        source.AppendLine(");");
        string writes = WriteIndices(shape.Pattern, terminal.Pattern, shape.Arity);
        if (terminal.Kind is TerminalKind.Add or TerminalKind.Remove)
        {
            source.Append("        Span<ComponentId> components = stackalloc ComponentId[").Append(terminal.Arity).AppendLine("];");
            for (int index = 0; index < terminal.Arity; index++)
            {
                source.Append("        components[").Append(index).Append("] = _world.Layouts.GetPrimary<U").Append(index + 1).AppendLine(">();");
            }
        }

        source.Append("        ");
        switch (terminal.Kind)
        {
            case TerminalKind.Destroy:
                source.Append("return GeneratedForEachRuntime.ExecuteGeneratedWhereDestroy(_world, in _query, ref invoker, ").Append(writes).AppendLine(");");
                break;
            case TerminalKind.Add:
                source.Append("return GeneratedForEachRuntime.ExecuteGeneratedWhereAdd(_world, in _query, ref invoker, ").Append(writes).AppendLine(", components);");
                break;
            case TerminalKind.Remove:
                source.Append("return GeneratedForEachRuntime.ExecuteGeneratedWhereRemove(_world, in _query, ref invoker, ").Append(writes).AppendLine(", components);");
                break;
            default:
                source.Append("GeneratedForEachRuntime.ExecuteGeneratedWhereForEach(_world, in _query, ref invoker, ").Append(writes).AppendLine(");");
                break;
        }

        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void RenderExtension(StringBuilder source, PredicateShape shape, string hash)
    {
        string typeName = "GeneratedWhereQuery_" + hash;
        source.Append("public static class GeneratedWhereExtensions_").Append(hash).AppendLine();
        source.AppendLine("{");
        source.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        source.Append("    public static ").Append(typeName).Append(GenericTypes(shape.Arity)).Append(" Where").Append(GenericParameters(shape.Arity)).Append("(this World world, in Query query, GeneratedWherePredicate_").Append(hash).Append(GenericTypes(shape.Arity)).AppendLine(" predicate)");
        source.AppendLine("    {");
        source.AppendLine("        GeneratedForEachRuntime.ThrowIfNull(world, nameof(world));");
        source.AppendLine("        GeneratedForEachRuntime.ThrowIfNull(predicate, nameof(predicate));");
        source.Append("        return new ").Append(typeName).Append(GenericTypes(shape.Arity)).AppendLine("(world, in query, predicate);");
        source.AppendLine("    }");
        source.AppendLine("}");
    }

    private static string WriteIndices(string predicatePattern, string terminalPattern, int predicateArity)
    {
        var values = new List<string>();
        for (int index = 0; index < predicatePattern.Length; index++)
        {
            if (IsWrite(predicatePattern[index]))
            {
                values.Add("GeneratedForEachRuntime.GetWriteQueryComponentIndex(access" + index + ")");
            }
        }

        for (int index = 0; index < terminalPattern.Length; index++)
        {
            if (IsWrite(terminalPattern[index]))
            {
                values.Add("GeneratedForEachRuntime.GetWriteQueryComponentIndex(access" + (predicateArity + index) + ")");
            }
        }

        if (values.Count == 0)
        {
            return "global::System.ReadOnlySpan<int>.Empty";
        }

        return "stackalloc int[] { " + string.Join(", ", values) + " }";
    }

    private static string AccessType(char mode) => IsWrite(mode) ? "WriteAccess" : "ReadAccess";

    private static bool IsWrite(char mode) => mode == 'W';

    private static string ParameterPrefix(char mode)
        => mode switch
        {
            'R' => "ref readonly ",
            'W' => "ref ",
            'I' => "in ",
            _ => string.Empty
        };

    private static string InvocationPrefix(char mode)
        => mode is 'R' or 'I' ? "in " : mode == 'W' ? "ref " : string.Empty;

    private static string GenericList(int arity, string prefix = "T")
    {
        if (arity == 0)
        {
            return string.Empty;
        }

        var values = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            values[index] = prefix + (index + 1).ToString(CultureInfo.InvariantCulture);
        }

        return string.Join(", ", values);
    }

    private static string GenericTypes(int arity, string prefix = "T")
        => GenericParameters(GenericList(arity, prefix));

    private static string GenericParameters(int arity) => GenericTypes(arity);

    private static string GenericParameters(string generic)
        => string.IsNullOrEmpty(generic) ? string.Empty : "<" + generic + ">";

    private static string JoinGeneric(string first, string second)
        => string.IsNullOrEmpty(first) ? second : string.IsNullOrEmpty(second) ? first : first + ", " + second;

    private static string StableName(string value)
    {
        unchecked
        {
            uint hash = 2166136261;
            foreach (char character in value)
            {
                hash = (hash ^ character) * 16777619;
            }

            return hash.ToString("X8", CultureInfo.InvariantCulture);
        }
    }

    private sealed class PredicateShape
    {
        internal PredicateShape(string pattern)
        {
            Pattern = pattern;
        }

        internal string Pattern { get; }
        internal int Arity => Pattern.Length;
        internal Dictionary<string, TerminalShape> Terminals { get; } = new(StringComparer.Ordinal);
        internal string Key => "Where|" + Pattern;
    }

    private sealed class TerminalShape
    {
        internal TerminalShape(TerminalKind kind, string pattern, int arity, bool hasEntity)
        {
            Kind = kind;
            Pattern = pattern;
            Arity = arity;
            HasEntity = hasEntity;
        }

        internal TerminalKind Kind { get; }
        internal string Pattern { get; }
        internal int Arity { get; }
        internal bool HasEntity { get; }
        internal bool IsCallback => Kind is TerminalKind.ForEach or TerminalKind.ForEachEntity;
        internal string Key => Kind + "|" + Pattern + "|" + Arity.ToString(CultureInfo.InvariantCulture) + "|" + HasEntity;
    }

    private enum TerminalKind
    {
        Destroy,
        Add,
        Remove,
        ForEach,
        ForEachEntity
    }
}
