using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Delta.ECS.Generators;

/// <summary>
/// Generates typed query factories only for the WhereAll, WhereAny and
/// WhereNone shapes used by a consumer compilation.
/// </summary>
[Generator]
public sealed class GeneratedQueryGenerator : IIncrementalGenerator
{
    private const int MaxArity = 256;
    private const string Header = """
        // <auto-generated />
        #nullable enable
        namespace Delta.ECS;

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (productionContext, compilation) => Execute(compilation, productionContext));
    }

    private static void Execute(Compilation compilation, SourceProductionContext context)
    {
        var shapes = new Dictionary<string, QueryShape>(StringComparer.Ordinal);
        foreach (SyntaxTree tree in compilation.SyntaxTrees)
        {
            SemanticModel model = compilation.GetSemanticModel(tree);
            foreach (InvocationExpressionSyntax invocation in tree.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                if (!TryReadShape(model, invocation, out QueryShape? shape)
                    || shape is null)
                {
                    continue;
                }

                if (!shapes.ContainsKey(shape.Key))
                {
                    shapes.Add(shape.Key, shape);
                }
            }
        }

        foreach (QueryShape shape in shapes.Values.OrderBy(static value => value.Key, StringComparer.Ordinal))
        {
            context.AddSource(
                "GeneratedQuery_" + StableName(shape.Key) + ".g.cs",
                Render(shape));
        }
    }

    private static bool TryReadShape(
        SemanticModel model,
        InvocationExpressionSyntax invocation,
        out QueryShape? shape)
    {
        shape = null;
        if (invocation.Expression is not MemberAccessExpressionSyntax member
            || member.Name is not GenericNameSyntax genericName
            || genericName.Identifier.ValueText is not ("WhereAll" or "WhereAny" or "WhereNone")
            || invocation.ArgumentList.Arguments.Count != 0)
        {
            return false;
        }

        if (model.GetTypeInfo(member.Expression).Type is not INamedTypeSymbol receiver
            || receiver.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) != "global::Delta.ECS.World")
        {
            return false;
        }

        int arity = genericName.TypeArgumentList.Arguments.Count;
        if (arity is < 1 or > MaxArity)
        {
            return false;
        }

        var componentTypes = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            ITypeSymbol? type = model.GetTypeInfo(genericName.TypeArgumentList.Arguments[index]).Type;
            if (type is null
                || type.TypeKind == TypeKind.Error
                || type is ITypeParameterSymbol
                || !IsAccessibleToGeneratedCode(type))
            {
                return false;
            }

            componentTypes[index] = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        shape = new QueryShape(genericName.Identifier.ValueText, componentTypes);
        return true;
    }

    private static bool IsAccessibleToGeneratedCode(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol array)
        {
            return IsAccessibleToGeneratedCode(array.ElementType);
        }

        if (type is not INamedTypeSymbol named)
        {
            return true;
        }

        if (named.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
        {
            return false;
        }

        return named.ContainingType is null || IsAccessibleToGeneratedCode(named.ContainingType);
    }

    private static string Render(QueryShape shape)
    {
        var source = new StringBuilder(8 * 1024);
        source.Append(Header);
        source.Append("public static class GeneratedQueryExtensions_")
            .Append(StableName(shape.Key))
            .AppendLine();
        source.AppendLine("{");
        source.AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        source.Append("    public static Query ")
            .Append(shape.Kind)
            .Append('<')
            .Append(GenericTypes(shape.Arity))
            .AppendLine(">(this World world)");
        source.AppendLine("    {");
        source.Append("        global::System.Span<ComponentId> components = stackalloc ComponentId[")
            .Append(shape.Arity.ToString(CultureInfo.InvariantCulture))
            .AppendLine("];");

        for (int index = 0; index < shape.Arity; index++)
        {
            source.Append("        components[")
                .Append(index.ToString(CultureInfo.InvariantCulture))
                .Append("] = world.Layouts.GetPrimary<T")
                .Append((index + 1).ToString(CultureInfo.InvariantCulture))
                .AppendLine(">();");
        }

        source.Append("        return world.CreateQuery(QuerySpec.")
            .Append(shape.Kind)
            .AppendLine("(components));");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static string GenericTypes(int arity)
    {
        var values = new string[arity];
        for (int index = 0; index < arity; index++)
        {
            values[index] = "T" + (index + 1).ToString(CultureInfo.InvariantCulture);
        }

        return string.Join(", ", values);
    }

    private static string StableName(string value)
    {
        unchecked
        {
            uint hash = 2166136261;
            foreach (char character in value)
            {
                hash = (hash ^ character) * 16777619;
            }

            return hash.ToString("X8", CultureInfo.InvariantCulture);
        }
    }

    private sealed class QueryShape
    {
        internal QueryShape(string kind, string[] componentTypes)
        {
            Kind = kind;
            ComponentTypes = componentTypes;
        }

        internal string Kind { get; }
        internal string[] ComponentTypes { get; }
        internal int Arity => ComponentTypes.Length;
        internal string Key => Kind + "|" + string.Join("|", ComponentTypes);
    }
}
