using System.Collections.Immutable;

namespace Delta.ECS.Generators;

internal static class GenericFunctorTemplates
{
    internal static string RenderOverloads(int arity)
    {
        List<string> members = RenderMembers(arity, dynamicIds: false);
        string source = $$"""
            // <auto-generated />
            namespace Delta.ECS
            {
                public static class GenericFunctorArguments{{arity}}
                {
            {{GeneratorTemplates.Indent(string.Join("\n\n", members), "        ")}}
                }
            }
            """;
        return GeneratorTemplates.FileTemplate(new GeneratedFileModel(string.Empty,
            ImmutableArray<string>.Empty, ImmutableArray.Create(source)));
    }

    internal static string RenderDynamicOverloads()
    {
        List<string> members = RenderMembers(arity: 0, dynamicIds: true);
        string source = $$"""
            // <auto-generated />
            namespace Delta.ECS
            {
                public static class GenericFunctorDynamicArguments
                {
            {{GeneratorTemplates.Indent(string.Join("\n\n", members), "        ")}}
                }
            }
            """;
        return GeneratorTemplates.FileTemplate(new GeneratedFileModel(string.Empty,
            ImmutableArray<string>.Empty, ImmutableArray.Create(source)));
    }

    private static List<string> RenderMembers(int arity, bool dynamicIds)
    {
        string ids = dynamicIds ? string.Empty : GeneratorTemplates.JoinIndexed(arity, static index => $"global::Delta.ECS.ComponentId functorArgument{index}");
        string idValues = dynamicIds ? string.Empty : GeneratorTemplates.JoinIndexed(arity, static index => $"functorArgument{index}");
        var members = new List<string>();
        foreach (string method in new[] { "ForEach", "ForEachEntity", "ForEachParallel", "ForEachEntityParallel" })
        {
            bool parallel = method.EndsWith("Parallel", StringComparison.Ordinal);
            foreach (bool entityList in new[] { false, true })
            {
                string mode = method switch
                {
                    "ForEach" => "Components",
                    "ForEachEntity" => "Entity",
                    "ForEachParallel" => "ParallelComponents",
                    _ => "ParallelEntity",
                };
                if (entityList)
                {
                    mode = mode switch
                    {
                        "Components" => "EntityList",
                        "Entity" => "EntityListEntity",
                        "ParallelComponents" => "EntityListParallel",
                        _ => "EntityListParallelEntity",
                    };
                }

                foreach (bool hasQuery in entityList ? new[] { false, true } : new[] { true })
                {
                    foreach (bool hasContext in new[] { false, true })
                    {
                        members.Add(RenderOverload(method, mode, entityList, hasQuery, parallel, hasContext, dynamicIds, ids, idValues));
                    }
                }
            }
        }

        return members;
    }

    internal static string Render(GenericFunctorModel model)
    {
        string name = "GenericFunctorExecutor_" + GeneratorSupport.StableName(model.TypeName);
        string generic = "<" + model.TypeParameters + ">";
        string selectors = GeneratorTemplates.JoinIndexed(model.Rows.Length, index => model.Rows[index].Selector);
        string arguments = GeneratorTemplates.JoinIndexed(model.Rows.Length, index => $"components[{index}]");
        var kernels = new List<string>();
        foreach (bool target in new[] { false, true })
        {
            foreach (bool parallel in new[] { false, true })
            {
                string methodName = target
                    ? parallel ? "ExecuteEntityListParallel" : "ExecuteEntityList"
                    : parallel ? "ExecuteParallel" : "ExecuteTyped";
                var shape = new IterationModel(
                    RegistrationBindingKind.Explicit,
                    hasEntity: model.HasEntity,
                    hasContext: model.HasContext,
                    isFunctor: true,
                    new string(model.Rows.Select(static row => row.Pattern).ToArray()),
                    model.Rows.Select(static row => row.TypeName).ToArray(),
                    model.TypeName,
                    contextType: model.ContextType,
                    parallel: parallel,
                    contextMode: model.ContextMode,
                    hasEntityTarget: target,
                    typeBinding: TypeBindingKind.CallbackInferred);
                kernels.Add(DemandDrivenForEachTemplates.RenderGenericFunctorKernel(shape, methodName));
            }
        }

        string callbackEntity = model.HasEntity ? "true" : "false";
        string contextGenericInterface = model.HasContext
            ? $"global::Delta.ECS.IGeneratedGenericFunctor<{model.ContextType}>"
            : "global::Delta.ECS.IGeneratedGenericFunctor";
        string contextOverload = model.HasContext
            ? $$"""

                    void global::Delta.ECS.IGeneratedGenericFunctor<{{model.ContextType}}>.Execute(
                        global::Delta.ECS.World world,
                        in global::Delta.ECS.Query query,
                        global::System.ReadOnlySpan<global::Delta.ECS.Entity> entities,
                        bool hasQuery,
                        global::Delta.ECS.GeneratedGenericFunctorMode mode,
                        int workerCount,
                        ref {{model.ContextType}} context,
                        global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> genericArguments)
                    {
                        {{RenderExecuteBody(model, arguments, callbackEntity, "context")}}
                    }
            """
            : string.Empty;
        string noContextExecute = model.HasContext
            ? "global::Delta.ECS.GeneratedForEachRuntime.ThrowGenericFunctorRequiresContext(typeof(" + model.TypeName + "));"
            : RenderExecuteBody(model, arguments, callbackEntity, null);
        string source = $$"""
            namespace Delta.ECS.Generated
            {
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                public sealed class {{name}}{{generic}} : {{contextGenericInterface}}
                {{model.Constraints}}
                {
                    private global::Delta.ECS.ComponentId[]? _components;

                    public {{name}}() { }

                    global::Delta.ECS.Query global::Delta.ECS.IGeneratedGenericFunctor.CreateQuery(
                        global::Delta.ECS.World world,
                        global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> genericArguments)
                    {
                        var components = _components ??= new global::Delta.ECS.ComponentId[] { {{selectors}} };
                        return world.WhereAll(components);
                    }

                    void global::Delta.ECS.IGeneratedGenericFunctor.Execute(
                        global::Delta.ECS.World world,
                        in global::Delta.ECS.Query query,
                        global::System.ReadOnlySpan<global::Delta.ECS.Entity> entities,
                        bool hasQuery,
                        global::Delta.ECS.GeneratedGenericFunctorMode mode,
                        int workerCount,
                        global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> genericArguments)
                    {
                        {{noContextExecute}}
                    }

            {{contextOverload}}

                    {{string.Join("\n", kernels)}}
                }
            }
            """;
        return GeneratorTemplates.FileTemplate(new GeneratedFileModel(string.Empty,
            ImmutableArray.Create("using global::Delta.ECS;", "using global::System;"), ImmutableArray.Create(source)));
    }

    private static string RenderOverload(
        string method,
        string mode,
        bool entityList,
        bool hasQuery,
        bool parallel,
        bool hasContext,
        bool dynamicIds,
        string ids,
        string idValues)
    {
        var parameters = new List<string> { "this global::Delta.ECS.World world" };
        if (entityList)
        {
            parameters.Add("global::System.ReadOnlySpan<global::Delta.ECS.Entity> entities");
        }

        if (hasQuery)
        {
            parameters.Add("in global::Delta.ECS.Query query");
        }

        if (hasContext)
        {
            parameters.Add("ref TContext context");
        }

        parameters.Add(dynamicIds
            ? "global::System.ReadOnlySpan<global::Delta.ECS.ComponentId> functorArguments"
            : ids);
        parameters.Add("global::System.Type functorType");
        if (parallel)
        {
            parameters.Add("int workerCount = 0");
        }

        string generic = hasContext ? "<TContext>" : string.Empty;
        string contextCall = hasContext ? "context, " : string.Empty;
        string argumentList = dynamicIds
            ? "functorArguments"
            : $"stackalloc global::Delta.ECS.ComponentId[] {{ {idValues} }}";
        string componentArguments = dynamicIds ? "functorArguments" : argumentList;

        string queryArgument = "in operationQuery";
        string entitiesArgument = entityList ? "entities" : "global::System.ReadOnlySpan<global::Delta.ECS.Entity>.Empty";
        string call = hasContext
            ? $"return world.CreateGenericFunctorOperation<TContext>({queryArgument}, {entitiesArgument}, {hasQuery.ToString().ToLowerInvariant()}, global::Delta.ECS.GeneratedGenericFunctorMode.{mode}, functorType, {(parallel ? "workerCount" : "0")}, {contextCall}{componentArguments});"
            : $"return world.CreateGenericFunctorOperation({queryArgument}, {entitiesArgument}, {hasQuery.ToString().ToLowerInvariant()}, global::Delta.ECS.GeneratedGenericFunctorMode.{mode}, functorType, {(parallel ? "workerCount" : "0")}, {componentArguments});";
        var setup = new List<string>();
        setup.Add(hasQuery
            ? "global::Delta.ECS.Query operationQuery = query;"
            : "global::Delta.ECS.Query operationQuery = default;");
        setup.Add(call);
        string body = string.Join("\n", setup);
        string operationType = hasContext
            ? "global::Delta.ECS.EcsOperation<TContext, global::Delta.ECS.World.GenericFunctorContextOperationInvoker<TContext>>"
            : "global::Delta.ECS.EcsOperation<global::Delta.ECS.World.GenericFunctorOperationInvoker>";
        return $"public static {operationType} {method}{generic}({string.Join(", ", parameters)})\n{{\n{GeneratorTemplates.Indent(body, "    ")}\n}}";
    }

    private static string RenderExecuteBody(GenericFunctorModel model, string arguments, string callbackEntity, string? context)
    {
        string parallelRefGuard = model.HasContext && model.ContextMode == ContextModeKind.Ref
            ? "if (mode is global::Delta.ECS.GeneratedGenericFunctorMode.ParallelComponents or global::Delta.ECS.GeneratedGenericFunctorMode.ParallelEntity or global::Delta.ECS.GeneratedGenericFunctorMode.EntityListParallel or global::Delta.ECS.GeneratedGenericFunctorMode.EntityListParallelEntity)\n{\n    global::Delta.ECS.GeneratedForEachRuntime.ThrowGenericFunctorParallelRefContext(typeof(" + model.TypeName + "));\n}\n"
            : string.Empty;
        string? contextArgument = model.HasContext
            ? SignatureProjection.ContextArgument(model.ContextMode, context!)
            : null;
        string call(string method, bool entityList, bool parallel)
        {
            var callArguments = new List<string> { "world" };
            if (entityList)
            {
                callArguments.Add("entities");
            }

            callArguments.Add("in selectedQuery");
            if (arguments.Length > 0)
            {
                callArguments.Add(arguments);
            }

            if (contextArgument is not null)
            {
                callArguments.Add(contextArgument);
            }

            callArguments.Add("ref functor");
            if (parallel)
            {
                callArguments.Add("workerCount");
            }

            return $"{method}({string.Join(", ", callArguments)});";
        }
        return $$"""
            var components = _components ??= new global::Delta.ECS.ComponentId[] { {{GeneratorTemplates.JoinIndexed(model.Rows.Length, index => model.Rows[index].Selector)}} };
            global::Delta.ECS.Query selectedQuery = hasQuery ? query : world.WhereAll(components);
            var functor = default({{model.TypeName}});
            if (((mode is global::Delta.ECS.GeneratedGenericFunctorMode.Entity or global::Delta.ECS.GeneratedGenericFunctorMode.EntityListEntity or global::Delta.ECS.GeneratedGenericFunctorMode.ParallelEntity or global::Delta.ECS.GeneratedGenericFunctorMode.EntityListParallelEntity)) != {{callbackEntity}})
            {
                global::Delta.ECS.GeneratedForEachRuntime.ThrowGenericFunctorModeMismatch(typeof({{model.TypeName}}), mode);
            }

            {{parallelRefGuard}}
            switch (mode)
            {
                case global::Delta.ECS.GeneratedGenericFunctorMode.Components:
                case global::Delta.ECS.GeneratedGenericFunctorMode.Entity:
                    {{call("ExecuteTyped", false, false)}}
                    break;
                case global::Delta.ECS.GeneratedGenericFunctorMode.EntityList:
                case global::Delta.ECS.GeneratedGenericFunctorMode.EntityListEntity:
                    {{call("ExecuteEntityList", true, false)}}
                    break;
                case global::Delta.ECS.GeneratedGenericFunctorMode.ParallelComponents:
                case global::Delta.ECS.GeneratedGenericFunctorMode.ParallelEntity:
                    {{call("ExecuteParallel", false, true)}}
                    break;
                case global::Delta.ECS.GeneratedGenericFunctorMode.EntityListParallel:
                case global::Delta.ECS.GeneratedGenericFunctorMode.EntityListParallelEntity:
                    {{call("ExecuteEntityListParallel", true, true)}}
                    break;
                default:
                    global::Delta.ECS.GeneratedForEachRuntime.ThrowInvalidGenericFunctorMode(mode);
                    break;
            }
            """;
    }
}
