using System.Collections.Immutable;

namespace Delta.ECS.Generators;

/// <summary>Raw-string templates for generated system access metadata.</summary>
internal static class GeneratedSystemAccessTemplates
{
    internal static string Render(GeneratedSystemAccessModel model)
    {
        string helper = RenderHelper(model);
        string property = model.InjectProperty ? RenderProperty(model) : string.Empty;
        string members = GeneratorTemplates.JoinNonEmpty(new[] { helper, property }, "\n\n");
        string source = string.IsNullOrEmpty(model.Namespace)
            ? $$"""
                // <auto-generated />
                #nullable enable
                {{members}}
                """
            : $$"""
                // <auto-generated />
                #nullable enable
                namespace {{model.Namespace}}
                {
                {{GeneratorTemplates.Indent(members, "    ")}}
                }
                """;
        return GeneratedSourceFormatter.Format(source);
    }

    private static string RenderHelper(GeneratedSystemAccessModel model)
    {
        string constructorArguments = GeneratorTemplates.JoinNonEmpty(
            new[]
            {
                RenderIds("reads", model.Reads),
                RenderIds("writes", model.Writes),
                RenderIds("stampReads", model.StampReads),
                RenderIds("adds", model.Adds),
                RenderIds("removes", model.Removes),
                model.ReadsTopology ? "readsTopology: true" : string.Empty,
                model.WritesTopology ? "writesTopology: true" : string.Empty,
                model.CreatesEntities ? "createsEntities: true" : string.Empty,
                model.DestroysEntities ? "destroysEntities: true" : string.Empty,
                model.UnknownWorldAccess ? "unknownWorldAccess: true" : string.Empty,
                model.UsesParallelExecutor ? "usesParallelExecutor: true" : string.Empty
            },
            ",\n");
        string result = constructorArguments.Length == 0
            ? "global::Delta.ECS.Systems.SystemAccess.None"
            : $$"""
                new global::Delta.ECS.Systems.SystemAccess(
                {{GeneratorTemplates.Indent(constructorArguments, "    ")}})
                """;
        return $$"""
            internal static class {{model.HelperName}}
            {
                internal static global::Delta.ECS.Systems.SystemAccess Create(global::Delta.ECS.World world)
                    => {{result}};
            }
            """;
    }

    private static string RenderProperty(GeneratedSystemAccessModel model)
        => $$"""
            partial class {{model.TypeName}}
            {
                /// <summary>Gets generated access metadata for this system.</summary>
                public global::Delta.ECS.Systems.SystemAccess Access
                    => {{model.HelperName}}.Create(((global::Delta.ECS.Systems.ISystem)this).World);
            }
            """;

    private static string RenderIds(string name, ImmutableArray<string> types)
        => types.IsDefaultOrEmpty
            ? string.Empty
            : $$"""
            {{name}}: new global::Delta.ECS.ComponentId[]
            {
            {{GeneratorTemplates.Indent(
                string.Join(",\n", types.Select(type => "world.Layouts.GetPrimary<" + type + ">()")),
                "    ")}}
            }
            """;
}
