using System.Collections.Immutable;

namespace Delta.ECS.Generators;

internal static class GenericBindingTemplates
{
    internal static string Render(
        IReadOnlyCollection<GenericComponentDispatcherBinding> componentDispatchers,
        IReadOnlyCollection<GenericFunctorDispatcherBinding> functorDispatchers,
        IReadOnlyCollection<GeneratedTypeTokenBinding> generatedTypeTokens,
        IReadOnlyCollection<int> componentRegistrationArities,
        bool includeGeneratedRegistrationExtension,
        bool includeModuleInitializerAttribute)
    {
        var registrations = new List<string>();
        foreach (GenericComponentDispatcherBinding binding in componentDispatchers
            .OrderBy(static binding => binding.OpenTypeName, StringComparer.Ordinal))
        {
            registrations.Add($"global::Delta.ECS.GeneratedGenericBindingRegistry.RegisterComponentDispatcher(typeof({binding.OpenTypeName}), {binding.Arity}, static (layouts, schemaId, componentArguments, typeArguments) => global::Delta.ECS.Generated.{binding.DispatcherName}.Register(layouts, schemaId, componentArguments, typeArguments));");
        }

        foreach (GenericFunctorDispatcherBinding binding in functorDispatchers
            .OrderBy(static binding => binding.OpenTypeName, StringComparer.Ordinal))
        {
            registrations.Add($"global::Delta.ECS.GeneratedGenericBindingRegistry.RegisterFunctorDispatcher(typeof({binding.OpenTypeName}), {binding.Arity}, static typeArguments => global::Delta.ECS.Generated.{binding.DispatcherName}.Create(typeArguments));");
        }

        foreach (GeneratedTypeTokenBinding binding in generatedTypeTokens
            .OrderBy(static binding => binding.ComponentTypeName, StringComparer.Ordinal))
        {
            registrations.Add($"global::Delta.ECS.GeneratedComponentTypeTokenRegistry.Register(typeof({binding.ComponentTypeName}), new global::Delta.ECS.Generated.{binding.TokenName}());");
        }

        string dispatchers = string.Join("\n\n", generatedTypeTokens
            .OrderBy(static binding => binding.ComponentTypeName, StringComparer.Ordinal)
            .Select(GenericTypeDispatchTemplates.RenderRegisteredComponentTypeToken)
            .Concat(componentDispatchers
            .OrderBy(static binding => binding.OpenTypeName, StringComparer.Ordinal)
            .Select(GenericTypeDispatchTemplates.RenderComponentDispatcher)
            .Concat(functorDispatchers
                .OrderBy(static binding => binding.OpenTypeName, StringComparer.Ordinal)
                .Select(GenericTypeDispatchTemplates.RenderFunctorDispatcher))));

        string attribute = includeModuleInitializerAttribute
            ? """
              namespace System.Runtime.CompilerServices
              {
                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
                  internal sealed class ModuleInitializerAttribute : global::System.Attribute { }
              }

              """
            : string.Empty;
        string registrationExtensions = componentRegistrationArities.Count == 0
            ? string.Empty
            : $$"""
                namespace Delta.ECS
                {
                    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                    public static class GeneratedGenericComponentRegistrationExtensions
                    {
                {{GeneratorTemplates.Indent(string.Join("\n\n", componentRegistrationArities.OrderBy(static arity => arity).Select(GenericTypeDispatchTemplates.RenderComponentRegistrationExtension)), "        ")}}
                    }
                }

                """;
        string generatedRegistrationExtension = !includeGeneratedRegistrationExtension
            ? string.Empty
            : """
                namespace Delta.ECS
                {
                    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                    public static class GeneratedComponentRegistrationExtensions
                    {
                        /// <summary>Registers a closed component using its generated constraint-capability token.</summary>
                        public static global::Delta.ECS.ComponentId RegisterGenerated<T>(
                            this global::Delta.ECS.ComponentLayoutRegistry layouts,
                            global::Delta.ECS.SchemaId schemaId)
                            => global::Delta.ECS.GeneratedGenericBindingRegistry.RegisterComponentType<T>(layouts, schemaId);
                    }
                }

                """;
        string source = $$"""
            // <auto-generated />
            {{registrationExtensions}}{{generatedRegistrationExtension}}{{attribute}}namespace Delta.ECS.Generated
            {
            {{GeneratorTemplates.Indent(dispatchers, "    ")}}

                internal static partial class GenericBindingModuleInitializer
                {
                    static partial void RegisterComponentCatalog();

                    [global::System.Runtime.CompilerServices.ModuleInitializer]
                    internal static void Initialize()
                    {
            {{GeneratorTemplates.Indent(string.Join("\n", registrations), "            ")}}
                        RegisterComponentCatalog();
                    }
                }
            }
            """;

        return GeneratorTemplates.FileTemplate(new GeneratedFileModel(string.Empty,
            ImmutableArray<string>.Empty,
            ImmutableArray.Create(source)));
    }
}
