using System.Collections.Immutable;

namespace Delta.ECS.Generators;

internal static class GenericBindingTemplates
{
    internal static string Render(
        IReadOnlyCollection<GenericComponentFactoryBinding> componentBindings,
        IReadOnlyCollection<GenericFunctorFactoryBinding> functorBindings,
        bool includeModuleInitializerAttribute)
    {
        var registrations = new List<string>();
        foreach (GenericComponentFactoryBinding binding in componentBindings
            .OrderBy(static binding => binding.GenericDefinition, StringComparer.Ordinal)
            .ThenBy(static binding => string.Join("\u001f", binding.GenericArguments), StringComparer.Ordinal))
        {
            string arguments = string.Join(", ", binding.GenericArguments.Select(static argument => $"typeof({argument})"));
            registrations.Add($"global::Delta.ECS.GeneratedGenericBindingRegistry.RegisterComponentFactory(typeof({binding.GenericDefinition}), new global::System.Type[] {{ {arguments} }}, typeof({binding.ComponentType}), static (layouts, schemaId) => layouts.Register<{binding.ComponentType}>(schemaId));");
        }

        foreach (GenericFunctorFactoryBinding binding in functorBindings
            .OrderBy(static binding => binding.GenericDefinition, StringComparer.Ordinal)
            .ThenBy(static binding => string.Join("\u001f", binding.GenericArguments), StringComparer.Ordinal))
        {
            string arguments = string.Join(", ", binding.GenericArguments.Select(static argument => $"typeof({argument})"));
            registrations.Add($"global::Delta.ECS.GeneratedGenericBindingRegistry.RegisterFunctorFactory(typeof({binding.GenericDefinition}), new global::System.Type[] {{ {arguments} }}, static () => new {binding.ExecutorType}());");
        }

        string attribute = includeModuleInitializerAttribute
            ? """
              namespace System.Runtime.CompilerServices
              {
                  [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
                  internal sealed class ModuleInitializerAttribute : global::System.Attribute { }
              }

              """
            : string.Empty;
        string source = $$"""
            // <auto-generated />
            {{attribute}}namespace Delta.ECS.Generated
            {
                internal static class GenericBindingModuleInitializer
                {
                    [global::System.Runtime.CompilerServices.ModuleInitializer]
                    internal static void Initialize()
                    {
            {{GeneratorTemplates.Indent(string.Join("\n", registrations), "            ")}}
                    }
                }
            }
            """;

        return GeneratorTemplates.FileTemplate(new GeneratedFileModel(string.Empty,
            ImmutableArray<string>.Empty,
            ImmutableArray.Create(source)));
    }
}
