<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Delta.ECS.ComponentTypeVisitor.Aot</RootNamespace>
    <AssemblyName>DeltaECS.ComponentTypeVisitor.Aot</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(PublishAot)' != 'true'">
    <ProjectReference Include="../../src/DeltaECS/DeltaECS.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(PublishAot)' == 'true'">
    <Reference Include="DeltaECS">
      <HintPath>../../src/DeltaECS/bin/$(Configuration)/net10.0/DeltaECS.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
