<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Delta.ECS.Generators.Aot</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <InterceptorsNamespaces>Delta.ECS.Generated</InterceptorsNamespaces>
    <InterceptorsPreviewNamespaces>Delta.ECS.Generated</InterceptorsPreviewNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="InterceptorsNamespaces" />
    <Reference Include="DeltaECS">
      <HintPath>../../src/DeltaECS/bin/$(Configuration)/net10.0/DeltaECS.dll</HintPath>
    </Reference>
    <Analyzer Include="../../src/DeltaECS.Generators/bin/$(Configuration)/netstandard2.0/DeltaECS.Generators.dll" />
  </ItemGroup>
</Project>
