namespace Delta.ECS;

/// <summary>
/// By-value functor compiler anchors as extension methods so they do not
/// outrank generated concrete overloads during overload resolution.
/// Instance anchors on <see cref="World"/> would always win over extensions
/// and force value calls such as <c>ForEach(in query, new Functor())</c>
/// onto the throwing stub.
/// </summary>
public static class FunctorAnchors
{
    /// <summary>
    /// Fallback when no generated component-bearing <c>ForEach</c> overload is
    /// selected. Prefer a generated by-value, <c>in</c>, <c>ref readonly</c>,
    /// or <c>ref</c> form.
    /// </summary>
    public static void ForEach<T>(this World world, in Query query, T action)
        where T : IForEach
    {
        _ = world;
        _ = query;
        _ = action;
        ThrowHelper.ThrowGeneratedFunctorRequired();
    }

    /// <summary>
    /// Fallback when no generated component-bearing <c>ForEachEntity</c>
    /// overload is selected.
    /// </summary>
    public static void ForEachEntity<T>(this World world, in Query query, T action)
        where T : IForEachEntity
    {
        _ = world;
        _ = query;
        _ = action;
        ThrowHelper.ThrowGeneratedFunctorRequired();
    }

    /// <summary>
    /// Fallback when no generated stamp <c>ForEachStamp</c> functor overload is
    /// selected.
    /// </summary>
    public static void ForEachStamp<T>(this World world, in Query query, T action)
        where T : IForEach
    {
        _ = world;
        _ = query;
        _ = action;
        ThrowHelper.ThrowGeneratedFunctorRequired();
    }

    /// <summary>
    /// Fallback when no generated stamp <c>ForEachEntityStamp</c> functor
    /// overload is selected.
    /// </summary>
    public static void ForEachEntityStamp<T>(this World world, in Query query, T action)
        where T : IForEachEntity
    {
        _ = world;
        _ = query;
        _ = action;
        ThrowHelper.ThrowGeneratedFunctorRequired();
    }

    /// <summary>
    /// Fallback when no generated parallel stamp functor overload is selected.
    /// </summary>
    public static void ForEachStampParallel<T>(
        this World world,
        in Query query,
        T action,
        int workerCount = 0)
        where T : IForEach
    {
        _ = world;
        _ = query;
        _ = action;
        _ = workerCount;
        ThrowHelper.ThrowGeneratedFunctorRequired();
    }

    /// <summary>
    /// Fallback when no generated parallel entity stamp functor overload is
    /// selected.
    /// </summary>
    public static void ForEachEntityStampParallel<T>(
        this World world,
        in Query query,
        T action,
        int workerCount = 0)
        where T : IForEachEntity
    {
        _ = world;
        _ = query;
        _ = action;
        _ = workerCount;
        ThrowHelper.ThrowGeneratedFunctorRequired();
    }
}
