<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DVG.ECS.Benchmarks</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DeltaECS\DeltaECS.csproj" />
    <ProjectReference Include="..\..\..\DeltaEngine\Depend\Arch\src\Arch\Arch.csproj" AdditionalProperties="Configuration=Release" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
    <PackageReference Include="Friflo.Engine.ECS" Version="3.6.0" />
  </ItemGroup>

</Project>
